import {accessibleInvoiceIds} from '../../services/erp/invoice-access';
import {scopeRealEstateReportInvoices} from '../../services/erp/real-estate-report-invoice-scope';
import {getErpCompanyCalendar} from '../../services/erp/company-calendar';
import {Router} from 'express';
import {z} from 'zod';
import {getPool} from '../../db';
import {storage,ErpValidationError} from '../../storage';
import {requireAnyPermission} from '../../middleware';
import {resolveContactViewScope} from '../../../shared/contact-access';
import {getZonedDateTimeParts} from '../../../shared/utils/agent-schedule';
import {parseInZoneToUTC} from '../../utils/timezone';
const router=Router();
router.get('/dashboard',requireAnyPermission(['view_real_estate_dashboard','manage_real_estate_dashboard']),async(req,res,next)=>{
 try{
 const companyId=res.locals.companyId,p=res.locals.permissions,has=(section:string)=>p[`view_real_estate_${section}`]||p[`manage_real_estate_${section}`],filter=z.object({month:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),currency:z.string().regex(/^[A-Z]{3}$/).optional()}).strict().parse(req.query);
 const first=`${filter.month}-01`,year=Number(filter.month.slice(0,4)),month=Number(filter.month.slice(5)),nextMonth=new Date(Date.UTC(year,month,1)).toISOString().slice(0,10),base=await storage.getBaseCurrency(companyId),currency=filter.currency??base?.code;
 const currencies=p.view_real_estate_financials?(await getPool().query('SELECT code,name FROM currencies WHERE company_id=$1 AND is_active=true ORDER BY code',[companyId])).rows:[];
 if(p.view_real_estate_financials&&!currencies.some(c=>c.code===currency))throw new ErpValidationError('Select an active ERP currency');
 const scope=resolveContactViewScope(p,req.user!.isSuperAdmin===true),contactIds=(await getPool().query('SELECT id FROM contacts WHERE company_id=$1',[companyId])).rows.map(r=>r.id),allowed=scope?await storage.getAccessibleContactIds(contactIds,{companyId,userId:req.user!.id,contactScope:scope}):[];
 const kinds=[...(has('properties')?['property']:[]),...(has('units')?['unit']:[])],db=getPool();
 const {timezone,today:localToday}=await getErpCompanyCalendar(companyId);
 const monthStart=parseInZoneToUTC(`${first}T00:00:00`,timezone),monthEnd=parseInZoneToUTC(`${nextMonth}T00:00:00`,timezone);
 const data:any={month:filter.month,timezone,currency:p.view_real_estate_financials?currency??null:null,currencies,properties:null,units:null,tenants:null,financial:null,maintenance:null,appointments:null,recentProperties:[],expiringLeases:[],agentPerformance:[],agentSales:[]};
 if(kinds.length){
 const status=(await db.query("SELECT kind,status,count(*)::int count FROM real_estate_assets WHERE company_id=$1 AND kind=ANY($2::text[]) AND status<>'archived' GROUP BY kind,status",[companyId,kinds])).rows;
 data.properties=has('properties')?status.filter(s=>s.kind==='property'):null;data.units=has('units')?status.filter(s=>s.kind==='unit'):null;
 data.recentProperties=(await db.query("SELECT id,kind,code,name,location,status,images FROM real_estate_assets WHERE company_id=$1 AND kind=ANY($2::text[]) AND status<>'archived' ORDER BY created_at DESC LIMIT 4",[companyId,kinds])).rows;
 }
 if(has('tenants'))data.tenants=(await db.query("SELECT count(*)::int total FROM real_estate_contact_roles WHERE company_id=$1 AND role='tenant' AND contact_id=ANY($2::int[])",[companyId,allowed])).rows[0].total;
 if(has('maintenance'))data.maintenance={...(await db.query("SELECT count(*)::int open,count(*) FILTER(WHERE priority='urgent')::int urgent FROM real_estate_maintenance WHERE company_id=$1 AND status NOT IN('completed','cancelled')",[companyId])).rows[0],recent:(await db.query("SELECT m.id,m.title,m.priority,m.status,a.name asset_name,a.kind FROM real_estate_maintenance m JOIN real_estate_assets a ON a.id=m.asset_id AND a.company_id=m.company_id WHERE m.company_id=$1 AND m.status NOT IN('completed','cancelled') ORDER BY CASE m.priority WHEN 'urgent' THEN 0 WHEN 'high' THEN 1 ELSE 2 END,m.updated_at DESC LIMIT 5",[companyId])).rows.map(r=>({...r,asset_name:kinds.includes(r.kind)?r.asset_name:null}))};
 if(has('schedule'))data.appointments={...(await db.query("SELECT count(*)::int upcoming,count(*) FILTER(WHERE e.appointment_type='viewing')::int viewings FROM real_estate_appointments e JOIN contact_appointments a ON a.id=e.appointment_id AND a.company_id=e.company_id WHERE e.company_id=$1 AND a.contact_id=ANY($2::int[]) AND a.status IN('scheduled','confirmed') AND a.scheduled_at>=now() AND a.scheduled_at<now()+interval '7 days'",[companyId,allowed])).rows[0],recent:(await db.query("SELECT a.id,a.title,a.scheduled_at,a.status,a.contact_id,c.name contact_name,p.name asset_name,p.kind,e.appointment_type FROM real_estate_appointments e JOIN contact_appointments a ON a.id=e.appointment_id AND a.company_id=e.company_id JOIN contacts c ON c.id=a.contact_id AND c.company_id=a.company_id LEFT JOIN real_estate_assets p ON p.id=e.asset_id AND p.company_id=e.company_id WHERE e.company_id=$1 AND a.contact_id=ANY($2::int[]) AND a.status IN('scheduled','confirmed') AND a.scheduled_at>=now() ORDER BY a.scheduled_at LIMIT 4",[companyId,allowed])).rows.map(r=>({...r,asset_name:kinds.includes(r.kind)?r.asset_name:null}))};
 if(has('leases'))data.expiringLeases=(await db.query("SELECT l.id,l.name,l.end_date::text,l.tenant_contact_id,c.name tenant_name,a.name asset_name,a.kind,(l.end_date-$3::date)::int days_left FROM real_estate_leases l JOIN contacts c ON c.id=l.tenant_contact_id AND c.company_id=l.company_id JOIN real_estate_assets a ON a.id=l.asset_id AND a.company_id=l.company_id WHERE l.company_id=$1 AND l.tenant_contact_id=ANY($2::int[]) AND l.status='active' AND l.end_date>=$3::date AND l.end_date<=$3::date+60 ORDER BY l.end_date LIMIT 5",[companyId,allowed,localToday])).rows.map(r=>({...r,asset_name:kinds.includes(r.kind)?r.asset_name:null}));
 if(p.view_real_estate_financials&&has('rent_collection')){
 const invoiceIds=await accessibleInvoiceIds(req);
 const financialQuery=(query:string,args:unknown[])=>{const scoped=scopeRealEstateReportInvoices(query,args,invoiceIds);return db.query(scoped.text,scoped.values);};
 const totals=(await financialQuery("SELECT COALESCE(sum(i.total_amount+(SELECT COALESCE(sum(CASE n.type WHEN 'credit_note' THEN -n.total_amount ELSE n.total_amount END),0) FROM invoices n WHERE n.company_id=i.company_id AND n.parent_invoice_id=i.id AND n.currency=i.currency AND n.type IN('credit_note','debit_note') AND n.status IN('sent','overdue','partially_paid','paid'))) FILTER(WHERE i.issue_date>=$4::date AND i.issue_date<$5::date),0)::text expected,COALESCE(sum(i.amount_due) FILTER(WHERE i.due_date::date<$6::date AND i.amount_due>0),0)::text overdue FROM invoices i JOIN real_estate_invoice_sources s ON s.invoice_id=i.id AND s.company_id=i.company_id WHERE i.company_id=$1 AND i.contact_id=ANY($2::int[]) AND i.currency=$3 AND s.source_type='rent' AND i.status NOT IN('draft','cancelled','void')",[companyId,allowed,currency,first,nextMonth,localToday])).rows[0];
 const collected=(await financialQuery("SELECT COALESCE(sum(p.amount),0)::text collected FROM invoice_payments p JOIN invoices i ON i.id=p.invoice_id AND i.company_id=p.company_id JOIN real_estate_invoice_sources s ON s.invoice_id=i.id AND s.company_id=i.company_id WHERE i.company_id=$1 AND i.contact_id=ANY($2::int[]) AND i.currency=$3 AND s.source_type='rent' AND i.status IN('sent','overdue','partially_paid','paid') AND (p.payment_date AT TIME ZONE 'UTC' AT TIME ZONE $6)>=$4::date AND (p.payment_date AT TIME ZONE 'UTC' AT TIME ZONE $6)<$5::date",[companyId,allowed,currency,first,nextMonth,timezone])).rows[0].collected;
 const series=(await financialQuery("WITH periods AS(SELECT generate_series($4::date-interval '5 months',$4::date,interval '1 month') AS period_start)SELECT to_char(periods.period_start,'YYYY-MM') AS month_key,COALESCE((SELECT sum(i.total_amount+(SELECT COALESCE(sum(CASE n.type WHEN 'credit_note' THEN -n.total_amount ELSE n.total_amount END),0) FROM invoices n WHERE n.company_id=i.company_id AND n.parent_invoice_id=i.id AND n.currency=i.currency AND n.type IN('credit_note','debit_note') AND n.status IN('sent','overdue','partially_paid','paid'))) FROM invoices i JOIN real_estate_invoice_sources s ON s.invoice_id=i.id AND s.company_id=i.company_id WHERE i.company_id=$1 AND i.contact_id=ANY($2::int[]) AND i.currency=$3 AND s.source_type='rent' AND i.status NOT IN('draft','cancelled','void') AND date_trunc('month',i.issue_date)=periods.period_start),0)::text expected,COALESCE((SELECT sum(p.amount) FROM invoice_payments p JOIN invoices i ON i.id=p.invoice_id AND i.company_id=p.company_id JOIN real_estate_invoice_sources s ON s.invoice_id=i.id AND s.company_id=i.company_id WHERE i.company_id=$1 AND i.contact_id=ANY($2::int[]) AND i.currency=$3 AND s.source_type='rent' AND i.status IN('sent','overdue','partially_paid','paid') AND date_trunc('month',p.payment_date AT TIME ZONE 'UTC' AT TIME ZONE $5)=periods.period_start),0)::text collected FROM periods ORDER BY periods.period_start",[companyId,allowed,currency,first,timezone])).rows;
 data.financial={...totals,collected,series:series.map(row=>({...row,month:row.month_key}))};
 }
 if(has('schedule'))data.agentPerformance=(await db.query("SELECT u.id,COALESCE(u.full_name,u.username) name,count(*)::int appointments,count(*) FILTER(WHERE a.status='completed')::int completed FROM real_estate_appointments e JOIN contact_appointments a ON a.id=e.appointment_id AND a.company_id=e.company_id JOIN users u ON u.id=e.agent_user_id AND u.company_id=e.company_id WHERE e.company_id=$1 AND a.contact_id=ANY($2::int[]) AND a.scheduled_at>=$3 AND a.scheduled_at<$4 GROUP BY u.id ORDER BY completed DESC,appointments DESC LIMIT 4",[companyId,allowed,monthStart,monthEnd])).rows;
 if(p.view_real_estate_financials&&has('payment_plans'))data.agentSales=(await db.query("SELECT u.id,COALESCE(u.full_name,u.username) name,count(*)::int sales,COALESCE(sum(s.sale_amount),0)::text contracted,COALESCE(sum(s.sale_amount) FILTER(WHERE s.status='handed_over'),0)::text delivered FROM real_estate_sale_agreements s JOIN real_estate_assets a ON a.id=s.asset_id AND a.company_id=s.company_id JOIN users u ON u.id=a.assigned_agent_id AND u.company_id=a.company_id WHERE s.company_id=$1 AND s.buyer_contact_id=ANY($2::int[]) AND s.currency=$3 AND s.status IN('finalized','handed_over') AND (s.finalized_at AT TIME ZONE $6)>=$4::date AND (s.finalized_at AT TIME ZONE $6)<$5::date GROUP BY u.id ORDER BY sum(s.sale_amount) DESC LIMIT 5",[companyId,allowed,currency,first,nextMonth,timezone])).rows;
 if(data.appointments)for(const appointment of data.appointments.recent)
  appointment.schedule_date=getZonedDateTimeParts(new Date(appointment.scheduled_at),timezone).dateKey;
 res.json({data});
 }catch(e){next(e);}
});
export default router;
