import {Router} from 'express';
import {z} from 'zod';
import {storage,ErpValidationError} from '../../storage';
import {getPool} from '../../db';
import {requireAnyPermission} from '../../middleware';
import {insertSupplierSchema} from '@shared/schema';
const router=Router(),read=['view_real_estate_vendors','manage_real_estate_vendors'];
router.get('/vendors',requireAnyPermission(read),async(req,res,next)=>{try{const filters=z.object({search:z.string().max(250).default(''),status:z.enum(['active','inactive']).optional(),limit:z.coerce.number().int().min(1).max(100).default(25),offset:z.coerce.number().int().min(0).default(0)}).strict().parse(req.query);res.json(await storage.getSuppliers(res.locals.companyId,filters));}catch(e){next(e);}});
router.post('/vendors',requireAnyPermission(['manage_real_estate_vendors']),async(req,res,next)=>{try{const value=insertSupplierSchema.omit({companyId:true,createdBy:true}).extend({name:z.string().trim().min(1).max(250),currency:z.string().regex(/^[A-Z]{3}$/),email:z.string().email().nullable().optional()}).strict().parse(req.body);if(!(await getPool().query('SELECT 1 FROM currencies WHERE company_id=$1 AND code=$2 AND is_active=true',[res.locals.companyId,value.currency])).rowCount)throw new ErpValidationError('Select an active ERP currency');res.status(201).json({data:await storage.createSupplier({...value,companyId:res.locals.companyId,createdBy:req.user!.id})});}catch(e){next(e);}});
router.get('/vendors/:id',requireAnyPermission(read),async(req,res,next)=>{try{const supplierId=z.coerce.number().int().positive().parse(req.params.id),companyId=res.locals.companyId,supplier=await storage.getSupplier(supplierId);if(!supplier||supplier.companyId!==companyId){res.status(404).json({error:'Vendor not found'});return;}const data:any={supplier,maintenance:[],expenses:[]};if(res.locals.permissions.view_real_estate_maintenance||res.locals.permissions.manage_real_estate_maintenance)data.maintenance=(await getPool().query('SELECT id,title,status,updated_at FROM real_estate_maintenance WHERE company_id=$1 AND supplier_id=$2 ORDER BY updated_at DESC LIMIT 50',[companyId,supplierId])).rows;if(res.locals.permissions.view_real_estate_financials&&(res.locals.permissions.view_real_estate_expenses||res.locals.permissions.manage_real_estate_expenses))data.expenses=(await getPool().query('SELECT id,title,status,amount,currency FROM real_estate_expenses WHERE company_id=$1 AND supplier_id=$2 ORDER BY updated_at DESC LIMIT 50',[companyId,supplierId])).rows;res.json({data});}catch(e){next(e);}});
router.patch('/vendors/:id',requireAnyPermission(['manage_real_estate_vendors']),async(req,res,next)=>{try{
 const c=res.locals.companyId,supplierId=z.coerce.number().int().positive().parse(req.params.id),old=await storage.getSupplier(supplierId);if(!old||old.companyId!==c)throw new ErpValidationError('Vendor not found','not_found');
 const v=z.object({name:z.string().trim().min(1).max(250),contactName:z.string().max(250).nullable(),email:z.string().email().nullable(),phone:z.string().max(100).nullable(),currency:z.string().regex(/^[A-Z]{3}$/),status:z.enum(['active','inactive'])}).strict().parse(req.body);if(!(await getPool().query('SELECT 1 FROM currencies WHERE company_id=$1 AND code=$2 AND is_active=true',[c,v.currency])).rowCount)throw new ErpValidationError('Select an active ERP currency');res.json({data:await storage.updateSupplier(supplierId,v)});
}catch(e){next(e);}});
export default router;
