import {loadAccessibleInvoice} from '../../services/erp/invoice-access';
import {roundErpDecimal} from '../../services/erp/decimal-math';
import {erpCurrencyDigits} from '../../../shared/erp-currency-precision';
import {calendarDateToDate} from '../../../shared/date-format';
import {Router} from 'express';
import {z} from 'zod';
import {getPool} from '../../db';
import {storage,ErpValidationError} from '../../storage';
import {requireAnyPermission} from '../../middleware';
import {realEstateExpenseSchema,realEstateExpenseTransitionSchema,assertExpenseTransition} from '../../../shared/real-estate-expenses';
import {calculateLineTotals} from '../../services/erp/tax-service';
import {validateAndNormalizeCustomFieldValues,validateCustomFieldRecordValues} from '../../utils/product-custom-field-values';
const router=Router(),read=['view_real_estate_expenses','manage_real_estate_expenses'];
function serializeExpense(row:any){return row;}
async function assertAssetAccess(client:any,c:number,assetId:number,permissions:Record<string,boolean>){
 const a=(await client.query('SELECT kind FROM real_estate_assets WHERE company_id=$1 AND id=$2',[c,assetId])).rows[0];
 if(!a||!permissions[`view_real_estate_${a.kind==='unit'?'units':'properties'}`]&&!permissions[`manage_real_estate_${a.kind==='unit'?'units':'properties'}`])throw new ErpValidationError('Property access required');
}
async function validateExpense(client:any,c:number,v:z.infer<typeof realEstateExpenseSchema>,permissions:Record<string,boolean>){
 await assertAssetAccess(client,c,v.assetId,permissions);
 if(!(await client.query("SELECT 1 FROM suppliers WHERE company_id=$1 AND id=$2 AND status='active'",[c,v.supplierId])).rowCount)throw new ErpValidationError('Select an active ERP supplier');
 const currency=(await client.query('SELECT decimal_places FROM currencies WHERE company_id=$1 AND code=$2 AND is_active=true',[c,v.currency])).rows[0];if(!currency)throw new ErpValidationError('Select an active ERP currency');
 if(!(await client.query("SELECT 1 FROM chart_of_accounts WHERE company_id=$1 AND id=$2 AND type='expense' AND is_active=true",[c,v.expenseAccountId])).rowCount)throw new ErpValidationError('Select an active ERP expense account');
 const typedLines=[];
 for(const l of v.lines){if(Number(roundErpDecimal(l.unitPrice,erpCurrencyDigits(currency.decimal_places)))!==Number(l.unitPrice))throw new ErpValidationError('Unit price exceeds ERP currency precision');const p=await storage.getProduct(l.productId);if(!p||p.companyId!==c||p.status!=='active')throw new ErpValidationError('Select an active Catalog item');if(l.taxGroupId&&p.isTaxable===false)throw new ErpValidationError('This Catalog item is not taxable');if(l.taxGroupId&&!(await client.query('SELECT 1 FROM tax_groups WHERE company_id=$1 AND id=$2 AND is_active=true',[c,l.taxGroupId])).rowCount)throw new ErpValidationError('Select an active tax group');typedLines.push({...l,taxGroupId:l.taxGroupId??undefined,productType:p.type});}
 return calculateLineTotals(c,typedLines,{decimalPlaces:erpCurrencyDigits(currency.decimal_places),asOf:new Date(`${v.expenseDate}T12:00:00Z`)});
}
async function activity(client:any,c:number,id:number,user:number,action:string,details:unknown){await client.query("INSERT INTO real_estate_activity(company_id,entity_type,entity_id,action,actor_user_id,details)VALUES($1,'real_estate_expense',$2,$3,$4,$5)",[c,id,action,user,JSON.stringify(details)]);}
router.use(['/expenses','/expense-context'],requireAnyPermission(read),requireAnyPermission(['view_real_estate_financials']));
router.get('/expense-context',async(_req,res,next)=>{try{const c=res.locals.companyId;res.json({items:(await getPool().query("SELECT id,name FROM products WHERE company_id=$1 AND status='active' ORDER BY name",[c])).rows,accounts:(await getPool().query("SELECT id,name FROM chart_of_accounts WHERE company_id=$1 AND type='expense' AND is_active=true ORDER BY account_code",[c])).rows,taxGroups:(await getPool().query('SELECT id,name FROM tax_groups WHERE company_id=$1 AND is_active=true ORDER BY name',[c])).rows,suppliers:(await storage.getSuppliers(c,{status:'active',limit:100})).data});}catch(e){next(e);}});
router.get('/expenses',async(req,res,next)=>{try{const f=z.object({search:z.string().max(250).default(''),limit:z.coerce.number().int().min(1).max(100).default(25),offset:z.coerce.number().int().min(0).default(0)}).strict().parse(req.query),c=res.locals.companyId;const kinds=['property','unit'].filter(k=>res.locals.permissions[`view_real_estate_${k==='unit'?'units':'properties'}`]||res.locals.permissions[`manage_real_estate_${k==='unit'?'units':'properties'}`]);const total=(await getPool().query('SELECT count(*)::int total FROM real_estate_expenses e JOIN real_estate_assets a ON a.id=e.asset_id AND a.company_id=e.company_id WHERE e.company_id=$1 AND e.title ILIKE $2 AND a.kind=ANY($3::text[])',[c,`%${f.search}%`,kinds])).rows[0].total;const data=(await getPool().query('SELECT e.*,e.expense_date::text,s.name supplier_name FROM real_estate_expenses e JOIN real_estate_assets a ON a.id=e.asset_id AND a.company_id=e.company_id LEFT JOIN suppliers s ON s.id=e.supplier_id AND s.company_id=e.company_id WHERE e.company_id=$1 AND e.title ILIKE $2 AND a.kind=ANY($3::text[]) ORDER BY e.updated_at DESC LIMIT $4 OFFSET $5',[c,`%${f.search}%`,kinds,f.limit,f.offset])).rows;res.json({data:data.map(serializeExpense),total});}catch(e){next(e);}});
router.post('/expenses',requireAnyPermission(['manage_real_estate_expenses']),async(req,res,next)=>{
 const client=await getPool().connect();try{const v=realEstateExpenseSchema.parse(req.body),c=res.locals.companyId;await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(78127,$1)',[c]);const totals=await validateExpense(client,c,v,res.locals.permissions);v.customFields=validateAndNormalizeCustomFieldValues(await storage.getProductCustomFieldDefinitions(c,'real_estate_expense'),v.customFields,{mode:'create'});
 const row=(await client.query("INSERT INTO real_estate_expenses(company_id,asset_id,supplier_id,title,expense_date,currency,amount,owner_chargeable,lines,custom_fields,created_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)RETURNING *,expense_date::text",[c,v.assetId,v.supplierId,v.title,v.expenseDate,v.currency,totals.totalAmount,v.ownerChargeable,JSON.stringify({items:v.lines,expenseAccountId:v.expenseAccountId}),JSON.stringify(v.customFields),req.user!.id])).rows[0];await activity(client,c,row.id,req.user!.id,'created',{});await client.query('COMMIT');res.status(201).json({data:serializeExpense(row)});}catch(e){await client.query('ROLLBACK');next(e);}finally{client.release();}
});
router.get('/expenses/:id',async(req,res,next)=>{try{
 const c=res.locals.companyId,id=z.coerce.number().int().positive().parse(req.params.id),row=(await getPool().query('SELECT e.*,e.expense_date::text,s.name supplier_name FROM real_estate_expenses e LEFT JOIN suppliers s ON s.id=e.supplier_id AND s.company_id=e.company_id WHERE e.company_id=$1 AND e.id=$2',[c,id])).rows[0];
 if(!row)throw new ErpValidationError('Expense not found','not_found');await assertAssetAccess(getPool(),c,row.asset_id,res.locals.permissions);
 res.json({data:serializeExpense(row),activity:(await getPool().query("SELECT action,details,created_at FROM real_estate_activity WHERE company_id=$1 AND entity_type='real_estate_expense' AND entity_id=$2 ORDER BY created_at DESC LIMIT 50",[c,id])).rows});
}catch(e){next(e);}});
router.patch('/expenses/:id',requireAnyPermission(['manage_real_estate_expenses']),async(req,res,next)=>{
 const client=await getPool().connect();try{
 const c=res.locals.companyId,id=z.coerce.number().int().positive().parse(req.params.id),{version,...fields}=req.body,v=realEstateExpenseSchema.parse(fields);z.number().int().positive().parse(version);
 await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(78127,$1)',[c]);const old=(await client.query('SELECT *,expense_date::text FROM real_estate_expenses WHERE company_id=$1 AND id=$2 FOR UPDATE',[c,id])).rows[0];
 if(!old)throw new ErpValidationError('Expense not found','not_found');await assertAssetAccess(client,c,old.asset_id,res.locals.permissions);
 if(old.version!==version)throw new ErpValidationError('Record changed. Reload before saving.','version_conflict');
 if(old.status!=='draft'||old.invoice_id||(await client.query("SELECT 1 FROM real_estate_invoice_sources WHERE company_id=$1 AND source_type='expense' AND source_id=$2",[c,id])).rowCount)throw new ErpValidationError('Only unposted drafts can be edited');
 const totals=await validateExpense(client,c,v,res.locals.permissions);v.customFields=validateCustomFieldRecordValues(await storage.getProductCustomFieldDefinitions(c,'real_estate_expense'),v.customFields,old.custom_fields??{});
 const row=(await client.query('UPDATE real_estate_expenses SET asset_id=$3,supplier_id=$4,title=$5,expense_date=$6,currency=$7,amount=$8,owner_chargeable=$9,lines=$10,custom_fields=$11,version=version+1,updated_at=now() WHERE company_id=$1 AND id=$2 RETURNING *,expense_date::text',[c,id,v.assetId,v.supplierId,v.title,v.expenseDate,v.currency,totals.totalAmount,v.ownerChargeable,JSON.stringify({items:v.lines,expenseAccountId:v.expenseAccountId}),JSON.stringify(v.customFields)])).rows[0];
 await activity(client,c,id,req.user!.id,'updated',{version:row.version});await client.query('COMMIT');res.json({data:serializeExpense(row)});
 }catch(e){await client.query('ROLLBACK');next(e);}finally{client.release();}
});
router.post('/expenses/:id/status',requireAnyPermission(['manage_real_estate_expenses']),async(req,res,next)=>{
 const client=await getPool().connect();try{
 const c=res.locals.companyId,id=z.coerce.number().int().positive().parse(req.params.id),v=realEstateExpenseTransitionSchema.parse(req.body);
 await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(78127,$1)',[c]);const old=(await client.query('SELECT *,expense_date::text FROM real_estate_expenses WHERE company_id=$1 AND id=$2 FOR UPDATE',[c,id])).rows[0];
 if(!old)throw new ErpValidationError('Expense not found','not_found');await assertAssetAccess(client,c,old.asset_id,res.locals.permissions);
 if(old.version!==v.version)throw new ErpValidationError('Record changed. Reload before saving.','version_conflict');
 const hasSource=!!(await client.query("SELECT 1 FROM real_estate_invoice_sources WHERE company_id=$1 AND source_type='expense' AND source_id=$2",[c,id])).rowCount;
 try{assertExpenseTransition(old.status,v.status,!!old.invoice_id||hasSource);}catch(e){throw new ErpValidationError((e as Error).message);}
 let basis=old.lines;
 if(v.status==='approved'){
 const input=realEstateExpenseSchema.parse({title:old.title,assetId:old.asset_id,supplierId:old.supplier_id,expenseDate:old.expense_date,currency:old.currency,ownerChargeable:old.owner_chargeable,expenseAccountId:old.lines.expenseAccountId,lines:old.lines.items,customFields:old.custom_fields});
 const totals=await validateExpense(client,c,input,res.locals.permissions);
 basis={...basis,approvedTotals:totals,approvedAt:new Date().toISOString(),approvedBy:req.user!.id};
 }else if(v.status==='draft'){basis={items:old.lines.items,expenseAccountId:old.lines.expenseAccountId};}
 const row=(await client.query('UPDATE real_estate_expenses SET status=$3,lines=$4,amount=COALESCE($5,amount),version=version+1,updated_at=now() WHERE company_id=$1 AND id=$2 RETURNING *,expense_date::text',[c,id,v.status,JSON.stringify(basis),v.status==='approved'?basis.approvedTotals.totalAmount:null])).rows[0];
 await activity(client,c,id,req.user!.id,'status_changed',{from:old.status,to:v.status});await client.query('COMMIT');res.json({data:serializeExpense(row)});
 }catch(e){await client.query('ROLLBACK');next(e);}finally{client.release();}
});
router.post('/expenses/:id/post',requireAnyPermission(['manage_real_estate_expenses']),requireAnyPermission(['manage_invoices']),async(req,res,next)=>{
 const client=await getPool().connect();try{const c=res.locals.companyId,recordId=z.coerce.number().int().positive().parse(req.params.id);await client.query('SELECT pg_advisory_lock(78127,$1)',[c]);const row=(await client.query('SELECT *,expense_date::text FROM real_estate_expenses WHERE company_id=$1 AND id=$2',[c,recordId])).rows[0];if(!row)throw new ErpValidationError('Expense not found','not_found');const asset=(await client.query('SELECT kind FROM real_estate_assets WHERE company_id=$1 AND id=$2',[c,row.asset_id])).rows[0];if(!asset||!res.locals.permissions[`view_real_estate_${asset.kind==='unit'?'units':'properties'}`]&&!res.locals.permissions[`manage_real_estate_${asset.kind==='unit'?'units':'properties'}`])throw new ErpValidationError('Property access required');if(row.status==='posted'){const posted=await loadAccessibleInvoice(req,row.invoice_id,'manage');if(!posted)throw new ErpValidationError('Expense invoice not found','not_found');res.json({data:posted});return;}if(row.status!=='approved')throw new ErpValidationError('Approve this expense before posting');if(z.number().int().positive().parse(req.body.version)!==row.version)throw new ErpValidationError('Record changed. Reload before posting.','version_conflict');const source=(await client.query("SELECT invoice_id FROM real_estate_invoice_sources WHERE company_id=$1 AND source_type='expense' AND source_id=$2",[c,recordId])).rows[0];let invoice=source?await loadAccessibleInvoice(req,source.invoice_id,'manage'):null;if(source&&!invoice)throw new ErpValidationError('Expense invoice not found','not_found');
 if(!invoice){const lines=row.lines.items,totals=row.lines.approvedTotals;if(!Array.isArray(lines)||!totals)throw new ErpValidationError('Return to draft and approve the expense to establish its accounting basis');const currentTotals=await validateExpense(client,c,realEstateExpenseSchema.parse({title:row.title,assetId:row.asset_id,supplierId:row.supplier_id,expenseDate:row.expense_date,currency:row.currency,ownerChargeable:row.owner_chargeable,expenseAccountId:row.lines.expenseAccountId,lines,customFields:row.custom_fields}),res.locals.permissions);if(['subtotal','taxAmount','totalAmount'].some(k=>Number((currentTotals as any)[k])!==Number(totals[k])))throw new ErpValidationError('Tax calculation changed. Return to draft and approve again before posting');invoice=await storage.createDraftInvoiceWithLineItemsAtomic({companyId:c,supplierId:row.supplier_id,type:'purchase_invoice',status:'draft',invoiceNumber:'',issueDate:calendarDateToDate(row.expense_date),dueDate:calendarDateToDate(row.expense_date),currency:row.currency,subtotal:totals.subtotal,taxAmount:totals.taxAmount,totalAmount:totals.totalAmount,amountPaid:'0',amountDue:totals.totalAmount,createdBy:req.user!.id},lines.map((l:any,i:number)=>({...l,taxRate:totals.itemTotals?.[i]?.effectiveRate??currentTotals.itemTotals[i].effectiveRate,discountType:'percentage',discountValue:'0',sortOrder:i})),{recalculateTotalsFromLines:true,postingContext:{netAccountId:row.lines.expenseAccountId,treatment:'expense',description:row.title},source:{sourceType:'expense',sourceId:recordId,periodKey:'expense',assetId:row.asset_id,accountingContext:{expenseDate:row.expense_date,ownerChargeable:row.owner_chargeable,approval:row.lines}}});}
 if(!invoice||invoice.companyId!==c||['cancelled','void'].includes(invoice.status))throw new ErpValidationError('Linked invoice must be resolved through ERP accounting');if(!await loadAccessibleInvoice(req,invoice.id,'manage'))throw new ErpValidationError('Expense invoice not found','not_found');if(invoice.status==='draft')invoice=await storage.sendInvoice(invoice.id,c,req.user!.id);await client.query('BEGIN');await client.query("UPDATE real_estate_expenses SET status='posted',invoice_id=$3,version=version+1,updated_at=now() WHERE company_id=$1 AND id=$2",[c,recordId,invoice!.id]);await activity(client,c,recordId,req.user!.id,'posted',{invoiceId:invoice!.id});await client.query('COMMIT');res.json({data:invoice});
 }catch(e){await client.query('ROLLBACK');next(e);}finally{await client.query('SELECT pg_advisory_unlock(78127,$1)',[res.locals.companyId]).catch(()=>{});client.release();}
});
export default router;
