import { useState } from 'react';
import { Link,useLocation } from 'wouter';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useTranslation } from '@/hooks/use-translation';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { ContactCustomFieldsBadges } from '@/components/contacts/ContactCustomFieldsBadges';
import type { CompanyContactCustomField } from '@/hooks/use-company-contact-custom-fields';
import { RealEstateShell } from './real-estate-shell';
import { useRealEstateAccess } from './use-real-estate-access';

export type LinkedContact={id:number;name:string;email:string|null;avatar_url:string|null;custom_fields:Record<string,unknown>};
export default function Contacts({role}:{role:'owner'|'tenant'}){
  const section=role==='owner'?'owners':'tenants',access=useRealEstateAccess(section),{t}=useTranslation(),{toast}=useToast(),cache=useQueryClient();
  const [,navigate]=useLocation(),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[open,setOpen]=useState(false),[contactSearch,setContactSearch]=useState(''),[contactPage,setContactPage]=useState(1);
  const definitions=useQuery<{data:CompanyContactCustomField[]}>({enabled:access.enabled,queryKey:['real-estate',access.companyId,'contact-definitions'],queryFn:async()=>(await apiRequest('GET','/api/erp/real-estate/contacts/field-definitions')).json()});
  const query=useQuery<{data:LinkedContact[];total:number}>({enabled:access.enabled,queryKey:['real-estate',access.companyId,section,search,offset],queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/contact-roles/${role}?${new URLSearchParams({search,offset:String(offset),limit:'25'})}`)).json()});
  const contacts=useQuery<{data:LinkedContact[];total:number}>({enabled:access.enabled&&access.canManage&&open,queryKey:['real-estate',access.companyId,'contact-search',contactSearch,contactPage],queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/contacts/search?${new URLSearchParams({search:contactSearch,page:String(contactPage)})}`)).json()});
  const link=useMutation({mutationFn:async(contactId:number)=>apiRequest('POST',`/api/erp/real-estate/contact-roles/${role}`,{contactId}),onSuccess:(_,contactId)=>{cache.invalidateQueries({queryKey:['real-estate',access.companyId,section]});setOpen(false);navigate(`/erp/real-estate/${section}/${contactId}`);},onError:(error:Error)=>toast({title:t('common.error','Error'),description:error.message,variant:'destructive'})});
  const title=t(`erp.realEstate.${section}.title`,role==='owner'?'Owners':'Tenants');
  return <RealEstateShell title={title} description={t(`erp.realEstate.${section}.description`,role==='owner'?'Manage ownership and portfolio relationships through CRM contacts.':'Manage residents, leases, and payment relationships through CRM contacts.')} icon={role==='owner'?'ri-user-star-line':'ri-group-line'} actions={access.canManage&&<Button onClick={()=>setOpen(true)}>{t(`erp.realEstate.${section}.add`,role==='owner'?'Add owner':'Add tenant')}</Button>}>
    <div className="re-panel mb-4 p-3"><Input className="max-w-md" aria-label={t('common.search','Search')} placeholder={t('erp.realEstate.contacts.search','Search linked contacts…')} value={search} onChange={event=>{setSearch(event.target.value);setOffset(0);}}/></div>
    {query.isError?<div className="re-panel p-8" role="alert">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="outline" onClick={()=>query.refetch()}>{t('common.retry','Retry')}</Button></div>:query.isLoading?<div role="status" className="re-panel h-64 animate-pulse"/>:!query.data?.data.length?<div className="re-panel py-16 px-8 text-center"><i className="ri-contacts-line text-4xl text-primary" aria-hidden="true"/><h2 className="mt-4 font-semibold">{t('erp.realEstate.contacts.empty','Connect your CRM relationships')}</h2><p className="mt-2 text-sm text-muted-foreground">{t('erp.realEstate.contacts.emptyDescription','Link an existing contact to open their Real Estate workspace.')}</p></div>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{query.data.data.map(contact=><Link key={contact.id} href={`/erp/real-estate/${section}/${contact.id}`} className="re-panel re-property-card p-5"><div className="flex items-center gap-3"><div className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-primary/10 text-primary">{contact.avatar_url?<img src={contact.avatar_url} alt="" className="h-full w-full object-cover"/>:<i className="ri-user-line text-2xl" aria-hidden="true"/>}</div><div className="min-w-0"><h2 className="truncate font-semibold">{contact.name}</h2><p className="mt-1 truncate text-xs text-muted-foreground">{contact.email??'—'}</p></div><i className="ri-arrow-right-up-line ml-auto text-muted-foreground" aria-hidden="true"/></div><div className="mt-4"><ContactCustomFieldsBadges customFields={contact.custom_fields} schema={definitions.data?.data??[]} maxVisible={3}/></div></Link>)}</div>}
    {!!query.data?.total&&<div className="mt-4 flex justify-between text-xs text-muted-foreground"><span>{offset+1}–{Math.min(offset+25,query.data.total)} / {query.data.total}</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={!offset} onClick={()=>setOffset(offset-25)}>{t('common.previous','Previous')}</Button><Button size="sm" variant="outline" disabled={offset+25>=query.data.total} onClick={()=>setOffset(offset+25)}>{t('common.next','Next')}</Button></div></div>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{t('erp.realEstate.contacts.link','Link CRM contact')}</DialogTitle><DialogDescription>{t('erp.realEstate.contacts.linkDescription','Choose an authorized contact. Their contact details and custom fields remain in CRM.')}</DialogDescription></DialogHeader><Input aria-label={t('erp.realEstate.contacts.searchCrm','Search CRM contacts')} value={contactSearch} onChange={event=>{setContactSearch(event.target.value);setContactPage(1);}}/>
      <div className="max-h-80 space-y-1 overflow-y-auto">{contacts.isError?<div role="alert">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="outline" onClick={()=>contacts.refetch()}>{t('common.retry','Retry')}</Button></div>:contacts.isLoading?<div role="status" className="h-32 animate-pulse bg-muted"/>:!contacts.data?.data.length?<p className="py-8 text-center text-sm text-muted-foreground">{t('erp.realEstate.contacts.none','No accessible contacts found.')}</p>:contacts.data.data.map(contact=><button key={contact.id} className="flex w-full items-center justify-between rounded-lg border border-border p-3 text-left hover:bg-muted disabled:opacity-50" disabled={link.isPending} onClick={()=>link.mutate(contact.id)}><div><strong className="text-sm">{contact.name}</strong><p className="text-xs text-muted-foreground">{contact.email??'—'}</p></div><i className="ri-add-line" aria-hidden="true"/></button>)}</div>
      {!!contacts.data?.total&&<div className="flex justify-end gap-2"><Button variant="outline" size="sm" disabled={contactPage===1} onClick={()=>setContactPage(contactPage-1)}>{t('common.previous','Previous')}</Button><Button variant="outline" size="sm" disabled={contactPage*25>=contacts.data.total} onClick={()=>setContactPage(contactPage+1)}>{t('common.next','Next')}</Button></div>}
    </DialogContent></Dialog>
  </RealEstateShell>;
}
