import {OwnerRentSummary} from './owner-rent-summary';
import {erpRetainedAmountDigits} from '../../../../../shared/erp-currency-precision';
import {formatDate} from '@/lib/utils';
import {usePermissions} from '@/hooks/usePermissions';
import {useErpCurrencies} from '@/hooks/use-erp-currencies';
import { Link,useLocation } from 'wouter';
import { useQuery } from '@tanstack/react-query';
import { useTranslation } from '@/hooks/use-translation';
import { apiRequest } from '@/lib/queryClient';
import { Button } from '@/components/ui/button';
import { Tabs,TabsContent,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { ContactCustomFieldsBadges } from '@/components/contacts/ContactCustomFieldsBadges';
import type { CompanyContactCustomField } from '@/hooks/use-company-contact-custom-fields';
import type { RealEstateAsset } from '@shared/real-estate-contracts';
import type {RealEstateSection} from '@shared/real-estate';
import type { LinkedContact } from './contacts';
import { RealEstateShell } from './real-estate-shell';
import { useRealEstateAccess } from './use-real-estate-access';

type Workspace={asOf:string;currentLeases:Array<{id:number;name:string;asset_id:number;asset_name:string;kind:string;start_date:string;end_date:string}>;activity:Array<{id:number;action:string;created_at:string;asset_id:number;asset_name:string;kind:string}>;settlementSummary:Array<{currency:string;count:number;collected:string;fees:string;expenses:string;payable:string;paid:string;outstanding:string}>;summary:{assets:number;leases:number;openMaintenance:number};receivables:Array<{id:number;invoice_number:string;currency:string;total_amount:string;amount_paid:string;amount_due:string;due_date:string;status:string;source_type:string}>;payments:Array<{id:number;amount:string;payment_date:string;payment_method:string;reference_number:string;invoice_number:string;currency:string}>;expenses:Array<{id:number;title:string;currency:string;amount:string;status:string}>;documents:Array<{id:number;name:string;category:string}>;contact:LinkedContact;assets:RealEstateAsset[];leases:Array<{id:number;name:string;status:string;start_date:string;end_date:string;asset_name:string;currency?:string;rent_amount?:string;deposit_amount?:string}>;maintenance:Array<{id:number;title:string;priority:string;status:string}>;appointments:Array<{id:number;title:string;scheduled_at:string;status:string}>;settlements:Array<{id:number;period_key:string;currency:string;payable:string;paid:string;status:string}>};
export default function ContactDetail({role,id}:{role:'owner'|'tenant';id:string}){
  const section=role==='owner'?'owners':'tenants',access=useRealEstateAccess(section),{t,currentLanguage}=useTranslation(),[,navigate]=useLocation();
  const {formatMoney,currencies}=useErpCurrencies({enabled:access.enabled&&access.financial});
 const query=useQuery<Workspace>({enabled:access.enabled,queryKey:['real-estate',access.companyId,section,id],queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/${section}/${id}`)).json()});
  const definitions=useQuery<{data:CompanyContactCustomField[]}>({enabled:access.enabled,queryKey:['real-estate',access.companyId,'contact-definitions'],queryFn:async()=>(await apiRequest('GET','/api/erp/real-estate/contacts/field-definitions')).json()});
  const permissions=usePermissions();
  const can=(section:RealEstateSection)=>permissions.hasAnyPermission([`view_real_estate_${section}`,`manage_real_estate_${section}`]);
  const portfolio=can('properties')||can('units');
  const tabs=[portfolio?'portfolio':null,portfolio?'activity':null,can('leases')?'leases':null,can('maintenance')?'maintenance':null,access.financial&&role==='tenant'&&can('rent_collection')?'payments':null,access.financial&&role==='owner'&&can('expenses')?'expenses':null,can('documents')?'documents':null,can('schedule')?'appointments':null,access.financial&&role==='owner'&&can('owner_settlements')?'settlements':null].filter(Boolean);
  const data=query.data;
  const money=(value:string,currency:string)=>formatMoney(Number(value),currency,currentLanguage?.code,erpRetainedAmountDigits(value,currencies.find(row=>row.code===currency)?.decimalPlaces));
  const empty=<p className="py-8 text-center text-sm text-muted-foreground">{t('erp.realEstate.contacts.noRecords','No related records to display.')}</p>;
  return <RealEstateShell title={data?.contact.name??t(`erp.realEstate.${section}.title`,role==='owner'?'Owners':'Tenants')} description={t(`erp.realEstate.${section}.workspace`,role==='owner'?'Owner portfolio workspace':'Tenant workspace')} icon={role==='owner'?'ri-user-star-line':'ri-group-line'} actions={<Button variant="outline" onClick={()=>navigate(`/erp/real-estate/${section}`)}>{t('erp.realEstate.contacts.back','Back to contacts')}</Button>}>
    {query.isError?<div role="alert" className="re-panel p-8">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="outline" onClick={()=>query.refetch()}>{t('common.retry','Retry')}</Button></div>:!data?<div role="status" className="re-panel h-80 animate-pulse"/>:<>
    <div className="mb-5 grid items-start gap-4 lg:grid-cols-[320px_minmax(0,1fr)]"><section className="re-panel p-5"><div className="flex items-center gap-3"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><i className="ri-user-line text-3xl" aria-hidden="true"/></div><div className="min-w-0"><h2 className="truncate font-semibold">{data.contact.name}</h2><p className="mt-1 break-all text-xs text-muted-foreground">{data.contact.email??'—'}</p></div></div><p className="mb-3 mt-5 text-xs text-muted-foreground">{t('erp.realEstate.contacts.crmFields','CRM contact information')}</p><ContactCustomFieldsBadges customFields={data.contact.custom_fields} schema={definitions.data?.data??[]} maxVisible={100}/><Button className="mt-5" variant="outline" onClick={()=>navigate('/contacts')}>{t('erp.realEstate.contacts.openCrm','Open CRM contacts')}</Button></section><div className="grid gap-3 sm:grid-cols-3">{[['properties',data.summary.assets,'ri-home-4-line'],['leases',data.summary.leases,'ri-file-list-3-line'],['maintenance',data.summary.openMaintenance,'ri-tools-line']].filter(([key])=>key==='properties'?portfolio:can(key as RealEstateSection)).map(([key,count,icon])=><section className="re-panel re-metric" key={key}><i className={`${icon} text-xl text-primary`} aria-hidden="true"/><strong>{count}</strong><p className="mt-1 text-xs text-muted-foreground">{t(`erp.realEstate.${key}.title`,key==='properties'?'Properties':key==='leases'?'Leases':'Maintenance')}</p></section>)}</div></div>
    {access.financial&&role==='owner'&&can('rent_collection')&&permissions.hasAnyPermission(['view_invoices','manage_invoices'])&&<OwnerRentSummary key={`${access.companyId}-${id}`} ownerId={id} companyId={access.companyId??undefined} asOf={data.asOf}/> }
    {access.financial&&role==='owner'&&can('owner_settlements')&&data.settlementSummary.length>0&&<section className="re-panel mb-5 p-5"><h2 className="font-semibold">{t('erp.realEstate.contacts.postedSettlements','Posted settlement totals')}</h2><p className="mt-1 text-xs text-muted-foreground">{t('erp.realEstate.contacts.postedSettlementsHelp','All posted owner settlements, grouped by ERP currency. Includes retained corrections and payout returns; excludes drafts and reversals. These totals cover settled funds, not all portfolio rent.')}</p><div className="mt-4 grid gap-4 xl:grid-cols-2">{data.settlementSummary.map(row=><div key={row.currency} className="rounded-xl border border-border p-4"><div className="mb-4 flex justify-between gap-3"><strong>{row.currency}</strong><span className="text-xs text-muted-foreground">{row.count} {t('erp.realEstate.owner_settlements.title','Owner Settlements')}</span></div><dl className="grid gap-x-4 gap-y-3 sm:grid-cols-2">{(['collected','fees','expenses','payable','paid','outstanding'] as const).map(key=><div key={key} className="min-w-0"><dt className="text-xs text-muted-foreground">{key==='outstanding'?t('erp.realEstate.reports.outstanding','Outstanding'):t(`erp.realEstate.settlements.${key}`,key)}</dt><dd data-testid={`contact-settlement-${row.currency}-${key}`} className="mt-1 break-words text-sm font-semibold">{money(row[key],row.currency)}</dd></div>)}</dl></div>)}</div></section>}
    {portfolio&&can('leases')&&<section className="re-panel mb-5 p-5" data-testid="contact-current-occupancy"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">{t('erp.realEstate.contacts.currentOccupancy','Current occupancy')}</h2><span className="text-xs text-muted-foreground">{formatDate(data.asOf,{locale:currentLanguage?.code,calendarDate:true})}</span></div><p className="mt-2 text-xs text-muted-foreground">{t('erp.realEstate.contacts.currentOccupancyHelp','Active leases covering today in the company calendar. Only properties and tenant contacts you can access are included.')}</p><div className="mt-4 space-y-3">{data.currentLeases.length?data.currentLeases.map(lease=><Link key={lease.id} href={`/erp/real-estate/leases/${lease.id}`} className="flex flex-wrap justify-between gap-3 rounded-lg border border-border p-4"><div className="min-w-0"><h3 className="break-words text-sm font-semibold">{lease.asset_name}</h3><p className="mt-1 break-words text-xs text-muted-foreground">{lease.name}</p></div><p className="text-xs text-muted-foreground">{formatDate(lease.start_date,{locale:currentLanguage?.code,calendarDate:true})} – {formatDate(lease.end_date,{locale:currentLanguage?.code,calendarDate:true})}</p></Link>):<p className="py-4 text-sm text-muted-foreground">{t('erp.realEstate.contacts.noCurrentLeases','No authorized active leases cover today.')}</p>}</div></section>}
    <Tabs key={tabs.join(',')} defaultValue={tabs[0]??'none'}><div className="overflow-x-auto"><TabsList className="mb-4">{portfolio&&<TabsTrigger value="portfolio">{t('erp.realEstate.contacts.portfolio','Portfolio')}</TabsTrigger>}{portfolio&&<TabsTrigger value="activity">{t('erp.realEstate.activity','Activity')}</TabsTrigger>}{can('leases')&&<TabsTrigger value="leases">{t('erp.realEstate.leases.title','Leases')}</TabsTrigger>}{can('maintenance')&&<TabsTrigger value="maintenance">{t('erp.realEstate.maintenance.title','Maintenance')}</TabsTrigger>}{access.financial&&role==='tenant'&&can('rent_collection')&&<TabsTrigger value="payments">{t('erp.realEstate.contacts.paymentHistory','Receivables and payment history')}</TabsTrigger>}{access.financial&&role==='owner'&&can('expenses')&&<TabsTrigger value="expenses">{t('erp.realEstate.expenses.title','Expenses')}</TabsTrigger>}{can('documents')&&<TabsTrigger value="documents">{t('erp.realEstate.documents.title','Documents')}</TabsTrigger>}{can('schedule')&&<TabsTrigger value="appointments">{t('erp.realEstate.contacts.appointments','Appointments')}</TabsTrigger>}{access.financial&&role==='owner'&&can('owner_settlements')&&<TabsTrigger value="settlements">{t('erp.realEstate.owner_settlements.title','Owner Settlements')}</TabsTrigger>}</TabsList></div>
      <TabsContent value="portfolio">{!data.assets.length?<section className="re-panel">{empty}</section>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data.assets.map(asset=><Link key={asset.id} href={`/erp/real-estate/${asset.kind==='unit'?'units':'properties'}/${asset.id}`} className="re-panel re-property-card p-5"><span className={`re-status re-status-${asset.status}`}>{t(`erp.realEstate.status.${asset.status}`,asset.status)}</span><h3 className="mt-3 font-semibold">{asset.name}</h3><p className="mt-1 text-xs text-muted-foreground">{asset.code} · {asset.location??'—'}</p>{access.financial&&asset.currency&&<strong className="mt-4 block text-sm">{money(asset.rental_price??'0',asset.currency)}</strong>}</Link>)}</div>}</TabsContent>
      {portfolio&&<TabsContent value="activity"><section className="re-panel p-5"><p className="mb-4 text-xs text-muted-foreground">{t('erp.realEstate.contacts.assetActivityHelp','Recent property and unit activity in this portfolio.')}</p>{data.activity.length?data.activity.map(event=><Link key={event.id} href={`/erp/real-estate/${event.kind==='unit'?'units':'properties'}/${event.asset_id}`} className="flex items-start gap-3 border-b border-border py-4 last:border-0"><i className="ri-history-line mt-1 text-primary" aria-hidden="true"/><div className="min-w-0"><h3 className="break-words text-sm font-semibold">{event.asset_name}</h3><p className="mt-1 text-sm">{t(`erp.realEstate.actions.${event.action}`,event.action)}</p><time className="mt-1 block text-xs text-muted-foreground">{new Intl.DateTimeFormat(currentLanguage?.code,{dateStyle:'medium',timeStyle:'short'}).format(new Date(event.created_at))}</time></div></Link>):empty}</section></TabsContent>}
      <TabsContent value="leases"><section className="re-panel p-5"><p className="mb-2 text-xs text-muted-foreground">{t('erp.realEstate.contacts.recentLeases','Most recent leases are shown first.')} {data.leases.length} / {data.summary.leases}</p>{data.leases.length?data.leases.map(lease=><Link key={lease.id} href={`/erp/real-estate/leases/${lease.id}`} className="flex flex-wrap justify-between gap-3 border-b border-border py-4 last:border-0"><div><h3 className="font-medium">{lease.name}</h3><p className="mt-1 text-xs text-muted-foreground">{lease.asset_name} · {formatDate(lease.start_date,{locale:currentLanguage?.code,calendarDate:true})} – {formatDate(lease.end_date,{locale:currentLanguage?.code,calendarDate:true})}</p></div><div className="text-right"><span className="re-status">{t(`erp.realEstate.leasesStatus.${lease.status}`,lease.status)}</span>{access.financial&&lease.currency&&<div className="mt-2 space-y-1 text-sm"><p>{t('erp.realEstate.leases.rent','Rent')}: <span data-testid={`contact-lease-rent-${lease.id}`}>{money(lease.rent_amount??'0',lease.currency)}</span></p><p className="text-xs text-muted-foreground">{t('erp.realEstate.leases.deposit','Deposit')}: <span data-testid={`contact-lease-deposit-${lease.id}`}>{money(lease.deposit_amount??'0',lease.currency)}</span></p></div>}</div></Link>):empty}</section></TabsContent>
      <TabsContent value="maintenance"><section className="re-panel p-5">{data.maintenance.length?data.maintenance.map(record=><Link key={record.id} href={`/erp/real-estate/maintenance/${record.id}`} className="flex justify-between gap-3 border-b border-border py-4 last:border-0"><h3 className="text-sm font-medium">{record.title}</h3><span className="re-status">{t(`erp.realEstate.maintenanceStatus.${record.status}`,record.status)}</span></Link>):empty}</section></TabsContent>
      {access.financial&&role==='tenant'&&can('rent_collection')&&<TabsContent value="payments"><div className="grid items-start gap-5 lg:grid-cols-2"><section className="re-panel p-5"><h2 className="mb-4 font-semibold">{t('erp.realEstate.reports.receivables','Receivables')}</h2>{data.receivables?.length?data.receivables.map(row=><Link key={row.id} href="/erp/real-estate/rent-collection" className="mb-3 block rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2"><strong className="text-sm">{row.invoice_number}</strong><span className="re-status">{t(`erp.realEstate.invoiceStatus.${row.status}`,row.status)}</span></div><p className="mt-2 text-xs text-muted-foreground">{t(`erp.realEstate.reports.source.${row.source_type}`,row.source_type)} · {formatDate(row.due_date,{locale:currentLanguage?.code,calendarDate:true})}</p><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between gap-3"><dt>{t('erp.realEstate.reports.paid','Paid')}</dt><dd>{money(row.amount_paid,row.currency)}</dd></div><div className="flex justify-between gap-3"><dt>{t('erp.realEstate.reports.outstanding','Outstanding')}</dt><dd>{money(row.amount_due,row.currency)}</dd></div></dl></Link>):empty}</section><section className="re-panel p-5"><h2 className="mb-4 font-semibold">{t('erp.realEstate.contacts.receipts','Payment receipts')}</h2>{data.payments?.length?data.payments.map(row=><article key={row.id} className="border-b py-4 last:border-0"><div className="flex flex-wrap justify-between gap-3 text-sm"><strong>{row.invoice_number}</strong><strong>{money(row.amount,row.currency)}</strong></div><time className="mt-2 block text-xs text-muted-foreground">{new Intl.DateTimeFormat(currentLanguage?.code,{dateStyle:'medium'}).format(new Date(row.payment_date))}</time>{row.reference_number&&<p className="mt-1 break-words text-xs text-muted-foreground">{row.reference_number}</p>}</article>):empty}</section></div></TabsContent>}
      {access.financial&&role==='owner'&&<TabsContent value="expenses"><section className="re-panel p-5">{data.expenses?.length?data.expenses.map(row=><Link key={row.id} href={`/erp/real-estate/expenses/${row.id}`} className="flex flex-wrap justify-between gap-3 border-b py-4 text-sm"><strong>{row.title}</strong><span>{money(row.amount,row.currency)}</span></Link>):empty}</section></TabsContent>}
      <TabsContent value="documents"><section className="re-panel p-5">{data.documents?.length?data.documents.map(row=><a key={row.id} href={`/api/erp/real-estate/documents/${row.id}/download`} target="_blank" rel="noreferrer" className="flex flex-wrap justify-between gap-3 border-b py-4 text-sm"><strong>{row.name}</strong><i className="ri-download-line text-primary" aria-hidden="true"/></a>):empty}</section></TabsContent>
      <TabsContent value="appointments"><section className="re-panel p-5">{data.appointments.length?data.appointments.map(record=><div key={record.id} className="flex justify-between gap-3 border-b border-border py-4 last:border-0"><div><h3 className="text-sm font-medium">{record.title}</h3><time className="text-xs text-muted-foreground">{new Intl.DateTimeFormat(currentLanguage?.code,{dateStyle:'medium',timeStyle:'short'}).format(new Date(record.scheduled_at))}</time></div><span className="re-status">{t(`erp.realEstate.schedule.status.${record.status}`,record.status)}</span></div>):empty}</section></TabsContent>
      {access.financial&&<TabsContent value="settlements"><section className="re-panel p-5">{data.settlements.length?data.settlements.map(record=><Link key={record.id} href={`/erp/real-estate/owner-settlements/${record.id}`} className="flex justify-between gap-3 border-b border-border py-4 last:border-0"><h3 className="text-sm font-medium">{record.period_key}</h3><div className="text-right"><strong className="text-sm">{money(record.payable,record.currency)}</strong><p className="text-xs text-muted-foreground">{t(`erp.realEstate.settlements.status.${record.status}`,record.status)}</p></div></Link>):empty}</section></TabsContent>}
    </Tabs></>}
  </RealEstateShell>;
}
