import {useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {useTranslation} from '@/hooks/use-translation';
import {usePermissions} from '@/hooks/usePermissions';
import {useToast} from '@/hooks/use-toast';
import {apiRequest} from '@/lib/queryClient';
import {formatCurrency} from '@/lib/utils';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {useRealEstateAccess} from './use-real-estate-access';
type Source={transaction_decimal_places?:number;base_decimal_places?:number;source_amount?:string;allocation_start?:string;adjusted_cost?:Array<{currency:string;amount:string;decimal_places?:number}>;invoice_id?:number|null;id:number;entry_number:string;date:string;account_name:string;description:string|null;amount:string;base_amount:string;currency:string;base_currency:string;reason:string;active:boolean;removed_at:string|null;removal_reason:string|null;status:string;reversal_date:string|null};
type Data={releases?:Array<{sale_id:number;currency:string;amount:string;decimal_places?:number}>;restricted:boolean;asOf:string;sources:Source[];candidates:Source[];currencies:Array<{code:string;decimalPlaces:number}>;totals:Array<{currency:string;amount:string;decimal_places?:number}>};
export function CostSources({assetId,kind}:{assetId:number;kind:'property'|'unit'}){
 const section=kind==='unit'?'units':'properties',access=useRealEstateAccess(section),{hasPermission}=usePermissions(),{t,currentLanguage}=useTranslation(),{toast}=useToast(),cache=useQueryClient();
 const [asOf,setAsOf]=useState('');
 const [open,setOpen]=useState(false),[remove,setRemove]=useState<number|null>(null),[search,setSearch]=useState(''),[line,setLine]=useState('none'),[reason,setReason]=useState(''),[allocationAmount,setAllocationAmount]=useState('');
 const enabled=access.enabled&&access.financial&&(hasPermission('view_accounting')||hasPermission('manage_accounting')),manage=access.canManage&&hasPermission('manage_accounting');
 const url=`/api/erp/real-estate/${section}/${assetId}/cost-sources`,key=['real-estate',access.companyId,'cost-sources',assetId];
 const query=useQuery<Data>({enabled,queryKey:[...key,search,asOf],queryFn:async()=>(await apiRequest('GET',`${url}?${new URLSearchParams({search,...(asOf?{asOf}:{})})}`)).json()});
 const label=(key:string,fallback:string)=>t(`erp.realEstate.costSources.${key}`,fallback);
 const save=useMutation({mutationFn:async()=>apiRequest('POST',remove?`${url}/${remove}/remove`:url,remove?{reason}:{lineId:Number(line),reason,...(allocationAmount?{allocationAmount}:{})}),onSuccess:()=>{cache.invalidateQueries({queryKey:['real-estate',access.companyId]});setOpen(false);toast({title:t('erp.common.saved','Saved')});},onError:(e:Error)=>toast({title:t('common.error','Error'),description:e.message,variant:'destructive'})});
 const money=(amount:string,currency:string,digits?:number)=>amount==null?label('incompleteBasis','Incomplete ERP base evidence'):formatCurrency(Number(amount),currency,{locale:currentLanguage?.code,decimalPlaces:digits??query.data?.currencies.find(c=>c.code===currency)?.decimalPlaces});
 if(!enabled)return null;
 return <section className="re-panel mb-5 p-5" aria-label={label('title','Acquisition cost basis')}>
  <div className="mb-3 flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">{label('title','Acquisition cost basis')}</h2>{manage&&<Button size="sm" variant="outline" onClick={()=>{setRemove(null);setReason('');setLine('none');setAllocationAmount('');setSearch('');setOpen(true);}}>{label('link','Link ERP cost source')}</Button>}</div>
  <p className="mb-4 max-w-3xl text-xs leading-relaxed text-muted-foreground">{label('help','Link posted ERP acquisition asset lines. Allocate all or part of a shared line to this asset. Amounts and currency bases stay in ERP; reversed journals do not contribute. Listing prices are not acquisition costs.')}</p>
  <div className="mb-4 flex flex-wrap items-end gap-3"><div className="space-y-2"><Label htmlFor="cost-basis-date">{label('asOf','Accounting date')}</Label><Input id="cost-basis-date" type="date" value={asOf||query.data?.asOf||''} onChange={e=>setAsOf(e.target.value)}/></div><p className="max-w-xl text-xs text-muted-foreground">{label('dateHelp','Cost follows ERP accounting dates and dated reversals, using current corrected asset attributions. Removing an attribution restates earlier dates; it does not reverse a journal.')}</p></div>
  {query.isError?<div role="alert">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="ghost" onClick={()=>query.refetch()}>{t('common.retry','Retry')}</Button></div>:!query.data?<div role="status" className="h-24 animate-pulse bg-muted"/>:<>
   {query.data.restricted&&<p className="mb-4 text-sm text-muted-foreground">{label('restricted','Some accounting evidence is restricted by ERP invoice, sale or CRM permissions. Visible totals are incomplete.')}</p>}<div className="mb-4 flex flex-wrap gap-3">{query.data.totals.map(row=><div key={row.currency} className="rounded-lg border px-4 py-3"><p className="text-xs text-muted-foreground">{label('retained','Retained ERP base cost')}</p><strong className="mt-1 block text-lg">{money(row.amount,row.currency,row.decimal_places)}</strong></div>)}</div>{query.data.releases?.map(row=><p key={row.sale_id+row.currency} className="mb-4 text-sm text-muted-foreground">{label('released','Cost released at handover')}: <strong>{money(row.amount,row.currency,row.decimal_places)}</strong></p>)}
   {!query.data.sources.length?<p className="text-sm text-muted-foreground">{label('empty','No acquisition cost sources linked. Cost-based yield is unavailable until a reconciled basis is linked.')}</p>:<div className="space-y-3">{query.data.sources.map(s=><article key={s.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words text-sm font-medium">{s.entry_number} · {s.account_name}</h3><p className="mt-1 text-xs text-muted-foreground">{new Intl.DateTimeFormat(currentLanguage?.code,{dateStyle:'medium',timeZone:'UTC'}).format(new Date(s.date+'T12:00:00Z'))} · {label(s.active?'active':'inactive',s.active?'Active basis':'Excluded from basis')}</p></div><div className="text-right text-sm"><strong>{money(s.amount,s.currency,s.transaction_decimal_places)}</strong><p className="mt-1 text-xs text-muted-foreground">{money(s.base_amount,s.base_currency,s.base_decimal_places)} {label('base','ERP base')}</p></div></div>{s.invoice_id&&<a className="mt-3 block text-xs text-primary hover:underline" href={`/erp/invoices?detail=${s.invoice_id}`}>{label('invoice','Open ERP acquisition invoice')}</a>}{s.adjusted_cost?.map(row=><p key={row.currency} className="mt-2 text-xs">{label('adjusted','Adjusted cost at accounting date')}: <strong>{money(row.amount,row.currency,row.decimal_places)}</strong></p>)}{s.source_amount&&Number(s.source_amount)!==Number(s.amount)&&<p className="mt-2 text-xs text-muted-foreground">{label('sharedSource','Allocated portion of shared ERP source')}: {money(s.amount,s.currency,s.transaction_decimal_places)} / {money(s.source_amount,s.currency,s.transaction_decimal_places)}</p>}<p className="mt-3 break-words text-xs text-muted-foreground">{s.reason}</p>{s.reversal_date&&<p className="mt-2 text-xs text-muted-foreground">{label('reversedOn','ERP reversal date')}: {new Intl.DateTimeFormat(currentLanguage?.code,{dateStyle:'medium',timeZone:'UTC'}).format(new Date(s.reversal_date+'T12:00:00Z'))}</p>}{s.removal_reason&&<p className="mt-2 break-words text-xs">{label('removalReason','Removal reason')}: {s.removal_reason}</p>}{manage&&!s.removed_at&&<Button className="mt-3" size="sm" variant="ghost" onClick={()=>{setRemove(s.id);setReason('');setOpen(true);}}>{label('remove','Remove attribution')}</Button>}</article>)}</div>}
  </>}
  <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{remove?label('remove','Remove attribution'):label('link','Link ERP cost source')}</DialogTitle><DialogDescription>{label('dialogHelp','This attributes existing accounting evidence. It does not create, alter or reverse an ERP posting. A reason is retained in history.')}</DialogDescription></DialogHeader><div className="space-y-4">{!remove&&<><Input aria-label={label('search','Search ERP cost sources')} placeholder={label('search','Search ERP cost sources')} value={search} onChange={e=>setSearch(e.target.value)}/><div className="space-y-2"><Label>{label('source','Posted ERP asset line')}</Label><Select value={line} onValueChange={value=>{setLine(value);setAllocationAmount('');}}><SelectTrigger aria-label={label('source','Posted ERP asset line')}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none" disabled>{label('choose','Select acquisition source')}</SelectItem>{query.data?.candidates.map(s=><SelectItem key={s.id} value={String(s.id)}>{s.entry_number} · {s.account_name} · {money(s.amount,s.currency,s.transaction_decimal_places)}</SelectItem>)}</SelectContent></Select></div>{line!=='none'&&<div className="space-y-2"><Label htmlFor="cost-allocation-amount">{label('allocationAmount','Acquisition amount to allocate')}</Label><Input id="cost-allocation-amount" type="number" min="0" step="any" value={allocationAmount} placeholder={query.data?.candidates.find(s=>String(s.id)===line)?.amount} onChange={e=>setAllocationAmount(e.target.value)}/><p className="text-xs text-muted-foreground">{label('allocationHelp','Leave blank to allocate the remaining available amount. Shared ERP source portions retain their base cents; tax is excluded from acquisition cost.')}</p></div>}{query.data?.candidates.length===0&&<p className="text-xs text-muted-foreground">{label('noCandidates','No matching posted acquisition lines with available amounts.')}</p>}</>}<div className="space-y-2"><Label htmlFor="cost-source-reason">{label('reason','Attribution reason')}</Label><Input id="cost-source-reason" value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>{t('common.cancel','Cancel')}</Button><Button disabled={save.isPending||reason.trim().length<3||(!remove&&line==='none')} onClick={()=>save.mutate()}>{t('erp.common.save','Save')}</Button></DialogFooter></DialogContent></Dialog>
 </section>;
}
