import {useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {useTranslation} from '@/hooks/use-translation';
import {useToast} from '@/hooks/use-toast';
import {apiRequest} from '@/lib/queryClient';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {RealEstateShell} from './real-estate-shell';
import {useRealEstateAccess} from './use-real-estate-access';
type Document={id:number;entity_type:string;entity_id:number;name:string;category:string;file_size:number;mime_type:string;created_at:string};
export default function Documents(){
 const access=useRealEstateAccess('documents'),{t,currentLanguage}=useTranslation(),{toast}=useToast(),cache=useQueryClient(),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[open,setOpen]=useState(false),[record,setRecord]=useState('none'),[name,setName]=useState(''),[category,setCategory]=useState('general'),[file,setFile]=useState<File|null>(null),[editing,setEditing]=useState<Document|null>(null);
 const query=useQuery<{data:Document[];total:number}>({enabled:access.enabled,queryKey:['real-estate',access.companyId,'documents',search,offset],queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/documents?${new URLSearchParams({search,offset:String(offset)})}`)).json()});
 const context=useQuery<{data:Array<{entityType:string;entityId:number;name:string}>}>({enabled:open&&access.enabled,queryKey:['real-estate',access.companyId,'document-context'],queryFn:async()=>(await apiRequest('GET','/api/erp/real-estate/document-context')).json()});
 const edit=useMutation({mutationFn:async()=>apiRequest('PATCH',`/api/erp/real-estate/documents/${editing!.id}`,{name,category,expectedName:editing!.name,expectedCategory:editing!.category}),onSuccess:()=>{cache.invalidateQueries({queryKey:['real-estate',access.companyId,'documents']});setOpen(false);setEditing(null);toast({title:t('erp.common.saved','Saved')});},onError:(e:Error)=>toast({title:t('common.error','Error'),description:e.message,variant:'destructive'})});
 const upload=useMutation({mutationFn:async()=>{const [type,id]=record.split(':');const body=new FormData();body.append('file',file!);body.append('name',name||file!.name);body.append('category',category);const response=await fetch(`/api/erp/real-estate/documents/${type}/${id}/upload`,{method:'POST',credentials:'include',body});const result=await response.json();if(!response.ok)throw new Error(result.error??result.message??'Upload failed');return result;},onSuccess:()=>{cache.invalidateQueries({queryKey:['real-estate',access.companyId,'documents']});setOpen(false);setFile(null);setName('');toast({title:t('erp.common.saved','Saved')});},onError:(e:Error)=>toast({title:t('common.error','Error'),description:e.message,variant:'destructive'})});
 return <RealEstateShell title={t('erp.realEstate.documents.title','Documents')} description={t('erp.realEstate.documents.description','Keep files linked to authorized Real Estate records.')} icon="ri-file-text-line" actions={access.canManage&&<Button onClick={()=>{setEditing(null);setName('');setCategory('general');setRecord('none');setOpen(true);}}>{t('erp.realEstate.documents.upload','Upload document')}</Button>}>
 <div className="re-panel mb-4 p-3"><Input aria-label={t('common.search','Search')} placeholder={t('erp.realEstate.documents.search','Search documents…')} value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}}/></div>
 {query.isError?<div role="alert" className="re-panel p-8">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="outline" onClick={()=>query.refetch()}>{t('common.retry','Retry')}</Button></div>:query.isLoading?<div role="status" className="re-panel h-64 animate-pulse"/>:!query.data?.data.length?<div className="re-panel py-16 text-center"><i className="ri-file-text-line text-4xl text-primary" aria-hidden="true"/><h2 className="mt-4 font-semibold">{t('erp.realEstate.documents.empty','No documents match this view')}</h2></div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{query.data.data.map(doc=><article key={doc.id} className="re-panel p-5"><div className="flex items-start gap-3"><i className="ri-file-text-line text-3xl text-primary" aria-hidden="true"/><div className="min-w-0"><h2 className="break-words text-sm font-semibold">{doc.name}</h2><p className="mt-1 text-xs text-muted-foreground">{t(`erp.realEstate.documentEntity.${doc.entity_type}`,doc.entity_type)} #{doc.entity_id}</p></div></div><p className="mt-4 text-xs text-muted-foreground">{doc.category} · {new Intl.NumberFormat(currentLanguage?.code,{maximumFractionDigits:1}).format(Number(doc.file_size)/1024)} KB</p><time className="mt-2 block text-xs text-muted-foreground">{new Intl.DateTimeFormat(currentLanguage?.code,{dateStyle:'medium'}).format(new Date(doc.created_at))}</time><Button asChild size="sm" variant="outline" className="mt-4"><a href={`/api/erp/real-estate/documents/${doc.id}/download`} target="_blank" rel="noreferrer">{t('erp.realEstate.documents.open','Open document')}</a></Button>{access.canManage&&<Button size="sm" variant="ghost" className="ml-2 mt-4" onClick={()=>{setEditing(doc);setName(doc.name);setCategory(doc.category);setOpen(true);}}>{t('common.edit','Edit')}</Button>}</article>)}</div>}
 {!!query.data?.total&&<div className="mt-4 flex justify-end gap-2"><Button variant="outline" size="sm" disabled={!offset} onClick={()=>setOffset(offset-25)}>{t('erp.realEstate.pagination.previous','Previous')}</Button><Button variant="outline" size="sm" disabled={offset+25>=query.data.total} onClick={()=>setOffset(offset+25)}>{t('erp.realEstate.pagination.next','Next')}</Button></div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing?t('common.edit','Edit'):t('erp.realEstate.documents.upload','Upload document')}</DialogTitle><DialogDescription>{t('erp.realEstate.documents.help','Choose a record you can manage. Files use the shared ERP media system.')}</DialogDescription></DialogHeader><div className="space-y-4">{!editing&&<Select value={record} onValueChange={setRecord}><SelectTrigger aria-label={t('erp.realEstate.documents.record','Linked record')}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">{t('erp.common.none','None')}</SelectItem>{context.data?.data.map(r=><SelectItem key={`${r.entityType}:${r.entityId}`} value={`${r.entityType}:${r.entityId}`}>{t(`erp.realEstate.documentEntity.${r.entityType}`,r.entityType)} · {r.name}</SelectItem>)}</SelectContent></Select>}<div className="space-y-2"><Label htmlFor="document-name">{t('erp.realEstate.documents.name','Document name')}</Label><Input id="document-name" value={name} onChange={e=>setName(e.target.value)}/></div><div className="space-y-2"><Label htmlFor="document-category">{t('erp.realEstate.documents.category','Category')}</Label><Input id="document-category" value={category} onChange={e=>setCategory(e.target.value)}/></div>{!editing&&<div className="space-y-2"><Label htmlFor="document-file">{t('erp.realEstate.documents.file','File')}</Label><Input id="document-file" type="file" accept=".pdf,.doc,.docx,.txt,.png,.jpg,.jpeg,.gif,.webp" onChange={e=>setFile(e.target.files?.[0]??null)}/></div>}</div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>{t('common.cancel','Cancel')}</Button><Button disabled={upload.isPending||edit.isPending||(!editing&&(!file||record==='none'))||!category.trim()||(!!editing&&!name.trim())} onClick={()=>editing?edit.mutate():upload.mutate()}>{t('erp.common.save','Save')}</Button></DialogFooter></DialogContent></Dialog>
 </RealEstateShell>;
}
