import {getZonedDateTimeParts} from '@shared/utils/agent-schedule';
import {zonedDateTimeToUtc} from '@/utils/timezones';
import { useEffect,useState } from 'react';
import { useLocation } from 'wouter';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useTranslation } from '@/hooks/use-translation';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { ErpCustomFieldsEditor,type ErpFieldDefinition } from '@/components/erp/ErpCustomFieldsEditor';
import type { RealEstateAsset } from '@shared/real-estate-contracts';
import { RealEstateShell } from './real-estate-shell';
import { useRealEstateAccess } from './use-real-estate-access';
import { operationIcons,type OperationRecord,type OperationSection } from './operations';

export default function OperationEditor({section,id}:{section:OperationSection;id?:string}){
 const access=useRealEstateAccess(section),propertyAccess=useRealEstateAccess('properties'),unitAccess=useRealEstateAccess('units'),vendorAccess=useRealEstateAccess('vendors'),{t}=useTranslation(),{toast}=useToast(),cache=useQueryClient(),[,navigate]=useLocation();
 const [form,setForm]=useState<Record<string,any>>({supplierId:null,scheduledAt:'',assetId:null,name:'',title:'',description:'',priority:'normal',assignedUserId:null,inspectorUserId:null,tenantContactId:null,guarantorContactId:null,startDate:'',endDate:'',currency:'',rentAmount:'',depositAmount:'0',dueDay:1,customFields:{},checklist:[],findings:[],terms:{}}),[search,setSearch]=useState(''),[contactSearch,setContactSearch]=useState(''),[checklistLabel,setChecklistLabel]=useState('');
 const entity=section==='leases'?'real_estate_lease':section==='maintenance'?'real_estate_maintenance':'real_estate_inspection';
 const definitions=useQuery<ErpFieldDefinition[]>({enabled:access.enabled&&access.canManage,queryKey:['erp-custom-fields',access.companyId,entity],queryFn:async()=>(await (await apiRequest('GET',`/api/erp/custom-fields/${entity}`)).json()).data});
 const record=useQuery<{data:OperationRecord}>({enabled:access.enabled&&access.canManage&&!!id,queryKey:['real-estate',access.companyId,section,id],queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/${section}/${id}`)).json()});
 const context=useQuery<{agents:Array<{id:number;name:string}>;currencies:Array<{code:string;name:string}>;baseCurrency:string|null;timezone:string|null}>({enabled:access.enabled&&access.canManage,queryKey:['real-estate',access.companyId,'context'],queryFn:async()=>(await apiRequest('GET','/api/erp/real-estate/context')).json()});
 const assets=useQuery<RealEstateAsset[]>({enabled:access.enabled&&access.canManage&&(propertyAccess.enabled||unitAccess.enabled),queryKey:['real-estate',access.companyId,'operation-assets',search,propertyAccess.enabled,unitAccess.enabled],queryFn:async()=>{const values=await Promise.all(['properties','units'].filter(section=>section==='properties'?propertyAccess.enabled:unitAccess.enabled).map(async section=>(await (await apiRequest('GET',`/api/erp/real-estate/${section}?${new URLSearchParams({search,limit:'50'})}`)).json()).data));return values.flat();}});
 const contacts=useQuery<{data:Array<{id:number;name:string}>}>({enabled:section==='leases'&&access.enabled&&access.canManage,queryKey:['real-estate',access.companyId,'lease-contacts',contactSearch],queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/contacts/search?search=${encodeURIComponent(contactSearch)}`)).json()});
 const billing=useQuery<{items:Array<{id:number;name:string}>;accounts:Array<{id:number;name:string;account_code:string;type:string}>;taxGroups:Array<{id:number;name:string}>}>({enabled:section==='leases'&&access.enabled&&access.canManage&&access.financial,queryKey:['real-estate',access.companyId,'billing-context'],queryFn:async()=>(await apiRequest('GET','/api/erp/real-estate/billing-context')).json()});
 const vendors=useQuery<{data:Array<{id:number;name:string}>}>({enabled:section==='maintenance'&&access.enabled&&vendorAccess.enabled,queryKey:['real-estate',access.companyId,'operation-vendors'],queryFn:async()=>(await apiRequest('GET','/api/erp/real-estate/vendors?status=active&limit=100')).json()});
 useEffect(()=>{if(!id&&context.data?.baseCurrency)setForm(prior=>({...prior,currency:prior.currency||context.data!.baseCurrency}));},[context.data,id]);
 useEffect(()=>{if(record.data){const row=record.data.data;setForm(prior=>({...prior,supplierId:row.supplier_id??null,scheduledAt:row.scheduled_at?new Date(row.scheduled_at).toISOString():null,assetId:row.asset_id,name:row.name??'',title:row.title??'',description:row.description??'',priority:row.priority??'normal',assignedUserId:row.assigned_user_id??null,inspectorUserId:row.inspector_user_id??null,tenantContactId:row.tenant_contact_id??null,guarantorContactId:row.guarantor_contact_id??null,startDate:row.start_date?String(row.start_date).slice(0,10):'',endDate:row.end_date?String(row.end_date).slice(0,10):'',currency:row.currency??'',rentAmount:row.rent_amount??'',depositAmount:row.deposit_amount??'0',dueDay:row.due_day??1,customFields:row.custom_fields,checklist:row.checklist??[],findings:row.findings??[],terms:row.terms??{}}));}},[record.data]);
 const save=useMutation({mutationFn:async()=>{const common={assetId:form.assetId,customFields:form.customFields,...(id?{version:record.data!.data.version}:{})};const payload=section==='leases'?{...common,name:form.name,tenantContactId:form.tenantContactId,guarantorContactId:form.guarantorContactId,startDate:form.startDate,endDate:form.endDate,currency:form.currency,rentAmount:form.rentAmount,depositAmount:form.depositAmount,dueDay:Number(form.dueDay),terms:form.terms}:section==='maintenance'?{...common,title:form.title,description:form.description,priority:form.priority,assignedUserId:form.assignedUserId,supplierId:form.supplierId}:{...common,title:form.title,inspectorUserId:form.inspectorUserId,scheduledAt:form.scheduledAt||null,checklist:form.checklist,findings:form.findings};return (await (await apiRequest(id?'PATCH':'POST',`/api/erp/real-estate/${section}${id?`/${id}`:''}`,payload)).json()).data;},onSuccess:data=>{cache.invalidateQueries({queryKey:['real-estate',access.companyId]});navigate(`/erp/real-estate/${section}/${data.id}`);toast({title:t('erp.common.saved','Saved')});},onError:(error:Error)=>toast({title:t('common.error','Error'),description:error.message,variant:'destructive'})});
 const field=(key:string,label:string,type='text')=><div className="space-y-2"><Label htmlFor={`operation-${key}`}>{t(`erp.realEstate.operations.fields.${key}`,label)}</Label><Input id={`operation-${key}`} type={type} value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})}/></div>;
 const select=(key:string,label:string,options:Array<{value:string;label:string}>)=><div className="space-y-2"><Label htmlFor={`operation-${key}`}>{t(`erp.realEstate.operations.fields.${key}`,label)}</Label><Select value={String(form[key]??'none')} onValueChange={value=>setForm({...form,[key]:key.endsWith('Id')?(value==='none'?null:Number(value)):value})}><SelectTrigger id={`operation-${key}`}><SelectValue/></SelectTrigger><SelectContent>{options.map(option=><SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select></div>;
 return <RealEstateShell title={t(`erp.realEstate.${section}.${id?'edit':'add'}`,id?'Edit record':section==='leases'?'New lease':section==='maintenance'?'Create maintenance request':'New inspection')} description={t('erp.realEstate.operations.editorDescription','Connect the property and record the details needed for this workflow.')} icon={operationIcons[section]} actions={<><Button variant="outline" onClick={()=>navigate(`/erp/real-estate/${section}${id?`/${id}`:''}`)}>{t('common.cancel','Cancel')}</Button><Button disabled={!access.canManage||!definitions.data||!context.data||!form.assetId||save.isPending||(section==='leases'&&(!access.financial||!form.tenantContactId))} onClick={()=>save.mutate()}>{t('erp.common.save','Save')}</Button></>}>
 {definitions.isError||context.isError||record.isError?<div role="alert" className="re-panel p-8">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="outline" onClick={()=>{definitions.refetch();context.refetch();if(id)record.refetch();}}>{t('common.retry','Retry')}</Button></div>:!definitions.data||!context.data||(id&&!record.data)?<div className="re-panel h-80 animate-pulse" role="status"/>:<div className="grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-4"><section className="re-form-section"><h2>{t('erp.realEstate.operations.details','Record details')}</h2><div className="grid gap-4 sm:grid-cols-2">{field(section==='leases'?'name':'title',section==='leases'?'Lease name':'Title')}<div className="space-y-2"><Input aria-label={t('erp.realEstate.schedule.searchAssets','Search properties and units')} value={search} onChange={event=>setSearch(event.target.value)}/>{select('assetId','Property / unit',[{value:'none',label:t('erp.common.none','None')},...(assets.data??[]).map(asset=>({value:String(asset.id),label:`${asset.code} · ${asset.name}`}))])}</div>{section==='leases'?<>{field('startDate','Start date','date')}{field('endDate','End date','date')}<div className="space-y-2"><Input aria-label={t('erp.realEstate.contacts.searchCrm','Search CRM contacts')} value={contactSearch} onChange={event=>setContactSearch(event.target.value)}/>{select('tenantContactId','Tenant contact',[{value:'none',label:t('erp.common.none','None')},...(contacts.data?.data??[]).map(contact=>({value:String(contact.id),label:contact.name}))])}</div>{select('guarantorContactId','Guarantor contact',[{value:'none',label:t('erp.common.none','None')},...(contacts.data?.data??[]).map(contact=>({value:String(contact.id),label:contact.name}))])}{field('dueDay','Rent due day','number')}</>:select(section==='maintenance'?'assignedUserId':'inspectorUserId','Assigned user',[{value:'none',label:t('erp.common.none','None')},...context.data.agents.map(agent=>({value:String(agent.id),label:agent.name}))])}</div>{section==='maintenance'&&vendorAccess.enabled&&<div className="mt-4">{select('supplierId','Vendor',[{value:'none',label:t('erp.common.none','None')},...(vendors.data?.data??[]).map(v=>({value:String(v.id),label:v.name}))])}</div>}{section==='maintenance'&&<div className="mt-4 space-y-2"><Label htmlFor="operation-description">{t('erp.realEstate.fields.description','Description')}</Label><Textarea id="operation-description" value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></div>}</section>
 {section==='inspections'&&<section className="re-form-section"><h2>{t('erp.realEstate.inspections.checklist','Inspection checklist')}</h2><div className="mb-4 flex gap-2"><Input aria-label={t('erp.realEstate.inspections.checklistItem','Checklist item')} value={checklistLabel} onChange={event=>setChecklistLabel(event.target.value)}/><Button variant="outline" disabled={!checklistLabel.trim()} onClick={()=>{setForm({...form,checklist:[...form.checklist,{label:checklistLabel,checked:false}]});setChecklistLabel('');}}>{t('common.add','Add')}</Button></div>{form.checklist.map((item:{label:string;checked:boolean},index:number)=><label key={index} className="flex items-center gap-3 border-b border-border py-3 text-sm"><input type="checkbox" checked={item.checked} onChange={event=>setForm({...form,checklist:form.checklist.map((entry:unknown,i:number)=>i===index?{...item,checked:event.target.checked}:entry)})}/>{item.label}</label>)}</section>}
 {section==='inspections'&&<section className="re-form-section"><h2>{t('erp.realEstate.inspections.findings','Inspection findings')}</h2><div className="mb-5 space-y-2"><Label htmlFor="inspection-scheduled">{t('erp.realEstate.inspections.scheduledLocal','Scheduled time')+` (${context.data?.timezone??'UTC'})`}</Label><Input id="inspection-scheduled" type="datetime-local" disabled={!context.data?.timezone} value={form.scheduledAt?(()=>{const p=getZonedDateTimeParts(new Date(form.scheduledAt),context.data?.timezone??'UTC');return `${p.dateKey}T${String(p.hour).padStart(2,'0')}:${String(p.minute).padStart(2,'0')}`;})():''} onChange={e=>setForm({...form,scheduledAt:e.target.value?zonedDateTimeToUtc(`${e.target.value}:00`,context.data?.timezone??'UTC').toISOString():null})}/></div>{form.findings.map((finding:{description:string;severity:string},index:number)=><div key={index} className="mb-4 space-y-2"><Textarea aria-label={t('erp.realEstate.inspections.findingDescription','Finding description')} value={finding.description} onChange={e=>setForm({...form,findings:form.findings.map((f:unknown,i:number)=>i===index?{...finding,description:e.target.value}:f)})}/><div className="flex gap-2"><Select value={finding.severity} onValueChange={value=>setForm({...form,findings:form.findings.map((f:unknown,i:number)=>i===index?{...finding,severity:value}:f)})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['minor','major','critical'].map(severity=><SelectItem key={severity} value={severity}>{t(`erp.realEstate.inspections.severity.${severity}`,severity)}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={()=>setForm({...form,findings:form.findings.filter((_:unknown,i:number)=>i!==index)})}>{t('common.remove','Remove')}</Button></div></div>)}<Button variant="outline" onClick={()=>setForm({...form,findings:[...form.findings,{description:'',severity:'minor'}]})}>{t('erp.realEstate.inspections.addFinding','Add finding')}</Button></section>}
 <section className="re-form-section"><h2>{t('erp.realEstate.editor.customFields','Additional information')}</h2><ErpCustomFieldsEditor definitions={definitions.data} values={form.customFields} onChange={customFields=>setForm({...form,customFields})}/></section></div><div className="space-y-4">{section==='leases'&&access.financial?<section className="re-form-section"><h2>{t('erp.realEstate.operations.financialTerms','Financial terms')}</h2><div className="space-y-4">{select('currency','ERP currency',context.data.currencies.map(currency=>({value:currency.code,label:`${currency.code} · ${currency.name}`})))}{field('rentAmount','Monthly rent','number')}{field('depositAmount','Security deposit','number')}<label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={form.terms.automaticRent===true} onChange={e=>setForm({...form,terms:{...form.terms,automaticRent:e.target.checked}})}/>{t('erp.realEstate.billing.automaticRent','Generate and issue monthly rent automatically')}</label>{billing.data&&<div className="space-y-4 border-t border-border pt-4">{[['rentCatalogItemId','Rent Catalog item'],['depositCatalogItemId','Deposit Catalog item'],['rentTaxGroupId','Rent tax group'],['rentRevenueAccountId','Rent revenue account'],['ownerFundsAccountId','Owner funds account'],['depositAccountId','Deposit liability account']].map(([key,label])=><div key={key} className="space-y-2"><Label htmlFor={`billing-${key}`}>{t(`erp.realEstate.billing.${key}`,label)}</Label><Select value={String(form.terms[key]??'none')} onValueChange={value=>setForm({...form,terms:{...form.terms,[key]:value==='none'?null:Number(value)}})}><SelectTrigger id={`billing-${key}`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">{t('erp.common.none','None')}</SelectItem>{(key.includes('Catalog')?billing.data.items:key==='rentTaxGroupId'?billing.data.taxGroups:billing.data.accounts.filter(account=>account.type===(key==='rentRevenueAccountId'?'revenue':'liability'))).map(item=><SelectItem key={item.id} value={String(item.id)}>{item.name}</SelectItem>)}</SelectContent></Select></div>)}</div>}</div></section>:section==='maintenance'?<section className="re-form-section"><h2>{t('erp.realEstate.operations.priority','Priority')}</h2>{select('priority','Priority',['low','normal','high','urgent'].map(value=>({value,label:t(`erp.realEstate.priority.${value}`,value)})))}</section>:null}</div></div>}
 </RealEstateShell>;
}
