import {formatDate} from '@/lib/utils';
import {useErpCurrencies} from '@/hooks/use-erp-currencies';
import { useState } from 'react';
import { Link,useLocation } from 'wouter';
import { useQuery } from '@tanstack/react-query';
import { useTranslation } from '@/hooks/use-translation';
import { apiRequest } from '@/lib/queryClient';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Table,TableHeader,TableRow,TableHead,TableBody,TableCell } from '@/components/ui/table';
import { REAL_ESTATE_OPERATION_TRANSITIONS } from '@shared/real-estate-operations';
import { RealEstateShell } from './real-estate-shell';
import { useRealEstateAccess } from './use-real-estate-access';
export type OperationSection='leases'|'maintenance'|'inspections';
export type OperationRecord={id:number;name?:string;title?:string;asset_id:number;asset_name:string;asset_kind:string;status:string;priority?:string;version:number;created_at:string;updated_at:string;custom_fields:Record<string,unknown>;[key:string]:any};
export const operationIcons={leases:'ri-file-list-3-line',maintenance:'ri-tools-line',inspections:'ri-survey-line'};
export default function Operations({section}:{section:OperationSection}){
 const access=useRealEstateAccess(section),{t,currentLanguage}=useTranslation(),[,navigate]=useLocation(),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[offset,setOffset]=useState(0);
 const {formatMoney}=useErpCurrencies({enabled:access.enabled&&access.financial});
 const query=useQuery<{data:OperationRecord[];total:number}>({enabled:access.enabled,queryKey:['real-estate',access.companyId,section,search,status,offset],queryFn:async()=>{const params=new URLSearchParams({search,limit:'25',offset:String(offset)});if(status!=='all')params.set('status',status);return (await apiRequest('GET',`/api/erp/real-estate/${section}?${params}`)).json();}});
 const labels={leases:'Leases',maintenance:'Maintenance',inspections:'Inspections'};
 return <RealEstateShell title={t(`erp.realEstate.${section}.title`,labels[section])} description={t(`erp.realEstate.${section}.description`,section==='leases'?'Manage occupancy contracts and rental obligations.':section==='maintenance'?'Track property repairs from request to resolution.':'Document property condition with checklists and findings.')} icon={operationIcons[section]} actions={access.canManage&&(section!=='leases'||access.financial)&&<Button onClick={()=>navigate(`/erp/real-estate/${section}/new`)}>{t(`erp.realEstate.${section}.add`,section==='leases'?'New lease':section==='maintenance'?'Create maintenance request':'New inspection')}</Button>}>
  <div className="re-panel mb-4 flex flex-wrap gap-3 p-3"><Input className="min-w-0 flex-1 sm:max-w-md" value={search} aria-label={t('common.search','Search')} placeholder={t('erp.realEstate.operations.search','Search records…')} onChange={event=>{setSearch(event.target.value);setOffset(0);}}/><Select value={status} onValueChange={value=>{setStatus(value);setOffset(0);}}><SelectTrigger className="w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{t('erp.realEstate.allStatuses','All statuses')}</SelectItem>{Object.keys(REAL_ESTATE_OPERATION_TRANSITIONS[section]).map(status=><SelectItem key={status} value={status}>{t(`erp.realEstate.${section}Status.${status}`,status)}</SelectItem>)}</SelectContent></Select></div>
  {query.isError?<div role="alert" className="re-panel p-8">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="outline" onClick={()=>query.refetch()}>{t('common.retry','Retry')}</Button></div>:query.isLoading?<div role="status" className="re-panel h-64 animate-pulse"/>:!query.data?.data.length?<div className="re-panel py-16 text-center"><i className={`${operationIcons[section]} text-4xl text-primary`} aria-hidden="true"/><h2 className="mt-4 font-semibold">{t('erp.realEstate.operations.empty','No records match this view')}</h2><p className="mt-2 text-sm text-muted-foreground">{t('erp.realEstate.operations.emptyDescription','Create a record to start managing this workflow.')}</p></div>:<div className="re-panel overflow-x-auto"><Table><TableHeader><TableRow>{['reference','property','status',section==='leases'?'endDate':'updated',...(section==='leases'&&access.financial?['rent']:[])].map(key=><TableHead key={key}>{t(`erp.realEstate.operations.columns.${key}`,key==='endDate'?'End date':key.charAt(0).toUpperCase()+key.slice(1))}</TableHead>)}</TableRow></TableHeader><TableBody>{query.data.data.map(record=><TableRow key={record.id}><TableCell><Link className="font-medium hover:text-primary" href={`/erp/real-estate/${section}/${record.id}`}>{record.name??record.title}</Link><p className="mt-1 text-xs text-muted-foreground">#{record.id}{record.priority?` · ${t(`erp.realEstate.priority.${record.priority}`,record.priority)}`:''}</p></TableCell><TableCell>{record.asset_name}</TableCell><TableCell><span className={`re-status re-status-${record.status}`}>{t(`erp.realEstate.${section}Status.${record.status}`,record.status)}</span></TableCell><TableCell className="whitespace-nowrap text-xs">{record.end_date?formatDate(record.end_date,{locale:currentLanguage?.code,calendarDate:true}):new Intl.DateTimeFormat(currentLanguage?.code,{dateStyle:'medium'}).format(new Date(record.updated_at))}</TableCell>{section==='leases'&&access.financial&&<TableCell className="whitespace-nowrap">{formatMoney(Number(record.rent_amount??0),record.currency??'USD',currentLanguage?.code)}</TableCell>}</TableRow>)}</TableBody></Table></div>}
  {!!query.data?.total&&<div className="mt-4 flex justify-between text-xs text-muted-foreground"><span>{offset+1}–{Math.min(offset+25,query.data.total)} / {query.data.total}</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={!offset} onClick={()=>setOffset(offset-25)}>{t('common.previous','Previous')}</Button><Button variant="outline" size="sm" disabled={offset+25>=query.data.total} onClick={()=>setOffset(offset+25)}>{t('common.next','Next')}</Button></div></div>}
 </RealEstateShell>;
}
