import {ErpCalendarError} from '@/components/erp/ErpCalendarError';
import {useErpCalendar,useErpCalendarDefault} from '@/hooks/use-erp-calendar';
import {formatDate} from '@/lib/utils';
import { useState } from 'react';
import { Link } from 'wouter';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useTranslation } from '@/hooks/use-translation';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter } from '@/components/ui/dialog';
import { useRealEstateAccess } from './use-real-estate-access';
type Version={id:number;effective_from:string;effective_to:string|null;shares:Array<{contactId:number|null;name:string|null;percentage:string}>};
export function Ownership({assetId,canManageAsset}:{assetId:number;canManageAsset:boolean}){
 const calendarAccess=useRealEstateAccess('owners'),calendar=useErpCalendar(calendarAccess.enabled,'/api/erp/real-estate/calendar');
  const access=useRealEstateAccess('owners'),{t,currentLanguage}=useTranslation(),{toast}=useToast(),cache=useQueryClient();
  const [open,setOpen]=useState(false),[closeId,setCloseId]=useState<number|null>(null),[from,setFrom]=useErpCalendarDefault(calendar),[to,setTo]=useState(''),[search,setSearch]=useState('');
  const [shares,setShares]=useState<Array<{contactId:number|null;percentage:string}>>([{contactId:null,percentage:'100'}]);
  const query=useQuery<{data:Version[]}>({enabled:access.enabled&&access.financial,queryKey:['real-estate',access.companyId,'ownership',assetId],queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/assets/${assetId}/ownership`)).json()});
  const contacts=useQuery<{data:Array<{id:number;name:string}>}>({enabled:open&&access.enabled&&access.canManage&&access.financial,queryKey:['real-estate',access.companyId,'ownership-contacts',search],queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/contacts/search?search=${encodeURIComponent(search)}`)).json()});
  const save=useMutation({mutationFn:async()=>closeId?apiRequest('PATCH',`/api/erp/real-estate/assets/${assetId}/ownership/${closeId}`,{effectiveTo:to}):apiRequest('PUT',`/api/erp/real-estate/assets/${assetId}/ownership`,{effectiveFrom:from,effectiveTo:to||null,shares}),onSuccess:()=>{cache.invalidateQueries({queryKey:['real-estate',access.companyId]});setOpen(false);setCloseId(null);toast({title:t('erp.common.saved','Saved')});},onError:(error:Error)=>toast({title:t('common.error','Error'),description:error.message,variant:'destructive'})});
  const date=(value:string)=>formatDate(value,{locale:currentLanguage?.code,calendarDate:true});
  if(!access.enabled||!access.financial)return null;
  const manage=access.canManage&&canManageAsset;
  return <section className="re-panel p-5"><ErpCalendarError calendar={calendar}/><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">{t('erp.realEstate.ownership.title','Ownership history')}</h2>{manage&&<Button size="sm" variant="outline" onClick={()=>{setCloseId(null);setTo('');setOpen(true);}}>{t('erp.realEstate.ownership.add','Add ownership period')}</Button>}</div>
    {query.isError?<div role="alert">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="outline" onClick={()=>query.refetch()}>{t('common.retry','Retry')}</Button></div>:query.isLoading?<div className="h-32 animate-pulse bg-muted" role="status"/>:!query.data?.data.length?<p className="text-sm text-muted-foreground">{t('erp.realEstate.ownership.empty','No ownership shares have been configured.')}</p>:<div className="space-y-4">{query.data.data.map(version=><div key={version.id} className="rounded-lg border border-border p-4"><div className="mb-3 flex flex-wrap justify-between gap-3"><h3 className="text-sm font-medium">{date(version.effective_from)} — {version.effective_to?date(version.effective_to):t('erp.realEstate.ownership.openEnded','Open-ended')}</h3>{!version.effective_to&&manage&&<Button variant="ghost" size="sm" onClick={()=>{setCloseId(version.id);setTo('');setOpen(true);}}>{t('erp.realEstate.ownership.close','Close period')}</Button>}</div>{version.shares.map((share,index)=><div key={index} className="flex justify-between gap-3 py-2 text-sm">{share.contactId?<Link className="text-primary hover:underline" href={`/erp/real-estate/owners/${share.contactId}`}>{share.name}</Link>:<span className="text-muted-foreground">{t('erp.realEstate.ownership.restricted','Restricted contact')}</span>}<strong>{Number(share.percentage)}%</strong></div>)}</div>)}</div>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{t(closeId?'erp.realEstate.ownership.close':'erp.realEstate.ownership.add',closeId?'Close period':'Add ownership period')}</DialogTitle><DialogDescription>{t('erp.realEstate.ownership.help','Shares must total 100%. Ownership periods cannot overlap.')}</DialogDescription></DialogHeader><div className="max-h-[60vh] space-y-4 overflow-y-auto">{!closeId&&<div className="space-y-2"><Label htmlFor="ownership-from">{t('erp.realEstate.ownership.from','Effective from')}</Label><Input id="ownership-from" type="date" value={from} onChange={event=>setFrom(event.target.value)}/></div>}<div className="space-y-2"><Label htmlFor="ownership-to">{t('erp.realEstate.ownership.to','Effective to')}</Label><Input id="ownership-to" type="date" value={to} onChange={event=>setTo(event.target.value)}/></div>{!closeId&&<><Input aria-label={t('erp.realEstate.contacts.searchCrm','Search CRM contacts')} value={search} onChange={event=>setSearch(event.target.value)}/>{shares.map((share,index)=><div key={index} className="grid grid-cols-[minmax(0,1fr)_80px_40px] gap-2"><Select value={share.contactId?String(share.contactId):'none'} onValueChange={value=>setShares(shares.map((item,i)=>i===index?{...item,contactId:Number(value)}:item))}><SelectTrigger aria-label={`${t('erp.realEstate.ownership.owner','Owner')} ${index+1}`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none" disabled>{t('erp.realEstate.contacts.link','Link CRM contact')}</SelectItem>{contacts.data?.data.map(contact=><SelectItem key={contact.id} value={String(contact.id)}>{contact.name}</SelectItem>)}</SelectContent></Select><Input aria-label={`${t('erp.realEstate.ownership.share','Share %')} ${index+1}`} type="number" min="0.0001" max="100" step="0.0001" value={share.percentage} onChange={event=>setShares(shares.map((item,i)=>i===index?{...item,percentage:event.target.value}:item))}/><Button size="icon" variant="ghost" disabled={shares.length===1} aria-label={t('common.remove','Remove')} onClick={()=>setShares(shares.filter((_,i)=>i!==index))}><i className="ri-close-line" aria-hidden="true"/></Button></div>)}<Button variant="outline" size="sm" onClick={()=>setShares([...shares,{contactId:null,percentage:''}])}>{t('erp.realEstate.ownership.addOwner','Add another owner')}</Button></>}</div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>{t('common.cancel','Cancel')}</Button><Button disabled={save.isPending||(closeId?!to:!from||shares.some(share=>!share.contactId))} onClick={()=>save.mutate()}>{t('erp.common.save','Save')}</Button></DialogFooter></DialogContent></Dialog>
  </section>;
}
