import {Link} from 'wouter';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {useTranslation} from '@/hooks/use-translation';
import {useErpCurrencies} from '@/hooks/use-erp-currencies';
import {apiRequest} from '@/lib/queryClient';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {erpRetainedAmountDigits} from '@shared/erp-currency-precision';

export function OwnerRentSummary({ownerId,companyId,asOf}:{ownerId:string;companyId:number|undefined;asOf:string}){
 const {t,currentLanguage}=useTranslation(),[period,setPeriod]=useState(asOf.slice(0,7)),{formatMoney,currencies}=useErpCurrencies();
 const query=useQuery<{issues:Array<{invoiceId:number;invoiceNumber:string;reason:string}>;forecast:null|{incomplete:number;rows:Array<{currency:string;leases:number;drafts:number;unissued:string}>};period:string;timezone:string;incomplete:number;rows:Array<{currency:string;obligations:number;expected:string;collected:string;unfunded:string}>}>({queryKey:['real-estate',companyId,'owners',ownerId,'rent-summary',period],enabled:/^\d{4}-(0[1-9]|1[0-2])$/.test(period),queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/owners/${ownerId}/rent-summary?period=${period}`)).json()});
 const money=(value:string,currency:string)=>formatMoney(Number(value),currency,currentLanguage?.code,erpRetainedAmountDigits(value,currencies.find(row=>row.code===currency)?.decimalPlaces));
 return <section className="re-panel mb-5 p-5" data-testid="owner-monthly-rent"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">{t('erp.realEstate.contacts.monthlyRent','Monthly owner rent')}</h2><div><label htmlFor="owner-rent-month" className="mb-1 block text-xs text-muted-foreground">{t('erp.realEstate.contacts.rentMonth','Month')}</label><Input id="owner-rent-month" type="month" value={period} onChange={event=>setPeriod(event.target.value)} className="w-44"/><p data-testid="owner-rent-period" className="mt-1 text-xs text-muted-foreground">{/^\d{4}-(0[1-9]|1[0-2])$/.test(period)?new Intl.DateTimeFormat(currentLanguage?.code,{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${period}-01T12:00:00Z`)):''}</p></div></div><p className="mt-2 text-xs text-muted-foreground">{t('erp.realEstate.contacts.monthlyRentBrief','Issued rent and dated receipts, excluding tax and allocated to historical owner shares.')}</p><details className="mt-2 text-xs text-muted-foreground"><summary className="cursor-pointer">{t('erp.realEstate.contacts.rentCalculation','How these amounts are calculated')}</summary><p className="mt-2">{t('erp.realEstate.contacts.monthlyRentHelp','Tax-exclusive owner shares from issued managed-rent invoices. Expected and unfunded relate to invoices issued in this month; collected relates to receipts dated in this month, including older invoices. Current credits and receipts revise these amounts. Unfunded is not the tenant invoice balance.')} {query.data?.timezone}</p></details>
 {query.isError?<div role="alert" className="mt-4 text-sm">{t('erp.realEstate.loadError','Unable to load this information.')} <Button variant="outline" onClick={()=>query.refetch()}>{t('common.retry','Retry')}</Button></div>:query.isLoading?<div role="status" className="mt-4 h-24 animate-pulse rounded-lg bg-muted"/>:<>
 {query.data?.forecast&&<div className="mt-4 rounded-xl border border-border p-4" data-testid="owner-rent-forecast"><h3 className="text-sm font-semibold">{t('erp.realEstate.contacts.unissuedRent','Unissued contractual rent')}</h3><p className="mt-2 text-xs text-muted-foreground">{t('erp.realEstate.contacts.unissuedRentHelp','Estimate for active or expired lease periods without an issued invoice, including accessible drafts. Uses actual-day proration, current contract terms and ownership at period issue date. Excludes tax; this is not billed or collected income.')}</p>{query.data.forecast.incomplete>0&&<p className="mt-2 text-sm">{t('erp.realEstate.contacts.forecastIncomplete','Some lease estimates require currency or ownership review and are excluded.')} {query.data.forecast.incomplete}</p>}{query.data.forecast.rows.length?<dl className="mt-3 space-y-3">{query.data.forecast.rows.map(row=><div key={row.currency} className="flex flex-wrap justify-between gap-3"><dt className="text-sm">{row.currency} · {row.leases} {t('erp.realEstate.leases.title','Leases')}</dt><dd data-testid={`owner-rent-${row.currency}-unissued`} className="text-sm font-semibold">{money(row.unissued,row.currency)}</dd></div>)}</dl>:<p className="mt-3 text-xs text-muted-foreground">{t('erp.realEstate.contacts.noUnissuedRent','No authorized unissued lease rent for this month.')}</p>}</div>}
 {query.data?.incomplete!==undefined&&query.data.incomplete>0&&<div className="mt-4 rounded-lg border border-amber-500/30 p-3" data-testid="owner-rent-evidence-issues"><p role="status" className="text-sm">{t('erp.realEstate.contacts.rentIncomplete','Some obligations require accounting reconciliation and are excluded from these totals.')} {query.data.incomplete}</p><div className="mt-3 space-y-2">{query.data.issues.map(issue=><Link key={issue.invoiceId} href={`/erp/invoices?detail=${issue.invoiceId}`} className="block rounded-lg border border-border p-3"><strong className="break-words text-sm">{issue.invoiceNumber}</strong><p className="mt-1 text-xs text-muted-foreground">{t(`erp.realEstate.contacts.rentEvidence.${issue.reason}`,issue.reason)}</p><span className="mt-2 block text-xs text-primary">{t('erp.realEstate.contacts.reviewInvoice','Review ERP invoice')} <i className="ri-arrow-right-line" aria-hidden="true"/></span></Link>)}</div></div>}

 {!query.data?.rows.length?<p className="py-5 text-sm text-muted-foreground">{t('erp.realEstate.contacts.noMonthlyRent','No authorized issued rent or receipts for this month.')}</p>:<div className="mt-4 grid gap-4 xl:grid-cols-2">{query.data.rows.map(row=><div key={row.currency} className="rounded-xl border border-border p-4"><strong>{row.currency}</strong><dl className="mt-4 grid gap-4 sm:grid-cols-3">{(['expected','collected','unfunded'] as const).map(key=><div key={key} className="min-w-0"><dt className="text-xs text-muted-foreground">{t(`erp.realEstate.contacts.rent${key[0].toUpperCase()+key.slice(1)}`,key)}</dt><dd data-testid={`owner-rent-${row.currency}-${key}`} className="mt-1 break-words font-semibold">{money(row[key],row.currency)}</dd></div>)}</dl></div>)}</div>}
 </>}
 </section>;
}
