import {useErpCurrencies} from '@/hooks/use-erp-currencies';
import {ContactCustomFieldsBadges} from '@/components/contacts/ContactCustomFieldsBadges';
import type {CompanyContactCustomField} from '@/hooks/use-company-contact-custom-fields';
import {WorkspaceDocuments} from './workspace-documents';
import { useState } from 'react';
import { Link,useLocation } from 'wouter';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useTranslation } from '@/hooks/use-translation';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter } from '@/components/ui/dialog';
import type { RealEstateProject,RealEstateHierarchy } from '@shared/real-estate-projects';
import type { RealEstateAsset } from '@shared/real-estate-contracts';
import { RealEstateShell } from './real-estate-shell';
import { useRealEstateAccess } from './use-real-estate-access';

export default function ProjectDetail({id}:{id:string}){
  const access=useRealEstateAccess('projects'),unitAccess=useRealEstateAccess('units'),{t,currentLanguage}=useTranslation(),{toast}=useToast(),cache=useQueryClient();
  const [,navigate]=useLocation(),[buildingId,setBuildingId]=useState('all'),[floorId,setFloorId]=useState('all'),[status,setStatus]=useState('all');
  const [dialog,setDialog]=useState<'building'|'floor'|null>(null),[name,setName]=useState(''),[code,setCode]=useState(''),[level,setLevel]=useState('0'),[offset,setOffset]=useState(0);
 const {formatMoney}=useErpCurrencies({enabled:access.enabled&&access.financial});
  const query=useQuery<{data:RealEstateProject;developer:{id:number;name:string;email:string|null;customFields:Record<string,unknown>}|null}&RealEstateHierarchy>({enabled:access.enabled,queryKey:['real-estate',access.companyId,'projects',id],queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/projects/${id}`)).json()});
  const contactFields=useQuery<{data:CompanyContactCustomField[]}>({enabled:access.enabled,queryKey:['real-estate',access.companyId,'contact-definitions'],queryFn:async()=>(await apiRequest('GET','/api/erp/real-estate/contacts/field-definitions')).json()});
  const units=useQuery<{data:RealEstateAsset[];total:number}>({enabled:access.enabled&&unitAccess.enabled,queryKey:['real-estate',access.companyId,'project-units',id,status,buildingId,floorId,offset],queryFn:async()=>{const params=new URLSearchParams({projectId:id,limit:'100',offset:String(offset)});if(status!=='all')params.set('status',status);if(buildingId!=='all')params.set('buildingId',buildingId);if(floorId!=='all')params.set('floorId',floorId);return (await apiRequest('GET',`/api/erp/real-estate/units?${params}`)).json();}});
  const add=useMutation({mutationFn:async()=>{if(dialog==='floor'&&buildingId==='all')throw new Error(t('erp.realEstate.projects.selectBuilding','Select a building first.'));return apiRequest('POST',dialog==='building'?`/api/erp/real-estate/projects/${id}/buildings`:`/api/erp/real-estate/buildings/${buildingId}/floors`,dialog==='building'?{name,code}:{name,level:Number(level)});},onSuccess:()=>{cache.invalidateQueries({queryKey:['real-estate',access.companyId]});setDialog(null);setName('');setCode('');toast({title:t('erp.common.saved','Saved')});},onError:(error:Error)=>toast({title:t('common.error','Error'),description:error.message,variant:'destructive'})});
  const project=query.data?.data;
  const visible=(units.data?.data??[]).filter(unit=>(buildingId==='all'||String(unit.building_id)===buildingId)&&(floorId==='all'||String(unit.floor_id)===floorId));
  const select=(value:string,onChange:(value:string)=>void,label:string,options:Array<{id:number;name:string}>)=><Select value={value} onValueChange={onChange}><SelectTrigger className="w-full sm:w-48" aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{label}</SelectItem>{options.map(option=><SelectItem key={option.id} value={String(option.id)}>{option.name}</SelectItem>)}</SelectContent></Select>;
  return <RealEstateShell title={project?.name??t('erp.realEstate.projects.title','Projects')} description={project?`${project.code} · ${project.location??''}`:''} icon="ri-building-line" actions={<><Button variant="outline" onClick={()=>navigate('/erp/real-estate/projects')}>{t('erp.realEstate.projects.back','Back to projects')}</Button>{access.canManage&&<Button onClick={()=>navigate(`/erp/real-estate/projects/${id}/edit`)}>{t('common.edit','Edit')}</Button>}</>}>
    {query.isError?<div className="re-panel p-8" role="alert">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="outline" onClick={()=>query.refetch()}>{t('common.retry','Retry')}</Button></div>:!project?<div className="re-panel h-80 animate-pulse" role="status"/>:<>
      <div className="mb-4 grid gap-4 lg:grid-cols-[minmax(0,1fr)_320px]"><section className="re-panel p-5"><span className="re-status">{t(`erp.realEstate.projectStatus.${project.status}`,project.status)}</span><h2 className="mt-4 font-semibold">{t('erp.realEstate.projects.overview','Development overview')}</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{project.description||t('erp.realEstate.noDescription','No description has been added.')}</p><div className="mt-5 grid grid-cols-2 gap-4 border-t border-border pt-4"><div><strong className="text-2xl">{query.data!.buildings.length}</strong><p className="text-xs text-muted-foreground">{t('erp.realEstate.projects.buildings','Buildings / towers')}</p></div><div><strong className="text-2xl">{query.data!.floors.length}</strong><p className="text-xs text-muted-foreground">{t('erp.realEstate.projects.floors','Floors')}</p></div></div></section><section className="re-panel p-5"><h2 className="font-semibold">{t('erp.realEstate.projects.hierarchy','Organize inventory')}</h2><p className="mt-2 text-sm text-muted-foreground">{t('erp.realEstate.projects.hierarchyDescription','Buildings contain floors; each unit belongs to one floor.')}</p>{access.canManage&&<div className="mt-5 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setDialog('building')}>{t('erp.realEstate.projects.addBuilding','Add building')}</Button><Button variant="outline" disabled={buildingId==='all'} onClick={()=>setDialog('floor')}>{t('erp.realEstate.projects.addFloor','Add floor')}</Button></div>}{unitAccess.canManage&&unitAccess.financial&&<Button className="mt-3 w-full" onClick={()=>navigate(`/erp/real-estate/units/new?projectId=${id}${buildingId==='all'?'':`&buildingId=${buildingId}`}${floorId==='all'?'':`&floorId=${floorId}`}`)}>{t('erp.realEstate.units.add','Add unit')}</Button>}</section></div>
      <section className="re-panel p-4 sm:p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">{t('erp.realEstate.unitHierarchy','Project inventory')}</h2><span className="text-xs text-muted-foreground">{units.data?.total??0} {t('erp.realEstate.units.title','Units')}</span></div><div className="mb-5 flex flex-wrap gap-2">{select(buildingId,value=>{setBuildingId(value);setFloorId('all');setOffset(0);},t('erp.realEstate.projects.allBuildings','All buildings'),query.data!.buildings)}{select(floorId,value=>{setFloorId(value);setOffset(0);},t('erp.realEstate.projects.allFloors','All floors'),query.data!.floors.filter(floor=>buildingId==='all'||String(floor.building_id)===buildingId))}<Select value={status} onValueChange={value=>{setStatus(value);setOffset(0);}}><SelectTrigger className="w-full sm:w-44" aria-label={t('erp.realEstate.allStatuses','All statuses')}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{t('erp.realEstate.allStatuses','All statuses')}</SelectItem>{['available','occupied','rented','reserved','sold','blocked'].map(status=><SelectItem key={status} value={status}>{t(`erp.realEstate.status.${status}`,status)}</SelectItem>)}</SelectContent></Select></div>
        {!unitAccess.enabled?<p className="py-8 text-center text-sm text-muted-foreground">{t('erp.realEstate.projects.inventoryPermission','Unit access is required to view this inventory.')}</p>:units.isError?<div role="alert">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="outline" onClick={()=>units.refetch()}>{t('common.retry','Retry')}</Button></div>:units.isLoading?<div role="status" className="h-48 animate-pulse bg-muted rounded-lg"/>:!visible.length?<div className="rounded-lg border border-dashed border-border py-12 text-center"><i className="ri-layout-grid-line text-3xl text-muted-foreground" aria-hidden="true"/><p className="mt-3 text-sm text-muted-foreground">{t('erp.realEstate.projects.noUnits','No units match this selection.')}</p></div>:<div className="space-y-5">{query.data!.floors.filter(floor=>visible.some(unit=>unit.floor_id===floor.id)).map(floor=><div key={floor.id}><div className="mb-2 flex items-center gap-2 text-xs text-muted-foreground"><i className="ri-stack-line" aria-hidden="true"/>{query.data!.buildings.find(building=>building.id===floor.building_id)?.name} · {floor.name}</div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">{visible.filter(unit=>unit.floor_id===floor.id).map(unit=><Link key={unit.id} href={`/erp/real-estate/units/${unit.id}`} className="re-panel re-property-card p-3"><span className={`re-status re-status-${unit.status}`}>{t(`erp.realEstate.status.${unit.status}`,unit.status)}</span><h3 className="mt-3 truncate text-sm font-semibold">{unit.name}</h3><p className="mt-1 truncate text-xs text-muted-foreground">{unit.code}</p>{unitAccess.financial&&<p className="mt-3 text-xs font-medium">{formatMoney(Number(unit.sale_price??unit.rental_price??0),unit.currency??'USD',currentLanguage?.code)}</p>}</Link>)}</div></div>)}</div>}
        {!!units.data?.total&&units.data.total>100&&<div className="mt-5 flex justify-end gap-2"><Button variant="outline" disabled={!offset} onClick={()=>setOffset(offset-100)}>{t('common.previous','Previous')}</Button><Button variant="outline" disabled={offset+100>=units.data.total} onClick={()=>setOffset(offset+100)}>{t('common.next','Next')}</Button></div>}
      </section>
    </>}
    {query.data?.developer&&<section className="re-panel mt-5 p-5"><h2 className="mb-3 font-semibold">{t('erp.realEstate.projects.developer','CRM developer')}</h2><p className="font-medium">{query.data.developer.name}</p><p className="mt-1 text-xs text-muted-foreground">{query.data.developer.email??'—'}</p><div className="mt-3"><ContactCustomFieldsBadges customFields={query.data.developer.customFields} schema={contactFields.data?.data??[]} maxVisible={6}/></div></section>}
    <Dialog open={dialog!==null} onOpenChange={open=>{if(!open)setDialog(null);}}><DialogContent><DialogHeader><DialogTitle>{t(dialog==='building'?'erp.realEstate.projects.addBuilding':'erp.realEstate.projects.addFloor',dialog==='building'?'Add building':'Add floor')}</DialogTitle><DialogDescription>{t('erp.realEstate.projects.hierarchyDescription','Buildings contain floors; each unit belongs to one floor.')}</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label htmlFor="hierarchy-name">{t('erp.realEstate.projects.hierarchyName','Name')}</Label><Input id="hierarchy-name" value={name} onChange={event=>setName(event.target.value)}/></div><div className="space-y-2"><Label htmlFor="hierarchy-code">{t(dialog==='building'?'erp.realEstate.projects.fields.code':'erp.realEstate.projects.floorLevel',dialog==='building'?'Reference code':'Floor level')}</Label><Input id="hierarchy-code" type={dialog==='floor'?'number':'text'} value={dialog==='building'?code:level} onChange={event=>dialog==='building'?setCode(event.target.value):setLevel(event.target.value)}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setDialog(null)}>{t('common.cancel','Cancel')}</Button><Button disabled={!name||add.isPending||(dialog==='building'&&!code)} onClick={()=>add.mutate()}>{t('erp.common.save','Save')}</Button></DialogFooter></DialogContent></Dialog>
  <WorkspaceDocuments entityType={'project'} entityId={Number(id)}/>
 </RealEstateShell>;
}
