import { useEffect,useState } from 'react';
import { useLocation } from 'wouter';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useTranslation } from '@/hooks/use-translation';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { ErpCustomFieldsEditor,type ErpFieldDefinition } from '@/components/erp/ErpCustomFieldsEditor';
import { ImageUploadDialog } from '@/components/ui/image-upload-dialog';
import type { RealEstateProject } from '@shared/real-estate-projects';
import { RealEstateShell } from './real-estate-shell';
import { useRealEstateAccess } from './use-real-estate-access';

export default function ProjectEditor({id}:{id?:string}){
  const access=useRealEstateAccess('projects'),{t}=useTranslation(),{toast}=useToast(),cache=useQueryClient();
  const [,navigate]=useLocation(),[imagesOpen,setImagesOpen]=useState(false),[contactSearch,setContactSearch]=useState('');
  const [form,setForm]=useState({name:'',code:'',location:'',description:'',status:'planning',handoverDate:'',developerContactId:null as number|null,images:[] as Array<{url:string;alt?:string}>,customFields:{} as Record<string,unknown>});
  const record=useQuery<{data:RealEstateProject}>({enabled:access.enabled&&access.canManage&&!!id,queryKey:['real-estate',access.companyId,'projects',id],queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/projects/${id}`)).json()});
  const contacts=useQuery<{data:Array<{id:number;name:string}>}>({enabled:access.enabled&&access.canManage,queryKey:['real-estate',access.companyId,'project-contact-search',contactSearch],queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/contacts/search?search=${encodeURIComponent(contactSearch)}`)).json()});
  const definitions=useQuery<ErpFieldDefinition[]>({enabled:access.enabled&&access.canManage,queryKey:['erp-custom-fields',access.companyId,'real_estate_project'],queryFn:async()=>(await (await apiRequest('GET','/api/erp/custom-fields/real_estate_project')).json()).data});
  useEffect(()=>{if(record.data){const project=record.data.data;setForm({name:project.name,code:project.code,location:project.location??'',description:project.description??'',status:project.status,handoverDate:project.handover_date?.slice(0,10)??'',developerContactId:project.developer_contact_id,images:project.images,customFields:project.custom_fields});}},[record.data]);
  const save=useMutation({mutationFn:async()=>(await (await apiRequest(id?'PATCH':'POST',`/api/erp/real-estate/projects${id?`/${id}`:''}`,{...form,handoverDate:form.handoverDate||null,...(id?{version:record.data!.data.version}:{})})).json()).data,onSuccess:data=>{cache.invalidateQueries({queryKey:['real-estate',access.companyId]});navigate(`/erp/real-estate/projects/${data.id}`);toast({title:t('erp.common.saved','Saved')});},onError:(error:Error)=>toast({title:t('common.error','Error'),description:error.message,variant:'destructive'})});
  const field=(key:'name'|'code'|'location'|'handoverDate',label:string,type='text')=><div className="space-y-2"><Label htmlFor={`project-${key}`}>{t(`erp.realEstate.projects.fields.${key}`,label)}</Label><Input id={`project-${key}`} type={type} value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})}/></div>;
  return <RealEstateShell title={t(id?'erp.realEstate.projects.edit':'erp.realEstate.projects.add',id?'Edit project':'Add project')} description={t('erp.realEstate.projects.editorDescription','Define the development before adding its buildings and units.')} icon="ri-building-line" actions={<><Button variant="outline" onClick={()=>navigate(`/erp/real-estate/projects${id?`/${id}`:''}`)}>{t('common.cancel','Cancel')}</Button><Button disabled={!access.canManage||!form.name||!form.code||!definitions.data||(!!id&&!record.data)||save.isPending} onClick={()=>save.mutate()}>{t('erp.common.save','Save')}</Button></>}>
    {record.isError||definitions.isError?<div className="re-panel p-8" role="alert">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="outline" onClick={()=>{definitions.refetch();if(id)record.refetch();}}>{t('common.retry','Retry')}</Button></div>:!definitions.data||(id&&!record.data)?<div role="status" className="re-panel h-80 animate-pulse"/>:<div className="grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-4"><section className="re-form-section"><h2>{t('erp.realEstate.projects.identity','Project identity')}</h2><div className="grid gap-4 sm:grid-cols-2">{field('name','Project name')}{field('code','Reference code')}{field('location','Location')}{field('handoverDate','Target handover','date')}<div className="space-y-2"><Label htmlFor="project-developer">{t('erp.realEstate.projects.developer','CRM developer')}</Label><Input aria-label={t('erp.realEstate.contacts.searchCrm','Search CRM contacts')} value={contactSearch} onChange={e=>setContactSearch(e.target.value)}/><Select value={String(form.developerContactId??'none')} onValueChange={v=>setForm({...form,developerContactId:v==='none'?null:Number(v)})}><SelectTrigger id="project-developer"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">{t('erp.common.none','None')}</SelectItem>{contacts.data?.data.map(c=><SelectItem key={c.id} value={String(c.id)}>{c.name}</SelectItem>)}</SelectContent></Select></div></div><div className="mt-4 space-y-2"><Label htmlFor="project-description">{t('erp.realEstate.fields.description','Description')}</Label><Textarea id="project-description" value={form.description} rows={5} onChange={event=>setForm({...form,description:event.target.value})}/></div></section><section className="re-form-section"><h2>{t('erp.realEstate.editor.customFields','Additional information')}</h2><ErpCustomFieldsEditor definitions={definitions.data} values={form.customFields} onChange={customFields=>setForm({...form,customFields})}/></section></div>
    <div className="space-y-4"><section className="re-form-section"><h2>{t('erp.realEstate.projects.stage','Development stage')}</h2><Select value={form.status} onValueChange={status=>setForm({...form,status})}><SelectTrigger aria-label={t('erp.realEstate.projects.stage','Development stage')}><SelectValue/></SelectTrigger><SelectContent>{['planning','construction','completed','archived'].map(status=><SelectItem value={status} key={status}>{t(`erp.realEstate.projectStatus.${status}`,status)}</SelectItem>)}</SelectContent></Select></section><section className="re-form-section"><h2>{t('erp.realEstate.gallery','Property gallery')}</h2><div className="space-y-3">{form.images.map((image,index)=><div key={`${image.url}-${index}`}><img src={image.url} alt={image.alt??form.name} className="h-32 w-full rounded-lg object-cover"/><Button variant="ghost" size="sm" onClick={()=>setForm({...form,images:form.images.filter((_,i)=>i!==index)})}>{t('erp.realEstate.removeImage','Remove image')}</Button></div>)}<Button variant="outline" disabled={form.images.length>=40} onClick={()=>setImagesOpen(true)}>{t('erp.realEstate.addImage','Add image')}</Button></div></section></div></div>}
    <ImageUploadDialog isOpen={imagesOpen} onClose={()=>setImagesOpen(false)} allowUrlInput={false} uploadUrl="/api/erp/real-estate/images/upload" onImageInsert={(url,alt)=>setForm(prior=>({...prior,images:[...prior.images,{url,alt}]}))}/>
  </RealEstateShell>;
}
