import {useErpCurrencies} from '@/hooks/use-erp-currencies';
import {CostSources} from './cost-sources';
import {ContactCustomFieldsBadges} from '@/components/contacts/ContactCustomFieldsBadges';
import type {CompanyContactCustomField} from '@/hooks/use-company-contact-custom-fields';
import { Link,useLocation } from 'wouter';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useAuth } from '@/hooks/use-auth';
import { useTranslation } from '@/hooks/use-translation';
import { usePermissions } from '@/hooks/usePermissions';
import { apiRequest } from '@/lib/queryClient';
import { Button } from '@/components/ui/button';
import { Tabs,TabsContent,TabsList,TabsTrigger } from '@/components/ui/tabs';
import type { RealEstateAsset } from '@shared/real-estate-contracts';
import { RealEstateShell } from './real-estate-shell';
import { ErpCustomFieldsEditor,type ErpFieldDefinition } from '@/components/erp/ErpCustomFieldsEditor';
import { useRealEstateAccess } from './use-real-estate-access';
import { Ownership } from './ownership';

export default function PropertyDetail({id,kind='property'}:{id:string;kind?:'property'|'unit'}){
  const {company,user}=useAuth();const {t,currentLanguage}=useTranslation();const {hasPermission}=usePermissions();const [,navigate]=useLocation();
  const section=kind==='unit'?'units':'properties';const base=`/erp/real-estate/${section}`;
  const access=useRealEstateAccess(section);
  const [imageIndex,setImageIndex]=useState(0);
 const {formatMoney}=useErpCurrencies({enabled:access.enabled&&access.financial});
  const query=useQuery<{seller:{id:number;name:string;email:string|null;customFields:Record<string,unknown>}|null;financial:{receivables:Array<{currency:string;invoices:number;billed:string;paid:string;outstanding:string}>;expenses:Array<{currency:string;records:number;amount:string}>}|null;related:Record<string,Array<any>>;data:RealEstateAsset&{property_type_name?:string;assigned_agent_name?:string;project_name?:string;building_name?:string;floor_name?:string;classifications?:Array<{id:number;name:string;kind:string;color:string|null}>};activity:Array<{action:string;created_at:string;details:Record<string,unknown>}>}>({enabled:access.enabled,queryKey:['real-estate',company?.id??user?.companyId,section,id],queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/${section}/${id}`)).json()});
  const contactFields=useQuery<{data:CompanyContactCustomField[]}>({enabled:access.enabled&&!!query.data?.seller,queryKey:['real-estate',company?.id??user?.companyId,'contact-definitions'],queryFn:async()=>(await apiRequest('GET','/api/erp/real-estate/contacts/field-definitions')).json()});
  const asset=query.data?.data;
  const definitions=useQuery<ErpFieldDefinition[]>({enabled:access.enabled,queryKey:['erp-custom-fields',company?.id??user?.companyId,kind],queryFn:async()=>(await (await apiRequest('GET',`/api/erp/custom-fields/${kind==='unit'?'real_estate_unit':'real_estate_property'}`)).json()).data});
  const fieldLabels:Record<string,string>={bedrooms:'Bedrooms',bathrooms:'Bathrooms',area:'Area',address:'Address',ownershipMode:'Ownership model'};
  return <RealEstateShell title={asset?.name??t('erp.realEstate.properties.title','Properties')} description={asset?`${asset.code} · ${asset.location??''}`:''} icon="ri-home-4-line"
    actions={<><Button variant="outline" onClick={()=>navigate(base)}>{t('erp.realEstate.backToProperties','Back to properties')}</Button>{hasPermission(`manage_real_estate_${section}`)&&<Button onClick={()=>navigate(`${base}/${id}/edit`)}>{t('common.edit','Edit')}</Button>}</>}>
    {query.isError?<div role="alert" className="re-panel p-8">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="outline" onClick={()=>query.refetch()}>{t('common.retry','Retry')}</Button></div>:!asset?<div role="status" className="re-panel h-96 animate-pulse"/>:<>
      <div className="mb-5 grid gap-4 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="min-w-0"><div className="re-panel re-property-image flex h-72 items-center justify-center sm:h-96">{asset.images[imageIndex]||asset.images[0]?<img className="h-full w-full object-cover" src={(asset.images[imageIndex]??asset.images[0]).url} alt={(asset.images[imageIndex]??asset.images[0]).alt??asset.name}/>:<div className="text-center text-muted-foreground"><i className="ri-building-4-line text-6xl opacity-40" aria-hidden="true"/><p className="mt-3 text-sm">{t('erp.realEstate.noImages','No property images yet')}</p></div>}</div>
        {asset.images.length>1&&<div className="mt-3 flex gap-2 overflow-x-auto pb-1">{asset.images.map((image,index)=><button key={`${image.url}-${index}`} className={`h-16 w-24 shrink-0 overflow-hidden rounded-lg border-2 ${index===imageIndex?'border-primary':'border-transparent'}`} aria-label={`${t('erp.realEstate.gallery','Property gallery')} ${index+1}`} aria-pressed={index===imageIndex} onClick={()=>setImageIndex(index)}><img className="h-full w-full object-cover" src={image.url} alt={image.alt??asset.name}/></button>)}</div>}</div>
        <div className="re-panel p-5"><span className={`re-status re-status-${asset.status}`}>{t(`erp.realEstate.status.${asset.status}`,asset.status)}</span><h2 className="mt-5 font-semibold">{t('erp.realEstate.propertySummary','Property summary')}</h2>
          <dl className="mt-4 space-y-4 text-sm">{[['propertyTypeId',asset.property_type_name],['assignedAgentId',asset.assigned_agent_name],['bedrooms',asset.bedrooms],['bathrooms',asset.bathrooms],['area',asset.area?`${asset.area} ${asset.area_measure==='sq_m'?'m²':'ft²'}`:null],['address',asset.address],['ownershipMode',asset.ownership_mode==='managed'?t('erp.realEstate.managed','Managed for owners'):t('erp.realEstate.companyOwned','Company owned')]].map(([key,value])=><div key={String(key)} className="flex justify-between gap-3"><dt className="text-muted-foreground">{t(`erp.realEstate.fields.${key}`,fieldLabels[String(key)]??String(key))}</dt><dd className="max-w-44 text-right">{value??'—'}</dd></div>)}</dl>
          {hasPermission('view_real_estate_financials')&&<div className="mt-5 border-t border-border pt-4"><p className="text-xs text-muted-foreground">{t('erp.realEstate.fields.rentalPrice','Monthly rent')}</p><strong className="text-2xl">{formatMoney(Number(asset.rental_price)||0,asset.currency??'USD',currentLanguage?.code)}</strong></div>}</div></div>
      {access.financial&&query.data?.financial&&<section className="re-panel mb-5 p-5"><h2 className="mb-4 font-semibold">{t('erp.realEstate.workspace.financialSummary','ERP financial summary')}</h2><div className="grid gap-4 md:grid-cols-2">{query.data.financial.receivables.map(row=><div key={row.currency} className="rounded-lg border p-4"><h3 className="text-sm font-semibold">{row.currency} · {row.invoices} {t('erp.realEstate.reports.invoices','Invoices')}</h3><dl className="mt-3 space-y-2">{(['billed','paid','outstanding'] as const).map(key=><div key={key} className="flex justify-between gap-3 text-sm"><dt className="text-muted-foreground">{t(`erp.realEstate.reports.${key}`,key)}</dt><dd>{formatMoney(Number(row[key]),row.currency,currentLanguage?.code)}</dd></div>)}</dl></div>)}{query.data.financial.expenses.map(row=><div key={'expense-'+row.currency} className="rounded-lg border p-4"><h3 className="text-sm font-semibold">{t('erp.realEstate.workspace.postedExpenses','Posted expenses')} · {row.currency}</h3><p className="mt-3 text-lg font-semibold">{formatMoney(Number(row.amount),row.currency,currentLanguage?.code)}</p></div>)}</div>{!query.data.financial.receivables.length&&!query.data.financial.expenses.length&&<p className="text-sm text-muted-foreground">{t('erp.realEstate.workspace.noFinancialRecords','No authorized issued financial records for this asset.')}</p>}</section>}
      {asset.ownership_mode==='company_owned'&&<CostSources assetId={asset.id} kind={kind}/>}
      {(!!asset.project_name||!!asset.classifications?.length)&&<section className="re-panel mb-5 p-5">{asset.project_name&&<p className="mb-4 text-sm"><i className="ri-building-line mr-2 text-primary" aria-hidden="true"/>{[asset.project_name,asset.building_name,asset.floor_name].filter(Boolean).join(' / ')}</p>}{!!asset.classifications?.length&&<><h2 className="mb-3 font-semibold">{t('erp.realEstate.workspace.features','Features and tags')}</h2><div className="flex flex-wrap gap-2">{asset.classifications.map(item=><span key={item.id} className="inline-flex max-w-full items-center gap-2 rounded-full border px-3 py-1.5 text-xs"><span aria-hidden="true" className="h-2 w-2 shrink-0 rounded-full" style={{background:item.color??'#64748b'}}/><span className="break-words">{item.name}</span></span>)}</div></>}</section>}
      {query.data?.seller&&<section className="re-panel mb-5 p-5"><h2 className="mb-3 font-semibold">{t('erp.realEstate.fields.sellerContactId','CRM seller')}</h2><p className="break-words font-medium">{query.data.seller.name}</p><p className="mt-1 break-words text-xs text-muted-foreground">{query.data.seller.email??'—'}</p><div className="mt-3">{contactFields.isError?<p role="alert" className="text-sm text-muted-foreground">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="ghost" size="sm" onClick={()=>contactFields.refetch()}>{t('common.retry','Retry')}</Button></p>:<ContactCustomFieldsBadges customFields={query.data.seller.customFields} schema={contactFields.data?.data??[]} maxVisible={6}/>}</div></section>}
      <Tabs defaultValue="overview"><div className="overflow-x-auto"><TabsList className="mb-4"><TabsTrigger value="overview">{t('erp.realEstate.overview','Overview')}</TabsTrigger><TabsTrigger value="activity">{t('erp.realEstate.activity','Activity')}</TabsTrigger>{Object.keys(query.data?.related??{}).map(feature=><TabsTrigger key={feature} value={feature}>{t(`erp.realEstate.${feature}.title`,feature)}</TabsTrigger>)}<TabsTrigger value="additional">{t('erp.realEstate.editor.customFields','Additional information')}</TabsTrigger></TabsList></div>
        <TabsContent value="overview"><div className="re-panel p-5"><h2 className="mb-3 font-semibold">{t('erp.realEstate.fields.description','Description')}</h2><p className="whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{asset.description||t('erp.realEstate.noDescription','No description has been added.')}</p></div></TabsContent>
        <TabsContent value="activity"><div className="re-panel p-5">{query.data!.activity.map((item,index)=><div key={index} className="flex items-center gap-3 border-b border-border py-3 last:border-0"><i className="ri-history-line text-primary"/><div><p className="text-sm">{t(`erp.realEstate.actions.${item.action}`,item.action)}</p><time className="text-xs text-muted-foreground">{new Intl.DateTimeFormat(currentLanguage?.code,{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.created_at))}</time></div></div>)}</div></TabsContent>
        <TabsContent value="additional"><div className="re-panel p-5">{definitions.data?.some(field=>field.isActive)?<ErpCustomFieldsEditor definitions={definitions.data} values={asset.custom_fields} onChange={()=>{}} disabled/>:<p className="text-sm text-muted-foreground">{t('erp.realEstate.noCustomFields','Configure custom fields for this record type in ERP Settings.')}</p>}</div></TabsContent>
        {Object.entries(query.data?.related??{}).map(([feature,records])=><TabsContent key={feature} value={feature}><section className="re-panel p-5"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="font-semibold">{t(`erp.realEstate.${feature}.title`,feature)}</h2><Button asChild size="sm" variant="outline"><Link href={`/erp/real-estate/${feature}`}>{t('erp.realEstate.dashboard.viewAll','View All')}</Link></Button></div>{records.length?<div className="space-y-3">{records.map(record=><a key={record.id} target={feature==='documents'?'_blank':undefined} rel={feature==='documents'?'noreferrer':undefined} href={feature==='documents'?`/api/erp/real-estate/documents/${record.id}/download`:feature==='schedule'?'/erp/real-estate/schedule':`/erp/real-estate/${feature}/${record.id}`} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4 text-sm"><div><h3 className="font-medium">{record.name??record.title??`${t('erp.realEstate.reservations.title','Reservations')} #${record.id}`}</h3>{record.contact_name&&<p className="mt-1 text-xs text-muted-foreground">{record.contact_name}</p>}</div>{record.status&&<span className="re-status">{t(`erp.realEstate.${feature==='reservations'?'reservationStatus':feature==='leases'?'leasesStatus':feature==='schedule'?'schedule.status':'maintenanceStatus'}.${record.status}`,record.status)}</span>}{record.category&&<span className="text-xs text-muted-foreground">{record.category}</span>}</a>)}</div>:<p className="py-8 text-center text-sm text-muted-foreground">{t('erp.realEstate.operations.empty','No records match this view')}</p>}</section></TabsContent>)}
      </Tabs>
      {asset.ownership_mode==='managed'&&<div className="mt-5"><Ownership assetId={asset.id} canManageAsset={access.canManage}/></div>}
    </>}
  </RealEstateShell>;
}
