import { useEffect,useState } from 'react';
import { useLocation } from 'wouter';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/hooks/use-auth';
import { useTranslation } from '@/hooks/use-translation';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { ErpCustomFieldsEditor,type ErpFieldDefinition } from '@/components/erp/ErpCustomFieldsEditor';
import { RealEstateShell } from './real-estate-shell';
import type { RealEstateAsset } from '@shared/real-estate-contracts';
import { useRealEstateAccess } from './use-real-estate-access';
import { ImageUploadDialog } from '@/components/ui/image-upload-dialog';
import type { RealEstateHierarchy } from '@shared/real-estate-projects';

type Seller={id:number;name:string};
type Context={currencies:Array<{code:string;name:string}>;taxonomy:Array<{id:number;kind:string;name:string}>;agents:Array<{id:number;name:string}>;baseCurrency:string|null};
export default function PropertyEditor({id,kind='property'}:{id?:string;kind?:'property'|'unit'}) {
  const {company,user}=useAuth(); const {t}=useTranslation(); const {toast}=useToast(); const [,navigate]=useLocation(); const cache=useQueryClient();
  const companyId=company?.id??user?.companyId; const section=kind==='unit'?'units':'properties'; const base=`/erp/real-estate/${section}`;
  const access=useRealEstateAccess(section);
  const [imageDialogOpen,setImageDialogOpen]=useState(false);
  const [contactSearch,setContactSearch]=useState('');
  const contacts=useQuery<{data:Array<{id:number;name:string}>}>({enabled:access.enabled&&access.canManage,queryKey:['real-estate',companyId,'asset-contact-search',contactSearch],queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/contacts/search?search=${encodeURIComponent(contactSearch)}`)).json()});
  const hierarchy=useQuery<RealEstateHierarchy&{projects:Array<{id:number;name:string}>}>({enabled:kind==='unit'&&access.enabled&&access.canManage,queryKey:['real-estate',companyId,'hierarchy'],queryFn:async()=>(await apiRequest('GET','/api/erp/real-estate/hierarchy')).json()});
  const [form,setForm]=useState<Record<string,any>>(()=>{const params=new URLSearchParams(window.location.search);return {kind,code:'',name:'',location:'',address:'',description:'',bedrooms:'',bathrooms:'',area:'',areaMeasure:'sq_ft',ownershipMode:'company_owned',listingPurpose:kind==='unit'?'sale':'rent',status:'available',currency:'',salePrice:'',rentalPrice:'',sellerContactId:null,images:[],customFields:{},tagIds:[],...(kind==='unit'?{projectId:params.get('projectId')?Number(params.get('projectId')):null,buildingId:params.get('buildingId')?Number(params.get('buildingId')):null,floorId:params.get('floorId')?Number(params.get('floorId')):null}:{})};});
  const context=useQuery<Context>({enabled:access.enabled&&access.canManage,queryKey:['real-estate',companyId,'context'],queryFn:async()=>(await apiRequest('GET','/api/erp/real-estate/context')).json()});
  const entity=kind==='unit'?'real_estate_unit':'real_estate_property';
  const definitions=useQuery<ErpFieldDefinition[]>({enabled:access.enabled&&access.canManage,queryKey:['erp-custom-fields',companyId,entity],queryFn:async()=>(await (await apiRequest('GET',`/api/erp/custom-fields/${entity}`)).json()).data});
  const record=useQuery<{data:RealEstateAsset;seller:Seller|null}>({queryKey:['real-estate',companyId,section,id],enabled:!!id&&access.enabled&&access.canManage,queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/${section}/${id}`)).json()});
  useEffect(()=>{if(!id&&context.data?.baseCurrency)setForm(prior=>({...prior,currency:prior.currency||context.data!.baseCurrency}));},[context.data,id]);
  useEffect(()=>{if(record.data){const a=record.data.data;setForm({kind:a.kind,code:a.code,name:a.name,location:a.location??'',address:a.address??'',description:a.description??'',bedrooms:a.bedrooms??'',bathrooms:a.bathrooms??'',area:a.area??'',areaMeasure:a.area_measure,ownershipMode:a.ownership_mode,listingPurpose:a.listing_purpose,status:a.status,currency:a.currency??'',salePrice:a.sale_price??'',rentalPrice:a.rental_price??'',propertyTypeId:a.property_type_id,assignedAgentId:a.assigned_agent_id,sellerContactId:a.seller_contact_id??null,projectId:a.project_id,buildingId:a.building_id,floorId:a.floor_id,images:a.images,customFields:a.custom_fields,tagIds:a.tag_ids??[]});}},[record.data]);
  const save=useMutation({mutationFn:async()=>{
    const payload:Record<string,any>={...form,bedrooms:form.bedrooms===''?null:Number(form.bedrooms),bathrooms:form.bathrooms===''?null:Number(form.bathrooms),area:form.area||null,salePrice:form.salePrice||null,rentalPrice:form.rentalPrice||null};
    if(id){payload.version=record.data!.data.version;if((form.sellerContactId??null)===(record.data!.data.seller_contact_id??null))delete payload.sellerContactId;}
    if(id&&!access.financial){delete payload.currency;delete payload.salePrice;delete payload.rentalPrice;}
    return (await (await apiRequest(id?'PATCH':'POST',id?`/api/erp/real-estate/${section}/${id}`:`/api/erp/real-estate/${section}`,payload)).json()).data;
  },onSuccess:data=>{cache.invalidateQueries({queryKey:['real-estate',companyId]});toast({title:t('erp.common.saved','Saved')});navigate(`${base}/${data.id}`);},onError:(error:Error)=>toast({title:t('common.error','Error'),description:error.message,variant:'destructive'})});
  const field=(key:string,label:string,type='text')=><div className="space-y-2"><Label htmlFor={`re-${key}`}>{t(`erp.realEstate.fields.${key}`,label)}</Label><Input id={`re-${key}`} type={type} value={form[key]??''} onChange={event=>setForm({...form,[key]:event.target.value})} /></div>;
  const select=(key:string,label:string,options:Array<{value:string;label:string}>)=><div className="space-y-2"><Label htmlFor={`re-${key}`}>{t(`erp.realEstate.fields.${key}`,label)}</Label><Select value={String(form[key]??'__none__')} onValueChange={value=>setForm({...form,[key]:value==='__none__'?null:key.endsWith('Id')?Number(value):value,...(key==='projectId'?{buildingId:null,floorId:null}:key==='buildingId'?{floorId:null}:{})})}><SelectTrigger id={`re-${key}`}><SelectValue /></SelectTrigger><SelectContent>{options.map(option=><SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select></div>;
  const ready=!!context.data&&!!definitions.data&&(!id||!!record.data);
  const taxonomy=[...(context.data?.taxonomy??[]),...(record.data?.data.classifications??[]).filter(item=>!context.data?.taxonomy.some(active=>active.id===item.id))];
  const previousType=record.data?.data;
  if(previousType?.property_type_id&&!taxonomy.some(item=>item.id===previousType.property_type_id))taxonomy.push({id:previousType.property_type_id,kind:'property_type',name:previousType.property_type_name??String(previousType.property_type_id)});
  const classificationName=(item:{id:number;name:string})=>context.data?.taxonomy.some(active=>active.id===item.id)?item.name:`${item.name} · ${t('erp.realEstate.taxonomy.inactive','Inactive')}`;
  return <RealEstateShell title={t(kind==='unit'?(id?'erp.realEstate.units.edit':'erp.realEstate.units.add'):(id?'erp.realEstate.properties.edit':'erp.realEstate.properties.add'),id?'Edit property':'Add property')} description={t('erp.realEstate.properties.editorDescription','Create a clear property record, then manage its operations from the workspace.')} icon="ri-home-4-line"
    actions={<><Button variant="outline" onClick={()=>navigate(id?`${base}/${id}`:base)}>{t('common.cancel','Cancel')}</Button><Button disabled={!access.canManage||!ready||save.isPending||!form.name||!form.code||(!id&&!form.currency)} onClick={()=>save.mutate()}>{save.isPending?t('erp.common.saving','Saving…'):t('erp.common.save','Save')}</Button></>}>
    {context.isError||definitions.isError||record.isError?<div className="re-panel p-8" role="alert">{t('erp.realEstate.loadError','Unable to load this information.')}<Button className="ml-3" variant="outline" onClick={()=>{context.refetch();definitions.refetch();if(id)record.refetch();}}>{t('common.retry','Retry')}</Button></div>:!ready?<div className="re-panel h-80 animate-pulse" role="status"/>:<div className="grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_320px]">
      <div className="space-y-4">{kind==='unit'&&<section className="re-form-section"><h2>{t('erp.realEstate.unitHierarchy','Project inventory')}</h2><div className="grid gap-4 sm:grid-cols-3">
        {select('projectId','Project',[{value:'__none__',label:t('erp.common.none','None')},...(hierarchy.data?.projects??[]).map(project=>({value:String(project.id),label:project.name}))])}
        {select('buildingId','Building / tower',[{value:'__none__',label:t('erp.common.none','None')},...(hierarchy.data?.buildings??[]).filter(building=>building.project_id===form.projectId).map(building=>({value:String(building.id),label:building.name}))])}
        {select('floorId','Floor',[{value:'__none__',label:t('erp.common.none','None')},...(hierarchy.data?.floors??[]).filter(floor=>floor.building_id===form.buildingId).map(floor=>({value:String(floor.id),label:floor.name}))])}
      </div></section>}<section className="re-form-section"><h2>{t('erp.realEstate.editor.identity','Property identity')}</h2><div className="grid gap-4 sm:grid-cols-2">{field('name','Property name')}{field('code','Reference code')}
        {select('propertyTypeId','Property type',[{value:'__none__',label:t('erp.common.none','None')},...taxonomy.filter(item=>item.kind==='property_type').map(item=>({value:String(item.id),label:classificationName(item)}))])}
        {select('listingPurpose','Listing purpose',['rent','sale','both'].map(value=>({value,label:t(`erp.realEstate.purpose.${value}`,value==='both'?'Rent and sale':value==='rent'?'For rent':'For sale')})))}
        {field('location','Location')}{field('address','Address')}</div><div className="mt-4 space-y-2"><Label htmlFor="re-description">{t('erp.realEstate.fields.description','Description')}</Label><Textarea id="re-description" rows={4} value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></div></section>
      <section className="re-form-section"><h2>{t('erp.realEstate.editor.characteristics','Key characteristics')}</h2><div className="grid gap-4 sm:grid-cols-2">{field('bedrooms','Bedrooms','number')}{field('bathrooms','Bathrooms','number')}{field('area','Area','number')}{select('areaMeasure','Area measurement',[{value:'sq_ft',label:'ft²'},{value:'sq_m',label:'m²'}])}</div></section>
      <section className="re-form-section"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="!mb-0">{t('erp.realEstate.gallery','Property gallery')}</h2><Button variant="outline" size="sm" disabled={form.images.length>=40} onClick={()=>setImageDialogOpen(true)}>{t('erp.realEstate.addImage','Add image')}</Button></div>
        {form.images.length?<div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{form.images.map((image:{url:string;alt?:string},index:number)=><div key={`${image.url}-${index}`} className="re-panel"><img src={image.url} alt={image.alt||form.name} className="h-28 w-full object-cover"/><div className="flex justify-between gap-1 p-2"><Button size="sm" variant="ghost" disabled={index===0} onClick={()=>setForm({...form,images:[image,...form.images.filter((_:unknown,i:number)=>i!==index)]})}>{index===0?t('erp.realEstate.cover','Cover'):t('erp.realEstate.makeCover','Set cover')}</Button><Button size="icon" variant="ghost" aria-label={t('erp.realEstate.removeImage','Remove image')} onClick={()=>setForm({...form,images:form.images.filter((_:unknown,i:number)=>i!==index)})}><i className="ri-close-line" aria-hidden="true"/></Button></div></div>)}</div>:<p className="text-sm text-muted-foreground">{t('erp.realEstate.noImages','No property images yet')}</p>}
      </section>
      <section className="re-form-section"><h2>{t('erp.realEstate.workspace.features','Features and tags')}</h2>{taxonomy.some(item=>['feature','tag'].includes(item.kind))?<div className="grid gap-3 sm:grid-cols-2">{taxonomy.filter(item=>['feature','tag'].includes(item.kind)).map(item=><label key={item.id} className="flex cursor-pointer items-start gap-3 rounded-lg border p-3 text-sm"><Checkbox checked={form.tagIds.includes(item.id)} onCheckedChange={checked=>setForm({...form,tagIds:checked?[...new Set([...form.tagIds,item.id])]:form.tagIds.filter((value:number)=>value!==item.id)})}/><span className="min-w-0 break-words">{classificationName(item)}</span></label>)}</div>:<p className="text-sm text-muted-foreground">{t('erp.realEstate.taxonomy.empty','No classifications yet')}</p>}</section>
      <section className="re-form-section"><h2>{t('erp.realEstate.editor.customFields','Additional information')}</h2>{definitions.data.length?<ErpCustomFieldsEditor definitions={definitions.data} values={form.customFields} onChange={values=>setForm({...form,customFields:values})}/>:<p className="text-sm text-muted-foreground">{t('erp.realEstate.noCustomFields','Configure custom fields for this record type in ERP Settings.')}</p>}</section></div>
      <div className="space-y-4">{access.financial&&<section className="re-form-section"><h2>{t('erp.realEstate.editor.pricing','Pricing')}</h2><div className="space-y-4">{select('currency','ERP currency',context.data.currencies.map(currency=>({value:currency.code,label:`${currency.code} · ${currency.name}`})))}{form.listingPurpose!=='rent'&&field('salePrice','Sale price','number')}{form.listingPurpose!=='sale'&&field('rentalPrice','Monthly rent','number')}</div></section>}
      <section className="re-form-section"><h2>{t('erp.realEstate.editor.management','Management')}</h2><div className="space-y-4">{select('ownershipMode','Ownership model',[{value:'company_owned',label:t('erp.realEstate.companyOwned','Company owned')},{value:'managed',label:t('erp.realEstate.managed','Managed for owners')}])}
        {select('assignedAgentId','Assigned agent',[{value:'__none__',label:t('erp.common.none','None')},...context.data.agents.map(agent=>({value:String(agent.id),label:agent.name}))])}
        <div className="space-y-2"><Label htmlFor="re-seller">{t('erp.realEstate.fields.sellerContactId','CRM seller')}</Label><Input aria-label={t('erp.realEstate.contacts.searchCrm','Search CRM contacts')} value={contactSearch} onChange={event=>setContactSearch(event.target.value)}/><Select value={String(form.sellerContactId??'none')} onValueChange={value=>setForm({...form,sellerContactId:value==='none'?null:Number(value)})}><SelectTrigger id="re-seller"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">{t('erp.common.none','None')}</SelectItem>{[...(contacts.data?.data??[]),...(record.data?.seller&&!contacts.data?.data.some(contact=>contact.id===record.data!.seller!.id)?[record.data.seller]:[])].map(contact=><SelectItem key={contact.id} value={String(contact.id)}>{contact.name}</SelectItem>)}</SelectContent></Select>{contacts.isError&&<p role="alert" className="text-xs text-destructive">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="ghost" size="sm" onClick={()=>contacts.refetch()}>{t('common.retry','Retry')}</Button></p>}<p className="text-xs text-muted-foreground">{t('erp.realEstate.sellerGuidance','Link the existing CRM seller. Ownership shares remain separate.')}</p></div>
        {!['rented','reserved','sold'].includes(form.status)&&select('status','Availability',['available','occupied','blocked'].map(value=>({value,label:t(`erp.realEstate.status.${value}`,value)})))}</div></section></div>
    </div>}
    <ImageUploadDialog isOpen={imageDialogOpen} onClose={()=>setImageDialogOpen(false)} uploadUrl="/api/erp/real-estate/images/upload" allowUrlInput={false} onImageInsert={(url,alt)=>setForm(prior=>({...prior,images:[...prior.images,{url,alt}]}))}/>
  </RealEstateShell>;
}
