import {AutomaticReminderSettings} from '@/components/erp/dental/AutomaticReminderSettings';
import {defaultDentalAutomaticReminders,type DentalAutomaticReminders} from '@shared/types/dental-reminder-types';
import {useEffect,useState} from 'react';
import {Link} from 'wouter';
import {useQuery,useMutation} from '@tanstack/react-query';
import {useTranslation} from '@/hooks/use-translation';
import {usePermissions} from '@/hooks/usePermissions';
import {useToast} from '@/hooks/use-toast';
import {apiRequest} from '@/lib/queryClient';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {RealEstateShell} from './real-estate-shell';
import {useRealEstateAccess} from './use-real-estate-access';
import {TaxonomySettings} from './taxonomy-settings';
export default function RealEstateSettings(){
 const access=useRealEstateAccess('settings'),{t}=useTranslation(),{hasAnyPermission}=usePermissions(),{toast}=useToast(),[reminders,setReminders]=useState<DentalAutomaticReminders>(defaultDentalAutomaticReminders),[hours,setHours]=useState('48'),[buffer,setBuffer]=useState('0');
 const query=useQuery<{data:{reservationExpiryHours:number;scheduleBufferMinutes:number;automaticReminders:DentalAutomaticReminders}}>({enabled:access.enabled,queryKey:['real-estate',access.companyId,'settings'],queryFn:async()=>(await apiRequest('GET','/api/erp/real-estate/settings')).json()});
 useEffect(()=>{if(query.data){setReminders(query.data.data.automaticReminders);setHours(String(query.data.data.reservationExpiryHours));setBuffer(String(query.data.data.scheduleBufferMinutes));}},[query.data]);
 const save=useMutation({mutationFn:async()=>apiRequest('PUT','/api/erp/real-estate/settings',{reservationExpiryHours:Number(hours),scheduleBufferMinutes:Number(buffer),automaticReminders:reminders}),onSuccess:()=>{query.refetch();toast({title:t('erp.common.saved','Saved')});},onError:(e:Error)=>toast({title:t('common.error','Error'),description:e.message,variant:'destructive'})});
 return <RealEstateShell title={t('erp.realEstate.settings.title','Real Estate Settings')} description={t('erp.realEstate.settings.description','Configure Real Estate behavior using existing ERP services.')} icon="ri-settings-3-line">
 {query.isError?<div role="alert" className="re-panel p-8">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="outline" onClick={()=>query.refetch()}>{t('common.retry','Retry')}</Button></div>:query.isLoading?<div role="status" className="re-panel h-48 animate-pulse"/>:<div className="grid items-start gap-4 lg:grid-cols-2"><section className="re-form-section"><h2>{t('erp.realEstate.settings.reservationPolicy','Reservation policy')}</h2><div className="space-y-2"><Label htmlFor="reservation-expiry">{t('erp.realEstate.settings.expiryHours','Reservation expiry (hours)')}</Label><Input id="reservation-expiry" type="number" min="1" max="720" disabled={!access.canManage} value={hours} onChange={e=>setHours(e.target.value)}/><p className="text-xs text-muted-foreground">{t('erp.realEstate.settings.expiryDescription','Applies to new holds. Existing reservations retain their recorded expiry time.')}</p></div><div className="mt-5 space-y-2"><Label htmlFor="schedule-buffer">{t('erp.realEstate.settings.scheduleBuffer','Appointment buffer (minutes)')}</Label><Input id="schedule-buffer" type="number" min="0" max="120" disabled={!access.canManage} value={buffer} onChange={e=>setBuffer(e.target.value)}/><p className="text-xs text-muted-foreground">{t('erp.realEstate.settings.scheduleHours','Agent working hours and breaks use existing agent availability settings.')}</p></div>{access.canManage&&<Button className="mt-5" disabled={save.isPending||Number(hours)<1||Number(hours)>720} onClick={()=>save.mutate()}>{t('erp.common.save','Save')}</Button>}</section><section className="re-panel p-5"><h2 className="font-semibold">{t('erp.realEstate.settings.sharedConfiguration','Shared ERP configuration')}</h2><p className="mt-2 text-sm text-muted-foreground">{t('erp.realEstate.settings.sharedDescription','Custom fields, currencies, exchange rates, taxes and payment gateways are managed in ERP Settings. People and their custom fields remain in CRM Contacts. Billable products and services remain in the Catalog.')}</p><div className="mt-5 flex flex-wrap gap-2">{hasAnyPermission(['view_erp_settings','manage_erp_settings'])&&<Button asChild variant="outline"><Link href="/erp/settings">{t('erp.settings.title','ERP Settings')}</Link></Button>}{hasAnyPermission(['view_products','manage_products'])&&<Button asChild variant="outline"><Link href="/erp/products">{t('erp.realEstate.settings.catalog','ERP Catalog')}</Link></Button>}</div></section><section className="re-panel min-w-0 p-5 lg:col-span-2"><AutomaticReminderSettings value={reminders} onChange={setReminders} disabled={!access.canManage || save.isPending} domain="real_estate" historyEnabled={hasAnyPermission(['view_real_estate_schedule','manage_real_estate_schedule'])}/>{access.canManage&&<Button className="mt-5" disabled={save.isPending||query.isFetching} onClick={()=>save.mutate()}>{t('erp.common.save','Save')}</Button>}</section><TaxonomySettings/></div>}
 </RealEstateShell>;
}
