import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {apiRequest} from '@/lib/queryClient';
import {useTranslation} from '@/hooks/use-translation';
import {useToast} from '@/hooks/use-toast';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {useRealEstateAccess} from './use-real-estate-access';
type Taxonomy={id:number;kind:'property_type'|'feature'|'tag';name:string;color:string|null;is_active:boolean};
export function TaxonomySettings(){
 const access=useRealEstateAccess('settings'),{t}=useTranslation(),{toast}=useToast(),cache=useQueryClient();
 const [open,setOpen]=useState(false),[editing,setEditing]=useState<Taxonomy|null>(null),[name,setName]=useState(''),[kind,setKind]=useState<Taxonomy['kind']>('property_type'),[color,setColor]=useState('#64748b');
 const label=(key:string,fallback:string)=>t(`erp.realEstate.taxonomy.${key}`,fallback);
 const query=useQuery<{data:Taxonomy[]}>({enabled:access.enabled,queryKey:['real-estate',access.companyId,'taxonomy'],queryFn:async()=>(await apiRequest('GET','/api/erp/real-estate/taxonomy')).json()});
 const mutation=useMutation({mutationFn:async({row,active}:{row?:Taxonomy;active?:boolean}={})=>{
  const source=row??editing;
  return source?apiRequest('PATCH',`/api/erp/real-estate/taxonomy/${source.id}`,{name:row?row.name:name,color:row?row.color:color,isActive:active??source.is_active,expectedName:source.name,expectedActive:source.is_active,expectedColor:source.color}):apiRequest('POST','/api/erp/real-estate/taxonomy',{kind,name,color});
 },onSuccess:()=>{cache.invalidateQueries({queryKey:['real-estate',access.companyId]});setOpen(false);toast({title:t('erp.common.saved','Saved')});},onError:(e:Error)=>toast({title:t('common.error','Error'),description:e.message,variant:'destructive'})});
 return <section className="re-panel p-5 lg:col-span-2"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">{label('title','Property types, features and tags')}</h2>{access.canManage&&<Button variant="outline" onClick={()=>{setEditing(null);setName('');setKind('property_type');setColor('#64748b');setOpen(true);}}>{label('add','Add classification')}</Button>}</div><p className="mt-2 text-sm text-muted-foreground">{label('help','Classify Real Estate assets within this company. Deactivated classifications remain on existing records and are unavailable for new assignments.')}</p>
 {query.isError?<div role="alert" className="mt-5">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="outline" onClick={()=>query.refetch()}>{t('common.retry','Retry')}</Button></div>:query.isLoading?<div role="status" className="mt-5 h-24 animate-pulse"/>:<div className="mt-5 grid items-start gap-4 md:grid-cols-3">{(['property_type','feature','tag'] as const).map(k=><section key={k} className="min-w-0 rounded-xl border p-4"><h3 className="mb-3 text-sm font-semibold">{label(k,k)}</h3>{!query.data?.data.some(r=>r.kind===k)&&<p className="py-4 text-xs text-muted-foreground">{label('empty','No classifications yet')}</p>}{query.data?.data.filter(r=>r.kind===k).map(row=><article key={row.id} className="border-b border-border/50 py-3 last:border-0"><div className="flex items-start gap-2"><span aria-hidden="true" className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full" style={{background:row.color??'#64748b'}}/><strong className="min-w-0 break-words text-sm">{row.name}</strong></div>{!row.is_active&&<p className="mt-1 text-xs text-muted-foreground">{label('inactive','Inactive')}</p>}{access.canManage&&<div className="mt-2 flex flex-wrap gap-2"><Button size="sm" variant="ghost" disabled={mutation.isPending} onClick={()=>{setEditing(row);setName(row.name);setKind(row.kind);setColor(row.color??'#64748b');setOpen(true);}}>{t('common.edit','Edit')}</Button><Button size="sm" variant="ghost" disabled={mutation.isPending} onClick={()=>mutation.mutate({row,active:!row.is_active})}>{row.is_active?label('deactivate','Deactivate'):label('activate','Activate')}</Button></div>}</article>)}</section>)}</div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing?label('edit','Edit classification'):label('add','Add classification')}</DialogTitle><DialogDescription>{label('dialogHelp','Use domain-specific names such as Apartment, Sea View or Furnished. Catalog categories and units remain separate.')}</DialogDescription></DialogHeader><div className="space-y-4">{!editing&&<div className="space-y-2"><Label>{label('kind','Classification kind')}</Label><Select value={kind} onValueChange={v=>setKind(v as Taxonomy['kind'])}><SelectTrigger aria-label={label('kind','Classification kind')}><SelectValue/></SelectTrigger><SelectContent>{(['property_type','feature','tag'] as const).map(k=><SelectItem key={k} value={k}>{label(k,k)}</SelectItem>)}</SelectContent></Select></div>}<div className="space-y-2"><Label htmlFor="taxonomy-name">{label('name','Classification name')}</Label><Input id="taxonomy-name" maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></div><div className="space-y-2"><Label htmlFor="taxonomy-color">{label('color','Display color')}</Label><Input id="taxonomy-color" type="color" value={color} onChange={e=>setColor(e.target.value)}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>{t('common.cancel','Cancel')}</Button><Button disabled={mutation.isPending||!name.trim()} onClick={()=>mutation.mutate({})}>{t('erp.common.save','Save')}</Button></DialogFooter></DialogContent></Dialog>
 </section>;
}
