// Contact mapping strategies
export enum ContactMappingStrategy {
  EXTRACT = "extract", // Extract from payload field
  CREATE = "create", // Create new contact
  SYSTEM = "system" // System-level (no contact)
}

export interface ContactMappingConfig {
  strategy: ContactMappingStrategy;
  extractField?: string; // JSONPath or dot notation (e.g., 'customer.email', 'phone')
  createFields?: {
    // Fields to use when creating new contact
    nameField?: string;
    emailField?: string;
    phoneField?: string;
    additionalFields?: Record<string, string>;
  };
}

// Filter conditions
export enum FilterOperator {
  EQUALS = "equals",
  NOT_EQUALS = "not_equals",
  CONTAINS = "contains",
  NOT_CONTAINS = "not_contains",
  STARTS_WITH = "starts_with",
  ENDS_WITH = "ends_with",
  GREATER_THAN = "greater_than",
  LESS_THAN = "less_than",
  EXISTS = "exists",
  NOT_EXISTS = "not_exists",
  IN = "in",
  NOT_IN = "not_in"
}

export interface FilterCondition {
  fieldPath: string; // JSONPath or dot notation (e.g., 'event_type', 'order.status')
  operator: FilterOperator;
  value?: unknown; // Value to compare against (not needed for exists/not_exists)
  caseSensitive?: boolean; // For string comparisons
}

// Response configuration
export enum ResponseMode {
  SYNC = "sync", // Wait for flow completion
  ASYNC = "async" // Return immediately
}

export interface ResponseConfig {
  statusCode: number; // HTTP status code (default: 200)
  bodyTemplate: string; // Response body with variable interpolation
  headers?: Record<string, string>;
  mode: ResponseMode;
  timeout?: number; // Timeout for sync mode (default: 30000ms)
}

// Webhook trigger configuration
export interface WebhookTriggerConfig {
  flowId: number;
  nodeId: string;
  companyId: number;
  webhookToken: string;
  customPath?: string;
  isActive: boolean;
  filterConditions: FilterCondition[];
  contactMapping: ContactMappingConfig;
  responseConfig: ResponseConfig;
  metadata?: Record<string, unknown>;
}

// Webhook payload structure
export interface WebhookPayload {
  body: unknown; // Parsed JSON body or form data
  headers: Record<string, string>;
  queryParams: Record<string, string>;
  method: string;
  path: string;
  ipAddress?: string;
  userAgent?: string;
}

// Filter evaluation result
export interface FilterEvaluationResult {
  passed: boolean;
  evaluatedConditions: Array<{
    condition: FilterCondition;
    result: boolean;
    actualValue?: unknown;
    reason?: string;
  }>;
}

// Webhook trigger execution context
export interface WebhookTriggerContext {
  triggerId: number;
  requestId: string;
  payload: WebhookPayload;
  filterResult?: FilterEvaluationResult;
  contactId?: number;
  conversationId?: number;
  variables: Record<string, unknown>; // Variables extracted from payload
}

export interface WebhookUrlConfig {
  autoGeneratedUrl: string; // /api/webhook/trigger/{flowId}/{token}
  customUrl?: string; // /api/webhook/trigger/{customPath}
  activeUrl: string; // The URL currently in use
}

export interface WebhookTriggerValidation {
  isValid: boolean;
  errors: Array<{
    field: string;
    message: string;
  }>;
}

export interface WebhookTestPayload {
  sampleData: unknown;
  expectedContact?: {
    email?: string;
    phone?: string;
    name?: string;
  };
  expectedFilters?: boolean;
}
