import { useTranslation } from '@/hooks/use-translation';

export const batchCopy = {
  title: ['Reminders', 'Recordatorios'],
  description: ['Schedule appointment reminders and confirmation requests for your clinic.', 'Programa recordatorios de citas y solicitudes de confirmación para tu clínica.'],
  editorDescription: ['Schedule appointment reminders and confirmation requests.', 'Programa recordatorios de citas y solicitudes de confirmación.'],
  scheduleOverview: ['Schedule overview', 'Resumen de la programación'],
  scheduleForm: ['Schedule form', 'Formulario de programación'],
  messagePreview: ['Message preview', 'Vista previa del mensaje'], sampleData: ['Sample data', 'Datos de ejemplo'],
  calendarDays: ['Calendar days', 'Días calendario'],
  oneDayBefore: ['1 calendar day before the appointment', '1 día calendario antes de la cita'],
  calendarDaysBefore: ['{{days}} calendar days before the appointment', '{{days}} días calendario antes de la cita'],
  schedules: ['Schedules', 'Programaciones'], activity: ['Activity', 'Actividad'],
  new: ['New schedule', 'Nueva programación'], edit: ['Edit schedule', 'Editar programación'],
  back: ['Back', 'Volver'], close: ['Close', 'Cerrar'], cancel: ['Cancel batch', 'Cancelar envío'],
  pause: ['Pause', 'Pausar'], resume: ['Resume', 'Reanudar'],
  delete: ['Delete batch', 'Eliminar envío'],
  deleteConfirm: ['Permanently delete this batch and all its activity history?', '¿Eliminar permanentemente este envío y todo su historial de actividad?'],
  keepBatch: ['Keep batch', 'Conservar envío'],
  deletePermanently: ['Delete permanently', 'Eliminar permanentemente'],
  deleting: ['Deleting…', 'Eliminando…'],
  deleted: ['Batch deleted', 'Envío eliminado'],
  save: ['Save schedule', 'Guardar programación'], saving: ['Saving…', 'Guardando…'],
  review: ['Preview recipients', 'Previsualizar destinatarios'],
  saved: ['Schedule saved', 'Programación guardada'], updated: ['Schedule updated', 'Programación actualizada'],
  loading: ['Loading…', 'Cargando…'], retry: ['Retry', 'Reintentar'],
  error: ['Unable to load reminder schedules. Please retry.', 'No se pudieron cargar las programaciones. Inténtalo de nuevo.'],
  empty: ['Set up your first reminder schedule', 'Configura tu primera programación'],
  emptyHelp: ['Reach patients with appointments on the same day in one scheduled batch.', 'Contacta a los pacientes con citas en la misma fecha mediante un envío programado.'],
  noActivity: ['No batches have run yet.', 'Todavía no se han realizado envíos.'],
  independent: ['Appointment-relative reminders are also enabled. Patients may receive both types of messages.', 'Los recordatorios previos a cada cita también están activados. Los pacientes pueden recibir ambos tipos de mensajes.'],
  schedule: ['Schedule', 'Programación'], recipients: ['Recipients', 'Destinatarios'], messageSection: ['Message', 'Mensaje'],
  name: ['Schedule name', 'Nombre de la programación'], purpose: ['Message purpose', 'Propósito del mensaje'],
  reminder: ['Appointment reminder', 'Recordatorio de cita'], confirmation: ['Confirmation request', 'Solicitud de confirmación'],
  mode: ['Frequency', 'Frecuencia'], daily: ['Every day', 'Todos los días'], once: ['One-time batch', 'Envío único'],
  time: ['Send at', 'Enviar a las'], daysAhead: ['Days before the appointment date', 'Días antes de la fecha de la cita'],
  sendTime: ['Send time', 'Hora de envío'], sameDay: ['Same day', 'El mismo día'],
  oneDayAhead: ['1 calendar day ahead', '1 día calendario después'],
  calendarDaysAhead: ['{{days}} calendar days ahead', '{{days}} días calendario después'],
  schedulePaused: ['Schedule paused', 'Programación pausada'],
  calendarDaysHelp: ['Calendar days before the appointment date.', 'Días calendario antes de la fecha de la cita.'],
  scheduleSummary: ['Schedule summary', 'Resumen de la programación'],
  dailyTiming: ['Every day at {{time}}', 'Todos los días a las {{time}}'],
  onceTiming: ['{{date}} at {{time}}', '{{date}} a las {{time}}'],
  targetDateSummary: ['For appointments on {{date}}.', 'Para citas del {{date}}.'],
  targetDaysSummary: ['For appointments: {{days}}.', 'Para citas: {{days}}.'],
  messageOtherChannels: ['Message for other channels', 'Mensaje para otros canales'],
  excludesOfficial: ['Excludes WhatsApp Official', 'No incluye WhatsApp Official'],
  sendDate: ['Send date', 'Fecha de envío'], appointmentDate: ['Appointment date', 'Fecha de las citas'],
  provider: ['Provider', 'Profesional'], office: ['Office', 'Consultorio'], service: ['Service', 'Servicio'], status: ['Appointment status', 'Estado de la cita'],
  allProviders: ['All providers', 'Todos los profesionales'], allOffices: ['All offices', 'Todos los consultorios'], allServices: ['All services', 'Todos los servicios'],
  both: ['Scheduled and confirmed', 'Programadas y confirmadas'], scheduled: ['Scheduled only', 'Solo programadas'], confirmed: ['Confirmed only', 'Solo confirmadas'],
  channel: ['Send through', 'Enviar mediante'], latest: ['Patient’s latest conversation', 'Última conversación del paciente'], specific: ['Specific channel connection', 'Conexión de canal específica'],
  connection: ['Channel connection', 'Conexión del canal'], chooseChannel: ['Choose a channel', 'Selecciona un canal'],
  message: ['Message for channels other than WhatsApp Official', 'Mensaje para canales distintos de WhatsApp Official'],
  sample: ['Sample message', 'Mensaje de ejemplo'],
  templatePreview: ['WhatsApp Official uses the approved template shown below.', 'WhatsApp Official utiliza la plantilla aprobada que se muestra abajo.'],
  reply: ['Patients can reply to confirm. Sending this message does not change appointment status.', 'Los pacientes pueden responder para confirmar. El envío no modifica el estado de la cita.'],
  timingHelp: ['Delivery starts at the scheduled time and progresses through the queue. Late batches catch up only on the scheduled send date.', 'El envío comienza a la hora programada y avanza por la cola. Los envíos retrasados solo se recuperan en la fecha de envío programada.'],
  timezoneRequired: ['Save a valid clinic timezone in General Settings before scheduling reminders.', 'Guarda una zona horaria válida para la clínica en Configuración general antes de programar recordatorios.'],
  summary: ['Schedule preview', 'Vista previa de la programación'],
  dailySummary: ['Every day at {{time}}, for appointments {{days}} calendar day(s) ahead.', 'Todos los días a las {{time}}, para citas dentro de {{days}} día(s) calendario.'],
  onceSummary: ['Send on {{date}} at {{time}}, for appointments on {{target}}.', 'Enviar el {{date}} a las {{time}}, para citas del {{target}}.'],
  matches: ['{{count}} matching appointment(s)', '{{count}} cita(s) coincidente(s)'],
  estimate: ['Estimate only. Final recipients are selected when the batch begins; one message is sent per appointment.', 'Solo es una estimación. Los destinatarios se seleccionan al comenzar el envío; se envía un mensaje por cita.'],
  next: ['Next run', 'Próximo envío'], timezone: ['Clinic timezone', 'Zona horaria de la clínica'],
  active: ['Active', 'Activa'], paused: ['Paused', 'Pausada'], cancelled: ['Cancelled', 'Cancelada'], completed: ['Completed', 'Completada'], expired: ['Expired', 'Vencida'], processing: ['Processing', 'Procesando'],
  sent: ['Sent', 'Enviado'], failed: ['Failed', 'Fallido'], skipped: ['Skipped', 'Omitido'], unknown: ['Delivery unknown', 'Entrega desconocida'], pending: ['Pending', 'Pendiente'],
  details: ['Delivery details', 'Detalles del envío'], total: ['Appointments', 'Citas'],
  previous: ['Previous', 'Anterior'], more: ['Next page', 'Página siguiente'],
  unavailable: ['Unavailable selection', 'Selección no disponible'],
  starterReminder: ['Hello {{contact.name}}, a reminder of your {{appointment.service}} appointment on {{appointment.date}} at {{appointment.start_time}}. We look forward to seeing you.', 'Hola {{contact.name}}, te recordamos tu cita de {{appointment.service}} el {{appointment.date}} a las {{appointment.start_time}}. Te esperamos.'],
  starterConfirmation: ['Hello {{contact.name}}, please reply to confirm your {{appointment.service}} appointment on {{appointment.date}} at {{appointment.start_time}}. Thank you!', 'Hola {{contact.name}}, por favor responde para confirmar tu cita de {{appointment.service}} el {{appointment.date}} a las {{appointment.start_time}}. ¡Gracias!'],
} as const;
export type BatchTextKey = keyof typeof batchCopy;
export function useBatchText() {
  const { t, currentLanguage } = useTranslation();
  const spanish = currentLanguage?.code?.startsWith('es');
  return (key: BatchTextKey, values?: Record<string, string | number>) =>
    t(`erp.dental.batches.${key}`, batchCopy[key][spanish ? 1 : 0], values);
}
