import { useTranslation } from '@/hooks/use-translation';

export const queueText = {
  digitalTicket: "Digital ticket",
  digitalTicketExpiry: "Valid until midnight in the clinic’s timezone.",
  digitalTicketExpired: "This ticket has expired.",
  digitalTicketNotFound: "Ticket unavailable",
  digitalTicketFailed: "Could not load the digital ticket. You can still print the ticket.",
  loadingDigitalTicket: "Preparing ticket QR code…",
  scanTicket: "Scan to view your live ticket",
  copyTicketLink: "Copy link",
  openTicket: "Open ticket",
  ticketLinkCopied: "Ticket link copied.",
  ticketCopyFailed: "Could not copy. Select and copy the link below.",
  mobileReceptionHelp: "Please contact reception for assistance.",
  mobileConnectionWarning: "Connection interrupted. Live updates will resume when connected.",
  mobileUpdating: "Waiting for a live update",
  mobileEstimateUnavailable: "Waiting time is not available yet.",
  mobile_waiting: "Please wait for your ticket to be called. Keep this page open for updates.",
  mobile_called: "Please proceed to your consulting room.",
  mobile_in_service: "Your visit is in progress.",
  mobile_finished: "Your turn is complete. Thank you for visiting.",
  mobile_skipped: "Your turn was skipped. Please contact reception.",
  mobile_cancelled: "Your turn was cancelled. Contact reception if this was a mistake.",
  mobile_invalidated: "Your appointment changed. Please check in again at reception.",

  backgroundType: "Background type",
  backgroundTypeColor: "Color",
  backgroundTypeImage: "Image",
  backgroundImageRequired: "Upload a background image to save, or choose Color.",
  backgroundSaveFailed: "The server did not retain your background settings. Your changes are still here. Update or restart the server, then try saving again.",
  "backgroundImage": "Background image",
  "backgroundImageHelp": "Use a landscape image, ideally 1920 × 1080 or larger.",
  "backgroundImageUploadHelp": "PNG, JPG or WebP. Maximum 30 MB.",
  "uploadBackgroundImage": "Upload background image",
  "replaceBackgroundImage": "Replace image",
  "removeBackgroundImage": "Remove image",
  "uploadingBackgroundImage": "Uploading background image…",
  "backgroundImageUploadFailed": "Could not load or upload this image. Try a valid PNG, JPG or WebP file.",
  "backgroundImageMode": "Display mode",
  "backgroundImagePosition": "Image position",
  "backgroundImageTransparency": "Image transparency",
  "backgroundImageDimming": "Dark overlay",
  "backgroundTransparencyHelp": "0% shows the full image; 100% hides it. Text and cards stay visible.",
  "backgroundDimmingHelp": "Increase darkening to keep ticket numbers and text readable over bright or busy images.",
  "backgroundMode_cover": "Cover",
  "backgroundMode_fit": "Fit",
  "backgroundMode_stretch": "Stretch",
  "backgroundMode_tile": "Tile",
  "backgroundModeHelp_cover": "Fill the screen while keeping proportions. Edges may be cropped.",
  "backgroundModeHelp_fit": "Show the entire image. Unfilled space stays dark.",
  "backgroundModeHelp_stretch": "Fill the screen by stretching the image. Its proportions may change.",
  "backgroundModeHelp_tile": "Repeat the image at its original size to fill the screen.",
  "backgroundPosition_top-left": "Top left",
  "backgroundPosition_top": "Top center",
  "backgroundPosition_top-right": "Top right",
  "backgroundPosition_left": "Center left",
  "backgroundPosition_center": "Center",
  "backgroundPosition_right": "Center right",
  "backgroundPosition_bottom-left": "Bottom left",
  "backgroundPosition_bottom": "Bottom center",
  "backgroundPosition_bottom-right": "Bottom right",
  changeTurnStatus: "Status for {{ticket}}",
  statusUpdated: "{{ticket}} updated to {{status}}",
  statusPreviousDay: "Previous-day tickets require fresh check-in.",
  statusDuplicate: "This patient or appointment already has an active ticket.",
  statusResourceBusy: "The professional or consulting room is occupied.",
  statusNotDue: "This appointment is not due yet.",
  statusAssignment: "The assigned professional or room is no longer available.",
  statusAppointmentChanged: "The appointment changed or is no longer eligible. Check in again.",
  statusInvalidated: "This ticket was invalidated. Check the patient in again.",
  statusConflict: "This ticket’s status changed. Refresh and try again.",
  statusServiceUnavailable: "The assigned service is no longer available. Check in again.",
  statusPatientUnavailable: "The patient must be registered in this clinic.",
  patientManagement: "Patient management",
  receptionDescription: "Keep your waiting room moving.",
  overview: "Queue overview",
  patientQueue: "Patient queue",
  ticketCount: "{{count}} tickets",
  searchPatientOrTicket: "Search patient or ticket...",
  filters: "Filters",
  ticketStatus: "Ticket status",
  allTickets: "All tickets",
  completed: "Completed",
  moreFilters: "More filters",
  previousOnly: "Previous-day tickets only",
  assignment: "Assignment",
  previousDayShort: "Previous day",
  showingTickets: "Showing {{from}}–{{to}} of {{total}}",
  previousPage: "Previous page",
  nextPage: "Next page",
  clinicTimezone: "Clinic timezone",
  callStation: "Call station",
  stationDescription: "Choose where to call the next patient.",
  chooseStation: "Select a professional and consulting room.",
  noStationPatients: "No eligible patients in this room",
  readyToCall: "Ready to call the next patient",
  stationOffline: "Calling is paused until the connection is restored.",
  nextPatient: "Next patient",
  activeTicket: "Active ticket",
  callNextPatient: "Call next patient",
  previousTicketCount: "{{count}} previous-day tickets",
  reviewPreviousDescription: "Review unresolved tickets from earlier visits.",
  reviewTickets: "Review tickets",
  resolveTicket: "Resolve ticket",
  resolveDescription: "Resolve this previous-day turn. Appointment completion is managed separately.",
  ticketResolved: "This ticket has already been resolved.",
  title: 'Digital Turn', description: 'Welcome patients, issue tickets, and manage the waiting room.',
  openTV: 'Open TV Display', settings: 'Display settings', checkIn: 'Check in', walkIn: 'Walk-in',
  appointment: 'Appointment', patient: 'Patient', searchPatient: 'Search patients', newPatient: 'Register patient',
  patientSearchHint: 'Search patients by name', noMatchingPatients: 'No available patients found.',
  turnActions: 'Actions for {{ticket}}',
  professional: 'Professional', room: 'Consulting room', service: 'Service', select: 'Select…', all: 'All',
  issue: 'Issue ticket', next: 'Next Call', recall: 'Recall', start: 'Start Service', finish: 'Finish',
  skip: 'Skip', return: 'Return to Queue', cancel: 'Cancel', reprint: 'Reprint', print: 'Print ticket',
  waiting: 'Waiting', called: 'Called', in_service: 'In service', finished: 'Finished', skipped: 'Skipped',
  cancelled: 'Cancelled', invalidated: 'Invalidated', status: 'Status', ticket: 'Ticket', issued: 'Issued',
  estimate: 'Estimated wait', approx: 'Approx. {{minutes}} min', delayed: 'Delayed', noEstimate: 'Awaiting estimate',
  empty: 'No turns to show', noEligible: 'No patients are ready for this professional and room.',
  previousDay: 'Previous day — resolve before issuing a new ticket', busy: 'Professional or room is busy',
  nowCalling: 'Now calling', upNext: 'Up Next', welcome: 'Welcome. We will be with you shortly.',
  proceedToRoom: 'Please proceed to your treatment room.', estimatedWaitTimes: 'Estimated wait times',
  waitingCount: '{{count}} waiting', displayWait: '~{{minutes}} min', displayPage: 'Page {{page}} of {{count}}',
  ourDentalTeam: 'Our dental team', wellnessMessage: 'A healthier, brighter smile starts here.',
  thankYouPatience: 'Thank you for your patience.', noActiveRooms: 'No active consulting rooms',
  watchTicket: 'Please watch for your ticket number', available: 'Available', activeRooms: 'Consulting rooms',
  professionals: 'Professionals', services: 'Services', startDisplay: 'Start Display',
  startHint: 'Enable fullscreen and call sounds on this screen.', connecting: 'Connecting to the clinic…',
  reconnecting: 'Connection interrupted. Reconnecting…', stale: 'Display paused. Waiting for a fresh update.',
  sessionExpired: 'Your session ended or access changed. Sign in again to resume the display.', signIn: 'Sign in',
  save: 'Save settings', saved: 'Settings saved', logo: 'IPS / clinic logo', uploadLogo: 'Upload logo',
  replaceLogo: 'Replace logo', resetLogo: 'Reset change', uploadingLogo: 'Uploading logo…',
  logoHelp: 'PNG, JPG, WebP or SVG. Your logo appears on the TV display and printed tickets.',
  primaryColor: 'Accent color', backgroundColor: 'Background color', welcomeMessage: 'Welcome message',
  messages: 'Rotating messages (one per line)', ticketFooter: 'Ticket footer', paperWidth: 'Ticket width',
  chime: 'Play a chime when calling', fallback: 'Fallback service duration (minutes)', preview: 'Live preview',
  loading: 'Loading…', retry: 'Retry', issuedSuccess: 'Ticket issued. Print it now or reprint it from the queue.',
  appointmentTime: 'Appointment time', clinicTime: 'All times use the clinic timezone',
  setup: 'Configure active professionals, consulting rooms, and services in Booking Settings before issuing tickets.',
  bookingSettings: 'Booking Settings', printHint: 'Select your thermal printer and matching paper size in the print dialog.',
  reasonChanged: 'Appointment changed. Check in again with the updated details.',
  reasonDeleted: 'Appointment deleted.', reasonInactive: 'Appointment is no longer scheduled or confirmed.',
  noAppointments: 'No eligible appointments today', checkInHelp: 'Assign a professional, service, and room before issuing a ticket.',
  searchQueue: 'Search queue...', noMatchingTurns: 'No turns match your search or filters.', actions: 'Actions',
  queue: 'Queue', today: 'Today', close: 'Close', error: 'Unable to complete this action',
  logoBackground: 'Logo background', transparentBackground: 'Transparent background',
  enableSound: 'Enable sound',
  callAnnouncements: "Call announcements",
  announcementMode: "How to call patients",
  announcement_silent: "Silent (screen only)",
  announcement_chime: "Built-in chime",
  announcement_speech: "Browser text to speech",
  announcement_chime_speech: "Chime, then speech",
  announcement_sound: "Uploaded sound effect",
  announcement_sound_speech: "Uploaded sound, then speech",
  uploadSound: "Upload sound",
  replaceSound: "Replace sound",
  removeSound: "Remove sound",
  uploadingSound: "Uploading sound…",
  soundFile: "Sound file",
  soundHelp: "MP3, WAV, OGG, M4A, AAC or WebM. Maximum 5 MB and 30 seconds. Choose a file this browser can play.",
  speechLanguage: "Announcement language",
  speechVoice: "Browser voice",
  automaticVoice: "Automatic voice",
  speechRate: "Speech speed",
  speechHelp: "Announces the ticket number and consulting room. Voices depend on the TV browser; an available voice for the selected language is used if the saved voice is missing.",
  announcementVolume: "Announcement volume",
  testAnnouncement: "Test announcement",
  stopTest: "Stop test",
  announcementFailed: "Audio could not play. Check the sound file, browser voice and device audio, then test again. Visual calls remain active.",
  autoClearPreviousDay: "Automatically clear previous-day tickets",
  autoClearHelp: "At midnight in {{timezone}}, previous-day tickets leave the queue and unfinished turns are cancelled automatically. Rooms and professionals become available. Ticket history is retained; appointments are unchanged.",
  settingsBranding: "Branding",
  settingsLayout: "Queue & layout",
  settingsAnnouncements: "Announcements",
  settingsAudio: "Audio",
  settingsDescription: "Customize what patients see on your waiting-room screen.",
  settingsSaving: "Saving…",
  settingsSaved: "Saved",
  settingsUnsaved: "Unsaved changes",
  settingsSaveFailed: "Save failed",
  settingsInvalid: "Review the highlighted tab and enter valid settings within the displayed limits.",
  clinicIdentity: "Clinic identity",
  clinicIdentityHelp: "Make your display recognizable to patients.",
  clinicName: "Clinic name",
  clinicNameHelp: "TV display only. Leave blank to use the company name. Maximum 200 characters.",
  clinicNameSaveFailed: "The server did not retain the TV clinic name. Your changes are still here. Update or restart the server, then try saving again.",
  screenAppearance: "Screen appearance",
  screenAppearanceHelp: "Adjust the display colors and daily queue preferences.",
  messagesHelp: "Add up to 10 rotating messages, one per line. Maximum 300 characters per message.",
  audioSettingsHelp: "Choose how the waiting-room screen announces each call.",
  previewEditingHelp: "Changes appear here as you edit.",
  waitingRoomDisplay: "Waiting-room display",
  sampleTicketsHelp: "Preview uses sample tickets",
  expandPreview: "Expand preview",
  closePreview: "Close preview",
  keepReadable: "Keep it readable",
  keepReadableHelp: "Use a short welcome message and a clear logo for patients viewing from a distance.",
  applyAfterSaving: "Changes apply after saving.",
  saveChanges: "Save changes",
  sampleRoom: "Consulting room {{number}}",
  sampleProfessional: "Dental professional",
  sampleService: "Dental consultation",
  ticketSettings: "Ticket printing",
} as const;
export type QueueTextKey = keyof typeof queueText;
export function useQueueText() {
  const { t, currentLanguage } = useTranslation();
  return { q: (key: QueueTextKey, variables?: Record<string, unknown>) => t(`erp.dental.queue.${key}`, queueText[key], variables), locale: currentLanguage?.code || 'en' };
}

export const queueStatusErrorKeys: Record<string, QueueTextKey> = { previous_day: "statusPreviousDay", duplicate_check_in: "statusDuplicate", queue_conflict: "statusDuplicate", resource_busy: "statusResourceBusy", appointment_not_due: "statusNotDue", assignment_unavailable: "statusAssignment", specialty_mismatch: "statusAssignment", appointment_changed: "statusAppointmentChanged", ticket_invalidated: "statusInvalidated", status_changed: "statusConflict", service_unavailable: "statusServiceUnavailable", patient_not_found: "statusPatientUnavailable" };
