import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useTranslation } from '@/hooks/use-translation';
import type { ColombiaCustomerFiscalProfile, ColombiaProductFiscalProfile } from '@shared/factus';

export function ColombiaCustomerFiscalFields({ value, onChange, disabled = false }: { value: Partial<ColombiaCustomerFiscalProfile>; onChange: (value: Partial<ColombiaCustomerFiscalProfile>) => void; disabled?: boolean }) {
  const { t } = useTranslation();
  const patch = (next: Partial<ColombiaCustomerFiscalProfile>) => onChange({ ...value, ...next });
  return <fieldset className="space-y-3 rounded-md border p-3">
    <legend className="px-1 text-sm font-medium">{t('erp.electronicInvoicing.fiscalProfile.title', 'Colombia fiscal profile (Factus)')}</legend>
    <div className="grid grid-cols-2 gap-3">
      <div className="space-y-2"><Label>{t('erp.electronicInvoicing.fiscalProfile.identificationType', 'Identification type')}</Label><Select value={value.identificationDocumentCode || ''} onValueChange={(v) => patch({ identificationDocumentCode: v })} disabled={disabled}><SelectTrigger data-tour="components-erp-colombiafiscalprofilefields.selecttrigger.erp.common.select"><SelectValue placeholder={t('erp.common.select', 'Select')} /></SelectTrigger><SelectContent><SelectItem value="13">13 — {t('erp.electronicInvoicing.fiscalProfile.documents.citizenshipId', 'Citizenship ID')}</SelectItem><SelectItem value="31">31 — NIT</SelectItem><SelectItem value="41">41 — {t('erp.electronicInvoicing.fiscalProfile.documents.passport', 'Passport')}</SelectItem><SelectItem value="42">42 — {t('erp.electronicInvoicing.fiscalProfile.documents.foreignId', 'Foreign ID')}</SelectItem><SelectItem value="48">48 — PPT</SelectItem><SelectItem value="50">50 — {t('erp.electronicInvoicing.fiscalProfile.documents.foreignNit', 'Foreign NIT')}</SelectItem></SelectContent></Select></div>
      <div className="space-y-2"><Label>{t('erp.electronicInvoicing.fiscalProfile.identificationNumber', 'Identification number')}</Label><Input data-tour="components-erp-colombiafiscalprofilefields.input.erp.electronicInvoicing.fiscalProfile.identificationType" value={value.identification || ''} onChange={(e) => patch({ identification: e.target.value })} disabled={disabled} /></div>
      <div className="space-y-2"><Label>{t('erp.electronicInvoicing.fiscalProfile.verificationDigit', 'Verification digit')}</Label><Input data-tour="components-erp-colombiafiscalprofilefields.input.erp.electronicInvoicing.fiscalProfile.identificationType" value={value.dv || ''} onChange={(e) => patch({ dv: e.target.value })} disabled={disabled} /></div>
      <div className="space-y-2"><Label>{t('erp.electronicInvoicing.fiscalProfile.organizationType', 'Organization type')}</Label><Select value={value.legalOrganizationCode || ''} onValueChange={(v: '1' | '2') => patch({ legalOrganizationCode: v })} disabled={disabled}><SelectTrigger data-tour="components-erp-colombiafiscalprofilefields.selecttrigger.erp.common.select"><SelectValue placeholder={t('erp.common.select', 'Select')} /></SelectTrigger><SelectContent><SelectItem value="1">{t('erp.electronicInvoicing.fiscalProfile.legalEntity', 'Legal entity')}</SelectItem><SelectItem value="2">{t('erp.electronicInvoicing.fiscalProfile.naturalPerson', 'Natural person')}</SelectItem></SelectContent></Select></div>
      <div className="space-y-2"><Label>{t('erp.electronicInvoicing.fiscalProfile.legalName', 'Legal name')}</Label><Input data-tour="components-erp-colombiafiscalprofilefields.input.erp.electronicInvoicing.fiscalProfile.identificationType" value={value.legalName || ''} onChange={(e) => patch({ legalName: e.target.value })} disabled={disabled} /></div>
      <div className="space-y-2"><Label>{t('erp.electronicInvoicing.fiscalProfile.tradeName', 'Trade name')}</Label><Input data-tour="components-erp-colombiafiscalprofilefields.input.erp.electronicInvoicing.fiscalProfile.identificationType" value={value.tradeName || ''} onChange={(e) => patch({ tradeName: e.target.value })} disabled={disabled} /></div>
      <div className="space-y-2"><Label>{t('erp.electronicInvoicing.fiscalProfile.tributeCode', 'Tribute code')}</Label><Select value={value.tributeCode || 'ZZ'} onValueChange={(v) => patch({ tributeCode: v })} disabled={disabled}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ZZ">ZZ — {t('erp.electronicInvoicing.fiscalProfile.notApplicable', 'Not applicable')}</SelectItem><SelectItem value="01">01 — {t('erp.electronicInvoicing.fiscalProfile.vat', 'VAT')}</SelectItem></SelectContent></Select></div>
      <div className="space-y-2"><Label>{t('erp.electronicInvoicing.fiscalProfile.responsibilities', 'Fiscal responsibilities')}</Label><Input data-tour="components-erp-colombiafiscalprofilefields.input.erp.electronicInvoicing.fiscalProfile.identificationType" value={(value.responsibilities || ['R-99-PN']).join(', ')} onChange={(e) => patch({ responsibilities: e.target.value.split(',').map((x) => x.trim()).filter(Boolean) })} disabled={disabled} /></div>
      <div className="space-y-2"><Label>{t('erp.electronicInvoicing.fiscalProfile.countryCode', 'Country code')}</Label><Input data-tour="components-erp-colombiafiscalprofilefields.input.erp.electronicInvoicing.fiscalProfile.identificationType" maxLength={2} value={value.countryCode || 'CO'} onChange={(e) => patch({ countryCode: e.target.value.toUpperCase() })} disabled={disabled} /></div>
      <div className="space-y-2"><Label>{t('erp.electronicInvoicing.fiscalProfile.municipalityCode', 'Municipality code')}</Label><Input data-tour="components-erp-colombiafiscalprofilefields.input.erp.electronicInvoicing.fiscalProfile.identificationType" value={value.municipalityCode || ''} onChange={(e) => patch({ municipalityCode: e.target.value })} disabled={disabled} /></div>
    </div>
    <div className="space-y-2"><Label>{t('erp.electronicInvoicing.fiscalProfile.address', 'Fiscal address')}</Label><Input data-tour="components-erp-colombiafiscalprofilefields.input.erp.electronicInvoicing.fiscalProfile.identificationType" value={value.address || ''} onChange={(e) => patch({ address: e.target.value })} disabled={disabled} /></div>
  </fieldset>;
}

export function ColombiaProductFiscalFields({ value, onChange, disabled = false }: { value: Partial<ColombiaProductFiscalProfile>; onChange: (value: Partial<ColombiaProductFiscalProfile>) => void; disabled?: boolean }) {
  const { t } = useTranslation();
  const patch = (next: Partial<ColombiaProductFiscalProfile>) => onChange({ ...value, ...next });
  return <fieldset className="space-y-3 rounded-md border p-3"><legend className="px-1 text-sm font-medium">{t('erp.electronicInvoicing.fiscalProfile.title', 'Colombia fiscal profile (Factus)')}</legend><div className="grid grid-cols-2 gap-3">
    <div className="space-y-2"><Label>{t('erp.electronicInvoicing.fiscalProfile.referenceCode', 'Reference code')}</Label><Input data-tour="components-erp-colombiafiscalprofilefields.input.erp.electronicInvoicing.fiscalProfile.referenceCode" value={value.codeReference || ''} onChange={(e) => patch({ codeReference: e.target.value })} disabled={disabled} /></div>
    <div className="space-y-2"><Label>{t('erp.electronicInvoicing.fiscalProfile.unitMeasureCode', 'Unit measure code')}</Label><Input data-tour="components-erp-colombiafiscalprofilefields.input.erp.electronicInvoicing.fiscalProfile.referenceCode" value={value.unitMeasureCode || '94'} onChange={(e) => patch({ unitMeasureCode: e.target.value })} disabled={disabled} /></div>
    <div className="space-y-2"><Label>{t('erp.electronicInvoicing.fiscalProfile.productStandardCode', 'Product standard code')}</Label><Input data-tour="components-erp-colombiafiscalprofilefields.input.erp.electronicInvoicing.fiscalProfile.referenceCode" value={value.standardCode || '999'} onChange={(e) => patch({ standardCode: e.target.value })} disabled={disabled} /></div>
    <div className="space-y-2"><Label>{t('erp.electronicInvoicing.fiscalProfile.taxCode', 'Tax code')}</Label><Input data-tour="components-erp-colombiafiscalprofilefields.input.erp.electronicInvoicing.fiscalProfile.referenceCode" value={value.taxCode || '01'} onChange={(e) => patch({ taxCode: e.target.value })} disabled={disabled || value.isExcluded} /></div>
    <label className="col-span-2 flex items-center gap-2 text-sm"><input data-tour="components-erp-colombiafiscalprofilefields.input.erp.electronicInvoicing.fiscalProfile.excluded" type="checkbox" checked={value.isExcluded || false} onChange={(e) => patch({ isExcluded: e.target.checked })} disabled={disabled} />{t('erp.electronicInvoicing.fiscalProfile.excluded', 'Excluded from tax')}</label>
  </div></fieldset>;
}
