import {erpCurrencyDigits} from '@shared/erp-currency-precision';
import {useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {apiRequest} from '@/lib/queryClient';
import {useTranslation} from '@/hooks/use-translation';
import {useToast} from '@/hooks/use-toast';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
type Allocation={id:number;target_invoice_id:number;target_invoice_number:string;amount:string;reference:string;reason:string;status:string;created_at:string};
export function CreditNoteAllocations({invoiceId,companyId,currency,canManage,currencyDecimalPlaces}:{invoiceId:number;companyId:number;currency:string;canManage:boolean;currencyDecimalPlaces?:number}){
 const {t,currentLanguage}=useTranslation(),{toast}=useToast(),cache=useQueryClient();
 const [open,setOpen]=useState(false),[reversing,setReversing]=useState<number|null>(null),[amount,setAmount]=useState(''),[target,setTarget]=useState('none'),[reference,setReference]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false);
 const label=(key:string,fallback:string)=>t(`erp.invoices.allocations.${key}`,fallback);
 const money=(value:string)=>new Intl.NumberFormat(currentLanguage?.code,{style:'currency',currency,minimumFractionDigits:erpCurrencyDigits(currencyDecimalPlaces),maximumFractionDigits:erpCurrencyDigits(currencyDecimalPlaces)}).format(Number(value));
 const history=useQuery<{data:Allocation[]}>({queryKey:['erp-credit-allocations',companyId,invoiceId],queryFn:async()=>(await apiRequest('GET',`/api/erp/invoices/${invoiceId}/allocations`)).json()});
 const targets=useQuery<{data:Array<{id:number;invoice_number:string;amount_due:string}>}>({enabled:open&&canManage&&reversing===null,queryKey:['erp-allocation-targets',companyId,invoiceId],queryFn:async()=>(await apiRequest('GET',`/api/erp/invoices/${invoiceId}/allocation-context`)).json()});
 const mutation=useMutation({mutationFn:async()=>reversing!==null?apiRequest('POST',`/api/erp/invoices/${invoiceId}/allocations/${reversing}/reverse`,{confirmed}):apiRequest('POST',`/api/erp/invoices/${invoiceId}/allocations`,{amount,targetInvoiceId:Number(target),reference,reason,confirmed}),onSuccess:()=>{cache.invalidateQueries({queryKey:['erp-credit-allocations',companyId,invoiceId]});cache.invalidateQueries({queryKey:['erp-credit-refunds',companyId,invoiceId]});cache.invalidateQueries({queryKey:['erp-allocation-targets',companyId,invoiceId]});cache.invalidateQueries({queryKey:['/api/erp/invoices',companyId]});setOpen(false);setReversing(null);toast({title:t('erp.common.saved','Saved')});},onError:(e:Error)=>toast({title:t('common.error','Error'),description:e.message,variant:'destructive'})});
 return <section className="space-y-4 rounded-lg border p-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">{label('title','Customer credit allocations')}</h3>{canManage&&<Button size="sm" onClick={()=>{setOpen(true);setReversing(null);setAmount('');setTarget('none');setReference('');setReason('');setConfirmed(false);}}>{label('record','Apply credit')}</Button>}</div>
  {history.isError?<Button variant="outline" onClick={()=>history.refetch()}>{t('common.retry','Retry')}</Button>:history.isLoading?<p role="status">{t('common.loading','Loading')}</p>:!history.data?.data.length?<p className="text-sm text-muted-foreground">{label('empty','No credit allocations recorded')}</p>:history.data.data.map(a=><article key={a.id} className="space-y-2 border-t pt-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong className="break-all">{a.reference}</strong><strong>{money(a.amount)}</strong></div><p>{a.target_invoice_number} · {label(a.status,a.status)}</p><p className="break-words text-muted-foreground">{a.reason}</p>{canManage&&a.status==='posted'&&<Button variant="outline" size="sm" onClick={()=>{setReversing(a.id);setConfirmed(false);setOpen(true);}}>{label('reverse','Reverse allocation')}</Button>}</article>)}
  <Dialog open={open} onOpenChange={value=>{if(!mutation.isPending)setOpen(value);}}><DialogContent><DialogHeader><DialogTitle>{reversing!==null?label('reverse','Reverse allocation'):label('record','Apply credit')}</DialogTitle><DialogDescription>{label('help','Apply available collected customer credit to another invoice for the same customer and currency. Receipt history is retained.')}</DialogDescription></DialogHeader>
  {reversing===null&&<><div className="space-y-2"><Label htmlFor="allocation-amount">{label('amount','Allocation amount')}</Label><Input id="allocation-amount" type="number" min="0" step="any" value={amount} onChange={e=>setAmount(e.target.value)}/></div><div className="space-y-2"><Label>{label('target','Target ERP invoice')}</Label><Select value={target} onValueChange={setTarget}><SelectTrigger aria-label={label('target','Target ERP invoice')}><SelectValue/></SelectTrigger><SelectContent searchable><SelectItem value="none">{t('erp.common.none','None')}</SelectItem>{targets.data?.data.map(i=><SelectItem key={i.id} value={String(i.id)}>{i.invoice_number} · {money(i.amount_due)}</SelectItem>)}</SelectContent></Select>{targets.isError&&<Button variant="outline" onClick={()=>targets.refetch()}>{t('common.retry','Retry')}</Button>}</div><div className="space-y-2"><Label htmlFor="allocation-reference">{label('reference','Allocation reference')}</Label><Input id="allocation-reference" maxLength={250} value={reference} onChange={e=>setReference(e.target.value)}/></div><div className="space-y-2"><Label htmlFor="allocation-reason">{label('reason','Allocation reason')}</Label><Input id="allocation-reason" maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></div></>}
  <div className="flex items-start gap-3"><Checkbox id="allocation-confirmed" checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/><Label htmlFor="allocation-confirmed">{reversing!==null?label('reversalConfirmed','Restore the credit and target invoice balance'):label('confirmed','Apply this credit to the selected invoice')}</Label></div><DialogFooter><Button variant="outline" disabled={mutation.isPending} onClick={()=>setOpen(false)}>{t('common.cancel','Cancel')}</Button><Button disabled={mutation.isPending||!confirmed||(reversing===null&&(Number(amount)<=0||target==='none'||!reference.trim()||!reason.trim()))} onClick={()=>mutation.mutate()}>{t('erp.common.save','Save')}</Button></DialogFooter></DialogContent></Dialog>
 </section>;
}
