import {erpRetainedAmountDigits} from '../../../../shared/erp-currency-precision';
import {useQuery} from '@tanstack/react-query';
import {Link} from 'wouter';
import {apiRequest} from '@/lib/queryClient';
import {useTranslation} from '@/hooks/use-translation';
export function InvoiceNoncashSettlements({invoiceId,companyId,currency,decimalPlaces=2}:{invoiceId:number;companyId:number;currency:string;decimalPlaces?:number}){
 const {t,currentLanguage}=useTranslation(),q=useQuery<{data:Array<{id:number;source_type:string;source_id:number|null;amount:string;status:string;journal_entry_id:number;created_at:string;original_allocation_id?:number;reason?:string;transaction_decimal_places?:number}>}>({queryKey:['/api/erp/invoices',companyId,'noncash',invoiceId],queryFn:async()=>(await apiRequest('GET',`/api/erp/invoices/${invoiceId}/noncash-settlements`)).json()});
 if(q.isError)return <p role="alert">{t('erp.realEstate.loadError','Unable to load this information.')}</p>;
 if(!q.data?.data.length)return null;
 return <section className="mb-5 space-y-3 rounded-lg border p-4"><h3 className="font-semibold">{t('erp.realEstate.settlementFees.noncash','Noncash invoice settlements')}</h3>{q.data.data.map(r=><article key={r.id} className="flex flex-wrap justify-between gap-3 border-t pt-3 text-sm"><div>{r.source_type==='owner_settlement'&&r.source_id?<Link className="text-primary underline" href={`/erp/real-estate/owner-settlements/${r.source_id}`}>{t('erp.realEstate.settlementFees.ownerSettlement','Owner settlement')} #{r.source_id}</Link>:<span>{t('erp.realEstate.settlementFees.noncash','Noncash invoice settlements')}</span>}<p className="mt-1 text-xs text-muted-foreground">{r.original_allocation_id&&<>{t('erp.realEstate.settlements.creditDelta','Correction')} #{r.original_allocation_id} · </>}{new Date(r.created_at).toLocaleDateString(currentLanguage?.code)} / {t(`erp.realEstate.settlements.status.${r.status}`,r.status)}</p>{r.reason&&<p className="mt-1 break-words text-xs">{r.reason}</p>}</div><strong data-testid={`invoice-noncash-amount-${r.id}`}>{new Intl.NumberFormat(currentLanguage?.code,{style:'currency',currency,minimumFractionDigits:erpRetainedAmountDigits(r.amount,r.transaction_decimal_places??decimalPlaces),maximumFractionDigits:erpRetainedAmountDigits(r.amount,r.transaction_decimal_places??decimalPlaces)}).format(Number(r.amount))}</strong></article>)}</section>;
}
