import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {useTranslation} from '@/hooks/use-translation';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';

/** Shared confirmation for recording returned money through ERP journal reversal. */
export function ReturnedPayoutDialog({open,onClose,reference,setReference,reason,setReason,confirmed,setConfirmed,pending,onSubmit,amount,setAmount,account,setAccount,accounts,maximum}:{open:boolean;onClose:()=>void;reference:string;setReference:(value:string)=>void;reason:string;setReason:(value:string)=>void;confirmed:boolean;setConfirmed:(value:boolean)=>void;pending:boolean;onSubmit:()=>void;amount:string;setAmount:(value:string)=>void;account:string;setAccount:(value:string)=>void;accounts:Array<{id:number;name:string}>;maximum:string}){
 const {t}=useTranslation(),label=(key:string,fallback:string)=>t(`erp.realEstate.settlements.${key}`,fallback);
 return <Dialog open={open} onOpenChange={value=>{if(!value&&!pending)onClose();}}><DialogContent><DialogHeader><DialogTitle>{label('recoverPayout','Record returned payout')}</DialogTitle><DialogDescription>{label('recoverHelp','Record money already returned. Choose the amount and receiving account; ERP posting restores the payable using the original payout accounting basis.')}</DialogDescription></DialogHeader><div className="space-y-2"><Label htmlFor="payout-return-amount">{label('returnAmount','Returned amount')}</Label><Input id="payout-return-amount" type="number" min="0" step="any" max={maximum} value={amount} onChange={e=>setAmount(e.target.value)}/></div><div className="space-y-2"><Label>{label('returnAccount','ERP receiving account')}</Label><Select value={account} onValueChange={setAccount}><SelectTrigger aria-label={label('returnAccount','ERP receiving account')}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">{t('erp.common.none','None')}</SelectItem>{accounts.map(a=><SelectItem key={a.id} value={String(a.id)}>{a.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="payout-return-reference">{label('returnReference','Return reference')}</Label><Input id="payout-return-reference" maxLength={250} value={reference} onChange={e=>setReference(e.target.value)}/></div><div className="space-y-2"><Label htmlFor="payout-return-reason">{label('recoveryReason','Reason for return')}</Label><Input id="payout-return-reason" maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></div><div className="flex items-start gap-3"><Checkbox id="payout-funds-returned" checked={confirmed} onCheckedChange={value=>setConfirmed(value===true)}/><Label htmlFor="payout-funds-returned">{label('fundsReturned','The entered amount has been returned to the selected account')}</Label></div><DialogFooter><Button variant="outline" disabled={pending} onClick={onClose}>{t('common.cancel','Cancel')}</Button><Button disabled={pending||!confirmed||!reference.trim()||!reason.trim()||Number(amount)<=0||Number(amount)>Number(maximum)||account==='none'} onClick={onSubmit}>{label('recoverPayout','Record returned payout')}</Button></DialogFooter></DialogContent></Dialog>;
}
