import {useState} from 'react';
import {Link} from 'wouter';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {apiRequest} from '@/lib/queryClient';
import {useTranslation} from '@/hooks/use-translation';
import {useToast} from '@/hooks/use-toast';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import type {SettlementFee} from '@shared/real-estate-settlement-fees';
export function SettlementFees({id,companyId,currency,decimalPlaces=2,items,editable,canView}:{id:number;companyId:number;currency:string;decimalPlaces?:number;items:Array<SettlementFee & {invoiceNumber?:string}>;editable:boolean;canView:boolean}){
 const {t,currentLanguage}=useTranslation(),{toast}=useToast(),cache=useQueryClient(),[invoice,setInvoice]=useState('none'),[amount,setAmount]=useState(''),[search,setSearch]=useState('');
 const label=(key:string,fallback:string)=>t(`erp.realEstate.settlementFees.${key}`,fallback);
 const candidates=useQuery<{data:Array<{id:number;name:string;amountDue:string}>}>({enabled:editable&&canView,queryKey:['real-estate',companyId,'settlement-fee-invoices',id,search],queryFn:async()=>(await apiRequest('GET',`/api/erp/real-estate/owner-settlements/${id}/fee-invoices?search=${encodeURIComponent(search)}`)).json()});
 const save=useMutation({mutationFn:async(fees:SettlementFee[])=>apiRequest('PATCH',`/api/erp/real-estate/owner-settlements/${id}/fees`,{expected:JSON.stringify(items),fees:fees.map(f=>({invoiceId:f.invoiceId,amount:f.amount}))}),onSuccess:()=>{cache.invalidateQueries({queryKey:['real-estate',companyId]});setInvoice('none');setAmount('');toast({title:t('erp.common.saved','Saved')});},onError:(e:Error)=>toast({title:t('common.error','Error'),description:e.message,variant:'destructive'})});
 const money=(v:string)=>new Intl.NumberFormat(currentLanguage?.code,{style:'currency',currency,minimumFractionDigits:decimalPlaces,maximumFractionDigits:decimalPlaces}).format(Number(v));
 return <section className="re-panel space-y-4 p-5"><h2 className="font-semibold">{label('title','Management fee invoices')}</h2><p className="text-sm text-muted-foreground">{label('help','Select an issued Catalog-backed ERP invoice billed to this owner. Posting deducts the fee from the owner payable and settles the invoice without recording cash. Revenue and tax stay on the original invoice.')}</p>
 {items.map(item=><article key={item.invoiceId} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4 text-sm"><div className="min-w-0">{canView?<Link href={`/erp/invoices?detail=${item.invoiceId}`} className="break-words text-primary underline">{item.invoiceNumber??`#${item.invoiceId}`}</Link>:<span>{item.invoiceNumber??`#${item.invoiceId}`}</span>}</div><strong>{money(item.amount)}</strong>{editable&&<Button size="sm" variant="outline" disabled={save.isPending} onClick={()=>save.mutate(items.filter(f=>f.invoiceId!==item.invoiceId))}>{label('remove','Remove fee')}</Button>}</article>)}
 {editable&&<><Input aria-label={label('search','Search fee invoices')} placeholder={label('search','Search fee invoices')} value={search} onChange={e=>setSearch(e.target.value)}/>{candidates.isError?<p role="alert">{t('erp.realEstate.loadError','Unable to load this information.')}<Button variant="outline" onClick={()=>candidates.refetch()}>{t('common.retry','Retry')}</Button></p>:<><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>{label('invoice','ERP fee invoice')}</Label><Select value={invoice} onValueChange={v=>{setInvoice(v);setAmount(candidates.data?.data.find(i=>String(i.id)===v)?.amountDue??'');}}><SelectTrigger aria-label={label('invoice','ERP fee invoice')}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">{t('erp.common.none','None')}</SelectItem>{candidates.data?.data.filter(i=>!items.some(f=>f.invoiceId===i.id)).map(i=><SelectItem key={i.id} value={String(i.id)}>{i.name} / {money(i.amountDue)}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="settlement-fee-amount">{label('amount','Fee deduction amount')}</Label><Input id="settlement-fee-amount" type="number" min="0" step="any" value={amount} onChange={e=>setAmount(e.target.value)}/></div></div><div className="flex flex-wrap justify-end gap-3"><Link href="/erp/invoices" className="text-sm text-primary underline">{label('openInvoices','Open ERP invoices')}</Link><Button disabled={save.isPending||invoice==='none'||Number(amount)<=0} onClick={()=>save.mutate([...items,{invoiceId:Number(invoice),amount}])}>{label('add','Add fee invoice')}</Button></div>{!candidates.isLoading&&!candidates.data?.data.length&&<p className="text-sm text-muted-foreground">{label('empty','No eligible outstanding Catalog invoices for this owner and currency. Create and issue the service invoice in ERP Invoices.')}</p>}</>}</>}
 </section>;
}
