import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {apiRequest} from '@/lib/queryClient';
import {useTranslation} from '@/hooks/use-translation';
import {useToast} from '@/hooks/use-toast';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
type Preview={snapshot:string;items:Array<{id:number;transactionDecimalPlaces?:number;currentPayable:string;expectedPayable:string;paid:string;delta:string;baseDelta?:string;requiresSync:boolean}>};
export function SettlementFeeCredits({id,companyId,currency,invoiceIds,editable}:{id:number;companyId:number;currency:string;invoiceIds:number[];editable:boolean}){
 const {t,currentLanguage}=useTranslation(),{toast}=useToast(),cache=useQueryClient(),[invoiceId,setInvoiceId]=useState<number|null>(null),[reason,setReason]=useState('');
 const label=(key:string,fallback:string)=>t(`erp.realEstate.settlements.${key}`,fallback),money=(v:string,digits=2)=>new Intl.NumberFormat(currentLanguage?.code,{minimumFractionDigits:digits,maximumFractionDigits:digits,style:'currency',currency}).format(Number(v));
 const preview=useQuery<Preview>({enabled:invoiceId!==null,queryKey:['real-estate',companyId,'settlement-fee-credit-preview',id,invoiceId],queryFn:async()=>(await (await apiRequest('GET',`/api/erp/real-estate/owner-settlements/${id}/fee-credit-preview?invoiceId=${invoiceId}`)).json()).data});
 const apply=useMutation({mutationFn:async()=>apiRequest('POST',`/api/erp/real-estate/owner-settlements/${id}/reconcile-fee-credits`,{invoiceId,expected:preview.data!.snapshot,reason}),onSuccess:()=>{cache.invalidateQueries({queryKey:['real-estate',companyId]});setInvoiceId(null);toast({title:t('erp.common.saved','Saved')});},onError:(e:Error)=>{preview.refetch();toast({title:t('common.error','Error'),description:e.message,variant:'destructive'});}});
 if(!editable||!invoiceIds.length)return null;
 const needsReturn=preview.data?.items.some(i=>Number(i.expectedPayable)<Number(i.paid)||Number(i.expectedPayable)<0),changed=preview.data?.items.some(i=>(Number(i.delta)!==0||Number(i.baseDelta??0)!==0)||i.requiresSync);
 return <section className="re-panel p-5"><h2 className="font-semibold">{label('feeCredits','Catalog fee note reconciliation')}</h2><p className="mt-2 text-xs text-muted-foreground">{label('feeCreditsHelp','Review posted ERP Catalog fee notes across all settlements sharing this invoice. Original deductions and payout history remain retained.')}</p><div className="mt-4 flex flex-wrap gap-2">{invoiceIds.map(invoice=><Button key={invoice} variant="outline" size="sm" onClick={()=>{setInvoiceId(invoice);setReason('');}}>{label('reviewFeeInvoice','Review fee invoice')} #{invoice}</Button>)}</div><Dialog open={invoiceId!==null} onOpenChange={v=>{if(!v)setInvoiceId(null);}}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{label('feeCredits','Catalog fee note reconciliation')}</DialogTitle><DialogDescription>{label('feeCreditsHelp','Review posted ERP Catalog fee notes across all settlements sharing this invoice. Original deductions and payout history remain retained.')}</DialogDescription></DialogHeader>{preview.isLoading?<p role="status">{t('common.loading','Loading...')}</p>:preview.isError?<div role="alert"><p className="break-words text-sm">{(preview.error as Error).message}</p><Button variant="outline" onClick={()=>preview.refetch()}>{t('common.retry','Retry')}</Button></div>:<div className="space-y-3">{preview.data?.items.map(i=><div key={i.id} className="rounded-lg border p-3 text-sm"><p className="font-medium">{label('title','Owner Settlements')} #{i.id}</p><div className="mt-2 grid grid-cols-2 gap-3"><p>{label('currentPayable','Current payable')}: {money(i.currentPayable,i.transactionDecimalPlaces)}</p><p>{label('revisedPayable','Revised payable')}: {money(i.expectedPayable,i.transactionDecimalPlaces)}</p><p>{label('paid','Paid')}: {money(i.paid,i.transactionDecimalPlaces)}</p><p>{label('creditDelta','Correction')}: {money(i.delta,i.transactionDecimalPlaces)}</p></div></div>)}</div>}{needsReturn&&<p role="alert" className="text-sm text-amber-500">{label('ownerReturnsRequired','Record confirmed returned owner payouts exceeding the revised payable before applying correction.')}</p>}{changed?<div className="space-y-2"><Label htmlFor="owner-credit-reason">{label('creditReason','Reason')}</Label><Input id="owner-credit-reason" value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></div>:preview.data&&<p role="status" className="text-sm text-muted-foreground">{label('feeCreditsCurrent','Owner entitlement is current. No correction is needed.')}</p>}<DialogFooter><Button variant="outline" onClick={()=>setInvoiceId(null)}>{t('common.cancel','Cancel')}</Button><Button disabled={apply.isPending||!changed||needsReturn||!reason.trim()} onClick={()=>apply.mutate()}>{label('applyRentCredits','Apply owner correction')}</Button></DialogFooter></DialogContent></Dialog></section>;
}
