import { DOCUMENT_GENERATOR_LOGO_SRC_TOKEN } from './document-generator-defaults';

export interface QuoteDesignPromptParams {
  content: string;
  language?: string;
  hasLogo: boolean;
}

function buildQuoteDesignBrief(params: QuoteDesignPromptParams): string {
  const languageLine = params.language
    ? `Language for all visible text: ${params.language}.`
    : 'Language: match the content (usually Spanish).';

  const logoLine = params.hasLogo
    ? `A company logo is attached. Place it prominently in the header and use it as the foundation of the visual identity. In HTML, use exactly: <img src="${DOCUMENT_GENERATOR_LOGO_SRC_TOKEN}" style="max-height:75px;max-width:260px;object-fit:contain;" alt="Logo" /> — do not invent a different logo.`
    : 'No logo was provided. Use a clean typographic company name from the content if available. Choose a professional palette that matches the business industry.';

  return [
    'You are an expert visual designer and quotation document generator. Transform the provided quotation data into a polished, Canva-style quotation design.',
    '',
    'Create a professional quotation that looks like a real premium business document — not a plain text document, not a basic HTML table, and not a generic reused template.',
    '',
    'INPUT DATA',
    '',
    'The user provides quotation data in any format (plain text, JSON, spreadsheet extract, or structured fields). Extract and organize the information intelligently.',
    '',
    'Possible data may include: company name, company logo, company address, company contact details, client name, client company, client address, quotation number, quotation date, valid-until date, project or event name, description of services or products, quantity, unit price, duration, subtotal, tax, discount, total, payment terms, notes, terms and conditions, and contact information.',
    '',
    'DESIGN OBJECTIVE',
    '',
    'Generate a visually impressive quotation inspired by high-quality Canva business templates.',
    '',
    'The design must have:',
    '- Strong visual hierarchy',
    '- A professional cover or header section',
    '- Clear separation between company information and client information',
    '- A well-designed quotation details section',
    '- A clean and readable pricing table',
    '- Prominent total amount',
    '- Proper spacing and alignment',
    '- Consistent typography',
    '- A professional color palette',
    '- Balanced use of whitespace',
    '- Modern visual elements such as subtle shapes, lines, cards, accents, or geometric elements where appropriate',
    '',
    'The design must feel intentionally designed. Do not simply place all text into a standard document template. Do NOT reuse the same layout, palette, or styling on every quote — vary the aesthetic based on this specific client and content.',
    '',
    'DESIGN STYLE',
    '',
    'Choose the visual style based on the nature of the business and quotation data. Valid directions include modern corporate, minimal luxury, premium business, clean technology, elegant hospitality, industrial and commercial, creative agency, construction and engineering, event services, solar and renewable energy, and professional services.',
    '',
    'Use the data (and attached logo when present) to determine the most appropriate style automatically.',
    '',
    'COLOR SYSTEM',
    '',
    'Create a consistent color system with one primary brand color, one secondary accent color, neutral background colors, and strong contrast for important information.',
    '',
    'If brand colors or a logo are provided, use them as the foundation of the visual identity.',
    '',
    'Do not use too many colors. Keep the design cohesive and professional.',
    '',
    logoLine,
    '',
    'TYPOGRAPHY',
    '',
    'Use a maximum of two font families.',
    '',
    'Use typography to create a clear hierarchy:',
    '- Company name and quotation title: prominent',
    '- Section headings: clear and visually distinct',
    '- Body text: highly readable',
    '- Prices and total: visually emphasized',
    '- Supporting information: smaller but still readable',
    '',
    'Avoid excessive use of bold text, all caps, decorative fonts, or unnecessary text effects.',
    '',
    'LAYOUT',
    '',
    'Structure the quotation logically. A typical layout may include:',
    '1. Header or cover section — company branding, quotation title, quotation number and date, strong visual identity',
    '2. Client and quotation information — prepared for, client details, project or event details',
    '3. Introduction or summary — concise professional description',
    '4. Products or services — item name, description, quantity, unit price, duration if applicable, total price',
    '5. Pricing summary — subtotal, discounts, taxes, additional fees, grand total',
    '6. Terms and conditions — payment terms, validity, important conditions',
    '7. Closing section — thank-you message, contact details, signature area if appropriate',
    '',
    'Do not force every section into the design. Only include sections for which data exists.',
    '',
    'CONTENT HANDLING',
    '',
    'Do not invent important business information, prices, dates, client details, or legal terms.',
    '',
    'If data is missing, omit that section rather than creating fake information.',
    '',
    'Preserve the exact numerical values provided by the user.',
    '',
    'Format currency consistently throughout the quotation.',
    '',
    'Keep the wording professional and concise. If the input contains rough notes, rewrite them into polished quotation language while preserving the original meaning.',
    '',
    languageLine,
    '',
    'PAGE DESIGN',
    '',
    'Every page must feel like part of the same document. Maintain consistent margins, typography, colors, spacing, and repeated header or footer elements where appropriate.',
    '',
    'Avoid overcrowding. If there is too much content, create additional pages instead of shrinking the text excessively.',
    '',
    'FINAL QUALITY CHECK',
    '',
    'Before completing the design, verify:',
    '- All provided data is included accurately',
    '- No important information was invented',
    '- Prices and totals are mathematically consistent',
    '- The quotation is easy to scan',
    '- The most important information has the strongest visual emphasis',
    '- The design looks professional and premium',
    '- The layout is balanced and text is readable',
    '- The design feels like a professionally created Canva quotation template',
    '',
    'QUOTATION DATA:',
    params.content,
  ].join('\n');
}

export function buildQuoteHtmlPrompt(params: QuoteDesignPromptParams): string {
  return [
    buildQuoteDesignBrief(params),
    '',
    'OUTPUT (HTML FOR PDF)',
    '',
    'Generate the final quotation as a complete visual design suitable for sending to a client, exporting as a high-quality PDF, printing, and sharing digitally.',
    '',
    'Prioritize visual quality, hierarchy, readability, and professional presentation over simply fitting all content onto one page.',
    '',
    'Return ONLY a full self-contained <html> document with inline CSS. No markdown fences, no commentary, no code explanation.',
    '',
    'Technical requirements:',
    '- A4 portrait',
    '- @page { size: A4; margin: 12mm; }',
    '- print-friendly CSS with printBackground support',
    '- Sharp readable text at print resolution',
    '- Use CSS page-break rules for multi-page documents when content is long',
    '- Clear page numbering for multi-page documents',
  ].join('\n');
}

export function buildQuoteImagePrompt(params: QuoteDesignPromptParams): string {
  return [
    buildQuoteDesignBrief(params),
    '',
    'OUTPUT (IMAGE)',
    '',
    'Generate the final quotation as a single high-resolution portrait image with A4 proportions.',
    '',
    'All text must be sharp and readable. Prioritize visual quality, hierarchy, readability, and professional presentation.',
    '',
    'The result should look like a premium Canva quotation template suitable for wrapping into a PDF and sharing with a client.',
  ].join('\n');
}
