import { TOUR_FEATURES, type TourFeature } from './guided-tour-registry';
import { TOUR_TARGETS } from './guided-tour-targets';
import { tourDefinitionSchema, type TourDefinition, type TourStep } from './guided-tours';
import spanish from '../translations/es.json';

const es = new Map((spanish as { key:string;value:string }[]).map(item=>[item.key,item.value]));
const localized=(en:string,translation:string)=>({en,es:translation});
const target=(key:string,file?:string,tag?:string) => TOUR_TARGETS.find(item => (item.labelKey===key || item.id.endsWith(`.${key}`)) && (!file || item.file.endsWith(`/${file}.tsx`)) && (!tag || item.tag===tag));
function selector(key:string,file?:string,tag?:string) { const item=target(key,file,tag); if(!item)throw new Error(`Missing tour target: ${file || '*'} ${tag || '*'} ${key}`);return item.selector; }
const step=(id:string,target:string,title:string,titleEs:string,content:string,contentEs:string,completion:TourStep['completion']={type:'next'},extra:Partial<TourStep>={}):TourStep => ({id,target,title:localized(title,titleEs),content:localized(content,contentEs),completion,placement:'auto',prepare:[],media:[],consequential:false,...extra});
const pageTarget='[data-tour-current-page]';
const fileFor=(feature:TourFeature) => {
  if(feature.id.startsWith('settings-') || feature.id==='settings')return 'settings';
  if(feature.id.startsWith('erp-settings'))return 'erp/settings';
  if(feature.id.startsWith('dental-patient-'))return 'erp/dental/patient-detail';
  return ({email:'EmailInterface',inbox:'Inbox',pipeline:'pipeline-view','my-calendar':'my-calendar-settings'} as Record<string,string>)[feature.id] || feature.route.split('?')[0].slice(1);
};
type Workflow = { button:string; editor:string; field?:string; file?:string; editorFile?:string; signal:string; permissions:string[]; detail:string; detailEs:string; };
const workflows:Record<string,Workflow>={
  contacts:{button:'contacts.page.actions.add_contact_aria',editor:'contacts.add.title',field:'contacts.add.name_placeholder',signal:'contact-created',permissions:['create_contacts'],detail:'Enter the contact name, identity and contact details. Review any required custom fields, then create the contact.',detailEs:'Introduce el nombre, la identidad y los datos de contacto. Revisa los campos personalizados obligatorios y crea el contacto.'},
  tasks:{button:'tasks.createTask',editor:'tasks.createTask',field:'tasks.titlePlaceholder',signal:'task-created',permissions:['manage_tasks'],detail:'Enter a title, choose the contact, priority, due date and assignee, then create the task.',detailEs:'Introduce un título, selecciona el contacto, la prioridad, la fecha y el responsable; después crea la tarea.'},
  'erp-products':{button:'erp.products.newProduct',editor:'erp.products.dialog.editTitle',field:'p-name',signal:'product-created',permissions:['manage_products'],detail:'Enter the product name, SKU, type, price and required fields. Save the product when the details are correct.',detailEs:'Introduce el nombre, SKU, tipo, precio y campos obligatorios. Guarda el producto cuando los datos sean correctos.'},
  'erp-suppliers':{button:'erp.suppliers.actions.addSupplier',editor:'erp.suppliers.dialog.editTitle',signal:'supplier-created',permissions:['manage_suppliers'],detail:'Enter the supplier name, contact information, address and payment terms. Save the supplier.',detailEs:'Introduce el nombre del proveedor, sus datos de contacto, dirección y condiciones de pago. Guarda el proveedor.'},
  'erp-employees':{button:'erp.employees.actions.addEmployee',editor:'erp.employees.dialog.editTitle',signal:'employee-created',permissions:['manage_hr'],detail:'Complete employee identity, department, position and employment details. Save the employee record.',detailEs:'Completa la identidad, departamento, puesto y datos laborales. Guarda el registro del empleado.'},
  'erp-invoices':{button:'erp.invoices.actions.createInvoice',editor:'erp.invoices.dialog.newTitle',signal:'invoice-created',permissions:['manage_invoices'],detail:'Choose the invoice type and customer or supplier. Add line items and review taxes, totals and dates before creating the invoice.',detailEs:'Elige el tipo de factura y el cliente o proveedor. Añade conceptos y revisa impuestos, totales y fechas antes de crearla.'},
  'erp-sales-orders':{button:'erp.salesOrders.newOrder',editor:'erp.salesOrders.newQuotation',signal:'sales-order-created',permissions:['manage_sales_orders'],detail:'Select a customer, add products and quantities, and review prices, taxes and delivery details. Create the sales order.',detailEs:'Selecciona el cliente, añade productos y cantidades y revisa precios, impuestos y entrega. Crea el pedido.'},
  'erp-purchase-orders':{button:'erp.purchaseOrders.actions.createPo',editor:'erp.purchaseOrders.dialog.newTitle',signal:'purchase-order-created',permissions:['manage_purchase_orders'],detail:'Choose the supplier, currency, dates and purchase-order details. Create the order; add and receive line items using the order detail controls.',detailEs:'Elige proveedor, moneda, fechas y datos del pedido de compra. Crea el pedido; añade y recibe los artículos desde sus detalles.'},
  'erp-inventory':{button:'erp.inventory.actions.recordAdjustment',editor:'erp.inventory.adjustment.title',field:'erp.inventory.adjustment.quantityExample',signal:'stock-adjusted',permissions:['manage_inventory'],detail:'Select the product and warehouse, enter the signed stock adjustment and reason, then record it. This changes real stock.',detailEs:'Selecciona producto y almacén, introduce el ajuste de existencias y el motivo y regístralo. Esto modifica las existencias reales.'},
  'erp-accounting':{button:'erp.accounting.actions.addAccount',editor:'erp.accounting.dialog.editAccount',signal:'account-created',permissions:['manage_accounting'],detail:'Enter the account code, name and type, choose its parent if needed, and save the account.',detailEs:'Introduce código, nombre y tipo de cuenta, elige la cuenta superior si corresponde y guarda.'},
  'erp-hr':{button:'erp.hr.leave.newRequest',editor:'erp.hr.leave.editTitle',signal:'leave-created',permissions:['manage_hr'],detail:'Select the employee, leave type, start and end dates, and reason. Submit the leave request for the normal approval process.',detailEs:'Selecciona empleado, tipo de permiso, fechas y motivo. Envía la solicitud al proceso habitual de aprobación.'},
  'erp-payroll':{button:'erp.payroll.actions.newRun',editor:'erp.payroll.dialog.newRunTitle',signal:'payroll-created',permissions:['manage_payroll'],detail:'Set the payroll period, payment date and notes. Create the payroll run before adding employee lines.',detailEs:'Establece el período de nómina, la fecha de pago y las notas. Crea la nómina antes de añadir empleados.'},
  'dental-patients':{button:'erp.dental.patients.add',editor:'erp.dental.patients.addTitle',editorFile:'AddDentalPatientDialog',signal:'patient-created',permissions:['manage_dental_patients'],detail:'Select an existing contact, or create a contact with the required identity and contact information. Confirm to add the patient.',detailEs:'Selecciona un contacto existente o crea uno con la identidad y los datos obligatorios. Confirma para añadir al paciente.'},
  'dental-schedule':{button:'erp.dental.schedule.new',editor:'erp.dental.schedule.edit',signal:'appointment-created',permissions:['manage_dental_schedule'],detail:'Choose the patient, service, provider, office, date and available time. Resolve validation messages and save the appointment.',detailEs:'Elige paciente, servicio, profesional, consultorio, fecha y hora disponible. Resuelve la validación y guarda la cita.'},
  'dental-treatment-plans':{button:'erp.dental.treatmentPlans.new',editor:'erp.dental.treatmentPlans.new',signal:'treatment-plan-saved',permissions:['manage_dental_treatment_plans'],detail:'Select the patient and name the treatment plan. Review its details and create it, then use the plan details to add treatment items.',detailEs:'Selecciona el paciente y asigna un nombre al plan. Revisa los datos y créalo; después añade tratamientos desde sus detalles.'},
  'restaurant-reservations':{button:'erp.restaurant.reservations.newReservation',editor:'erp.restaurant.reservations.newReservation',signal:'reservation-created',permissions:['manage_sales_orders'],detail:'Enter the customer, party size, date, time and table details. Check availability and create the reservation.',detailEs:'Introduce cliente, comensales, fecha, hora y mesa. Comprueba la disponibilidad y crea la reserva.'},
};
function base(feature:TourFeature,kind:'overview'|'task'):TourDefinition {
  const nameEs=es.get(`guided_tours.feature_${feature.id}`)||es.get(TOUR_TARGETS.find(item=>item.file.endsWith(`/${fileFor(feature)}.tsx`)&&item.tag==='h1')?.labelKey || '')||feature.label;
  return {slug:`${feature.id}-${kind}`,feature:feature.id,category:feature.category,title:localized(`${feature.label}: ${kind==='overview'?'overview':'guided task'}`,`${nameEs}: ${kind==='overview'?'introducción':'tarea guiada'}`),description:localized(`Learn to use ${feature.label} in your workspace. Follow each step using the actual controls.`,`Aprende a utilizar ${nameEs} en tu espacio de trabajo. Sigue cada paso con los controles de la aplicación.`),routes:feature.id==='flows'?['/flows','/flows/new','/flows/:id']:[feature.route],order:kind==='task'?0:10,permissions:[],businessTypes:feature.businessTypes as TourDefinition['businessTypes'],prerequisites:[],kind,media:[],steps:[]};
}
function startStep(feature:TourFeature):TourStep {
  const tab=feature.route.split('?tab=')[1];
  const contentTarget=tab?target(tab,fileFor(feature),'TabsContent')?.selector:undefined;
  return step('start',contentTarget||pageTarget,feature.label,es.get(`guided_tours.feature_${feature.id}`)||feature.label,
    `This is ${feature.label}. Review the information and available controls before continuing.`,
    `Esta sección es ${es.get(`guided_tours.feature_${feature.id}`)||feature.label}. Revisa la información y los controles antes de continuar.`,{type:'next'},
    {route:feature.route});
}
function featureTargets(feature:TourFeature) {
  const related:Record<string,string[]>={inbox:['ConversationList','MessageComposer'],pipeline:['PipelineSearchBar','PipelineSelector'],campaigns:['CampaignDashboard'],pages:['PagesManagement'],'captured-data':['CapturedDataDashboard'],'call-logs':['CallLogsTable','CallLogsFilters'],'dental-queue':['QueueReceptionBoard']};
  return TOUR_TARGETS.filter(item=>item.file.endsWith(`/${fileFor(feature)}.tsx`)||(related[feature.id]||[]).some(file=>item.file.endsWith(`/${file}.tsx`)));
}
export const INITIAL_GUIDED_TOURS:TourDefinition[]=[];
for(const feature of TOUR_FEATURES){
  const overview=base(feature,'overview');overview.steps=[startStep(feature)];
  const controls=featureTargets(feature);
  const filters=controls.filter(item=>(item.tag==='Input'||item.tag==='input'||item.tag==='SelectTrigger')&&/search|filter|date|period|range/i.test(item.labelKey || item.id));
  for(const item of filters.slice(0,2))overview.steps.push(step(`control-${overview.steps.length}`,item.selector,item.label,es.get(item.labelKey)||item.label,`Use ${item.label} to narrow the information shown on this page.`,`Utiliza ${es.get(item.labelKey)||item.label} para limitar la información de esta página.`));
  INITIAL_GUIDED_TOURS.push(overview);
  if(feature.id==='flows')continue;
  const task=base(feature,'task');task.steps=[startStep(feature)];
  const workflow=workflows[feature.id];
  if(workflow){
    const file=workflow.file||fileFor(feature),editorFile=workflow.editorFile||file;
    task.permissions=workflow.permissions;
    task.steps.push(step('open',selector(workflow.button,file,'Button'),'Open the form','Abrir formulario','Select the highlighted button to open the form.','Selecciona el botón resaltado para abrir el formulario.',{type:'click'}));
    if(workflow.field){const field=target(workflow.field,editorFile);if(field)task.steps.push(step('field',field.selector,'Complete the field','Completar el campo',`Enter ${field.label}, then press Tab to continue.`,`Introduce ${es.get(field.labelKey)||field.label} y pulsa Tab para continuar.`,{type:'change',nonEmpty:true}));}
    task.steps.push(step('save',selector(workflow.editor,editorFile,'DialogContent'),'Review and save','Revisar y guardar',workflow.detail,workflow.detailEs,{type:'signal',name:workflow.signal},{consequential:true}));
  }else if(filters.length){
    const control=filters[0];
    task.steps.push(step('filter',control.selector,'Choose what to display','Elegir qué mostrar',`Use ${control.label} to find the information you need. ${control.tag.toLowerCase()==='input'?'Enter a value and press Tab.':'Open the selector and choose an option.'}`,`Utiliza ${es.get(control.labelKey)||control.label} para encontrar la información. ${control.tag.toLowerCase()==='input'?'Introduce un valor y pulsa Tab.':'Abre el selector y elige una opción.'}`,{type:'change',nonEmpty:true}));
    task.steps.push(step('review',pageTarget,'Review the results','Revisar los resultados','Review the displayed records and their status. Use the available detail controls to inspect the relevant record.','Revisa los registros y sus estados. Utiliza los controles de detalle para inspeccionar el registro correspondiente.'));
  }else{
    const tab=feature.route.split('?tab=')[1];
    const tabTarget=tab?target(tab,fileFor(feature),'TabsTrigger'):controls.find(item=>item.tag==='TabsTrigger');
    if(tabTarget)task.steps.push(step('section',tabTarget.selector,'Select the section','Seleccionar la sección','Select this tab to open its controls.','Selecciona esta pestaña para abrir sus controles.',{type:'click'}));
    task.steps.push(step('review',tab?target(tab,fileFor(feature),'TabsContent')?.selector||pageTarget:pageTarget,'Review available actions','Revisar las acciones disponibles','Review the settings and records in this section. Required permissions and configuration determine the actions available to you.','Revisa la configuración y los registros de esta sección. Tus permisos y la configuración determinan las acciones disponibles.'));
  }
  INITIAL_GUIDED_TOURS.push(task);
}
const flows=TOUR_FEATURES.find(feature=>feature.id==='flows')!;
const bot=base(flows,'task');bot.slug='create-bot';bot.title=localized('How to Create a Bot','Cómo crear un bot');bot.permissions=['manage_flows'];bot.prerequisites=['channel'];
bot.steps=[
  step('menu','[data-tour-nav="flows"]','Open Flow Builder','Abrir el editor de flujos','Open Flow Builder from the application menu.','Abre el editor de flujos desde el menú.',{type:'route',path:'/flows'},{prepare:['sidebar']}),
  step('new',selector('flows.new_flow','flows','Button'),'Create a new flow','Crear un flujo','Select New Flow. A Message Trigger node is included automatically.','Selecciona Nuevo flujo. Se incluye automáticamente un nodo de activación de mensajes.',{type:'route',path:'/flows/new'}),
  step('name',selector('flow_builder.main.flow_name','flow-builder','Input'),'Name your bot','Asignar un nombre','Enter a descriptive flow name, then press Tab.','Introduce un nombre descriptivo y pulsa Tab.',{type:'change',nonEmpty:true}),
  step('trigger','.react-flow__node[data-id="trigger-node"]','Review the message trigger','Revisar el activador','Configure when the bot should respond. Keep the default trigger to respond to incoming messages, or set the relevant trigger conditions.','Configura cuándo debe responder el bot. Conserva el activador predeterminado para mensajes entrantes o establece las condiciones.'),
  step('message','[data-tour-node-type="message"]','Add a message node','Añadir un nodo de mensaje','Select Message to add a response node to the canvas.','Selecciona Mensaje para añadir un nodo de respuesta.',{type:'signal',name:'flow-node-added',capture:'message'}),
  step('configure','.react-flow__node[data-id="{{message}}"]','Configure the response','Configurar la respuesta','Edit the message text, then select Done in the node.','Edita el texto del mensaje y selecciona Listo en el nodo.',{type:'signal',name:'flow-node-configured',resource:'message'}),
  step('followup','[data-tour-node-type="message"]','Add a follow-up message','Añadir un mensaje de seguimiento','The first message is connected to the trigger automatically. Add another Message node to practice connecting nodes yourself.','El primer mensaje se conecta al activador automáticamente. Añade otro nodo Mensaje para practicar la conexión manual.',{type:'signal',name:'flow-node-added',capture:'followup'}),
  step('arrange',selector('flow_builder.main.arranging','flow-builder','Button'),'Arrange the nodes','Organizar los nodos','Select Auto-Arrange so the new nodes do not overlap.','Selecciona Organizar automáticamente para que los nodos no se superpongan.',{type:'click'}),
  step('configure-followup','.react-flow__node[data-id="{{followup}}"]','Configure the follow-up','Configurar el seguimiento','Edit this second message and select Done.','Edita este segundo mensaje y selecciona Listo.',{type:'signal',name:'flow-node-configured',resource:'followup'}),
  step('connect','[data-tour="flow-canvas"]','Connect the nodes','Conectar los nodos','Drag a connection from the first Message node output handle to the second Message node input handle. Use Fit view or zoom out if needed.','Arrastra una conexión desde la salida del primer nodo Mensaje hasta la entrada del segundo. Utiliza Ajustar vista o aleja el zoom si es necesario.',{type:'signal',name:'flow-connected',resource:'followup'}),
  step('save',selector('common.save','flow-builder','Button'),'Save the flow','Guardar el flujo','Select Save to review the save options.','Selecciona Guardar para revisar las opciones.',{type:'click'}),
  step('save-only',selector('flow_builder.save_without_clearing_sessions','flow-builder','Button'),'Save only','Solo guardar','Select Save only. This creates your real draft without clearing bot sessions.','Selecciona Solo guardar. Esto crea el borrador real sin borrar las sesiones del bot.',{type:'signal',name:'flow-saved',capture:'flow'},{consequential:true}),
  step('back',selector('flow_builder.main.go_back','flow-builder','Button'),'Return to flows','Volver a los flujos','Use Go Back to return to the flow list.','Utiliza Volver para regresar a la lista.',{type:'route',path:'/flows'}),
  step('activate','[data-tour-flow-status="{{flow}}"]','Activate the bot','Activar el bot','Open the status selector and choose Active for the flow you created.','Abre el selector de estado y elige Activo para el flujo creado.',{type:'signal',name:'flow-activated',resource:'flow'},{consequential:true}),
  step('assign','[data-tour-flow-assign="{{flow}}"]','Choose a channel','Elegir un canal','Open Assign for your new flow.','Abre Asignar para tu nuevo flujo.',{type:'click'}),
  step('assignment',selector('flows.manage_flow_assignments','flows','DialogContent'),'Assign your bot','Asignar el bot','Choose the connected channel and confirm Assign. The new assignment is initially inactive.','Elige el canal conectado y confirma Asignar. La nueva asignación está inicialmente inactiva.',{type:'signal',name:'flow-assigned',resource:'flow'},{consequential:true}),
  step('enable-channel',selector('flows.manage_flow_assignments','flows','DialogContent'),'Activate the channel assignment','Activar la asignación del canal','Select Activate on the channel assignment you just created. Your bot can now respond to real incoming messages on that channel.','Selecciona Activar en la asignación que acabas de crear. El bot podrá responder a mensajes reales en ese canal.',{type:'signal',name:'flow-channel-activated',resource:'flow'},{consequential:true}),
];
INITIAL_GUIDED_TOURS.push(bot);
// Primary tasks that use inline editors or compose workflows across page components.
const taskFor=(id:string)=>INITIAL_GUIDED_TOURS.find(tour=>tour.feature===id&&tour.kind==='task')!;
const replaceTask=(id:string,title:string,titleEs:string,steps:TourStep[],permissions:string[]=[])=>{
  const tour=taskFor(id);if(!tour)return;tour.title=localized(title,titleEs);tour.steps=[startStep(TOUR_FEATURES.find(feature=>feature.id===id)!),...steps];tour.permissions=permissions;
};
const inlineTask=(id:string,title:string,titleEs:string,body:string,bodyEs:string,signal:string,targetSelector=pageTarget,permissions:string[]=[])=>replaceTask(id,title,titleEs,[step('configure',targetSelector,title,titleEs,body,bodyEs,{type:'signal',name:signal},{consequential:true})],permissions);
const createTask=(id:string,buttonKey:string,buttonFile:string,editorKey:string,editorFile:string,signal:string,title:string,titleEs:string,body:string,bodyEs:string,permissions:string[])=>replaceTask(id,title,titleEs,[
  step('open',selector(buttonKey,buttonFile,'Button'),'Open the form','Abrir el formulario','Select the highlighted button.','Selecciona el botón resaltado.',{type:'click'}),
  step('save',selector(editorKey,editorFile,'DialogContent'),title,titleEs,body,bodyEs,{type:'signal',name:signal},{consequential:true}),
],permissions);
createTask('pipeline','pipeline.add_deal','KanbanBoard','pipeline.add_new_deal','AddDealModal','deal-created','Create a deal','Crear una oportunidad','Enter a deal title, select its contact, stage, owner and value, then create the deal.','Introduce un título, selecciona contacto, etapa, responsable y valor y crea la oportunidad.',['manage_pipeline']);
createTask('templates','templates.create','templates','templates.create.title','CreateTemplateModal','template-saved','Create a message template','Crear una plantilla de mensaje','Choose the channel, template name, language and category. Write the message, configure variables and media, and submit the template. Provider approval may still be required.','Elige canal, nombre, idioma y categoría. Escribe el mensaje, configura variables y medios y envía la plantilla. Puede requerir aprobación del proveedor.',['manage_templates']);
replaceTask('campaigns','Create a campaign draft','Crear un borrador de campaña',[
  step('open',selector('campaigns.create_campaign','CampaignDashboard','Button'),'Create a campaign','Crear una campaña','Open the campaign builder.','Abre el editor de campañas.',{type:'click'}),
  step('save',pageTarget,'Configure and save the draft','Configurar y guardar el borrador','Complete the campaign name, channel, audience, message and scheduling sections. Use Save Draft after reviewing validation. Launching a campaign is a separate action.','Completa nombre, canal, audiencia, mensaje y programación. Utiliza Guardar borrador después de revisar la validación. El lanzamiento es una acción separada.',{type:'signal',name:'campaign-saved'},{consequential:true}),
],['create_campaigns']);
replaceTask('pages','Create a company page','Crear una página de empresa',[
  step('open',selector('pages.create','PagesManagement','Button'),'Create a page','Crear una página','Open the page editor.','Abre el editor de páginas.',{type:'click'}),
  step('save',pageTarget,'Write and save the page','Escribir y guardar la página','Set a title and slug, choose a template and add content. Review the preview and save the page.','Establece título y dirección, elige una plantilla y añade contenido. Revisa la vista previa y guarda la página.',{type:'signal',name:'page-saved'},{consequential:true}),
],['manage_pages']);
replaceTask('erp-dashboard','Inspect dashboard performance','Consultar el rendimiento',[
  step('period','[data-tour="erp-dashboard-period"]','Choose a period','Elegir un período','Choose a different reporting period.','Elige otro período de análisis.',{type:'change',nonEmpty:true}),
  step('results',pageTarget,'Review performance','Revisar el rendimiento','Compare revenue, orders and inventory indicators for the selected period.','Compara ingresos, pedidos e inventario para el período elegido.'),
]);
replaceTask('erp-reports','Run an ERP report','Consultar un informe ERP',[
  step('type','[data-tour="erp-report-type"]','Choose a report','Elegir un informe','Choose the report you need and review its date and filter controls.','Elige el informe y revisa sus controles de fecha y filtros.',{type:'change',nonEmpty:true}),
  step('results',pageTarget,'Review the report','Revisar el informe','Read the totals and detailed records. Export is available when your role permits it.','Consulta totales y registros detallados. La exportación depende de tus permisos.'),
]);
inlineTask('my-calendar','Configure personal availability','Configurar la disponibilidad personal','Choose your calendar provider, working days, hours and scheduling rules, then save your calendar settings.','Elige proveedor de calendario, días laborables, horario y reglas de programación y guarda la configuración.','settings-saved');
inlineTask('dental-booking-settings','Configure dental booking','Configurar las reservas dentales','Configure bookable services, offices, providers, working hours and booking rules. Review validation, then Save.','Configura servicios, consultorios, profesionales, horarios y reglas de reserva. Revisa la validación y guarda.','settings-saved',pageTarget,['manage_dental_schedule']);
inlineTask('dental-chart','Save an odontogram snapshot','Guardar una versión del odontograma','Open a patient chart, select a tooth and record the findings with the chart controls. Review the chart and select Save snapshot.','Abre el odontograma del paciente, selecciona un diente y registra los hallazgos. Revisa el odontograma y selecciona Guardar versión.','chart-saved',pageTarget,['edit_dental_chart']);
inlineTask('restaurant-pos','Create and send a restaurant order','Crear y enviar un pedido','Choose the service type, table and customer. Add menu items, quantities and modifiers. Review the order and select Send to Kitchen.','Elige tipo de servicio, mesa y cliente. Añade productos, cantidades y modificadores. Revisa el pedido y selecciona Enviar a cocina.','restaurant-order-saved',pageTarget,['manage_sales_orders']);
createTask('dental-patient-notes','erp.dental.clinical.addNote','ClinicalProgressNotes','erp.dental.clinical.editNote','ClinicalProgressNotes','clinical-note-saved','Add a clinical progress note','Añadir una nota clínica','Choose the specialty and note template if applicable. Enter the clinical findings, treatment and tooth references, then save the note.','Elige especialidad y plantilla si corresponde. Introduce hallazgos, tratamiento y referencias dentales y guarda la nota.',['manage_dental_patients']);
inlineTask('dental-patient-profile','Update a patient profile','Actualizar el perfil de un paciente','Review the selected patient identity. Edit the relevant profile fields and select Save changes.','Comprueba la identidad del paciente. Modifica los campos necesarios y selecciona Guardar cambios.','patient-updated',selector('profile','erp/dental/patient-detail','TabsContent'),['manage_dental_patients']);
inlineTask('dental-patient-history','Record patient vital signs','Registrar constantes vitales','Review medical history, allergies and screening records. In vital signs, enter the new measurements and save the record.','Revisa historia clínica, alergias y pruebas. Introduce las nuevas mediciones en constantes vitales y guarda el registro.','patient-updated',selector('history','erp/dental/patient-detail','TabsContent'),['manage_dental_patients']);
const settingsTasks:[string,string,string,string,string][]=[
  ['settings-general','Set the default timezone','Establecer la zona horaria','Choose the company default timezone and save General settings.','Elige la zona horaria de la empresa y guarda la configuración general.'],
  ['settings-inbox','Configure inbox availability','Configurar la disponibilidad de la bandeja','Configure working hours, availability and assignment settings, then save.','Configura horario laboral, disponibilidad y asignación y guarda.'],
  ['settings-whatsapp-behavior','Configure WhatsApp behavior','Configurar el comportamiento de WhatsApp','Review typing, reading and delivery behavior. Adjust the required options and save settings.','Revisa escritura, lectura y entrega. Ajusta las opciones y guarda la configuración.'],
  ['settings-personalization','Customize header shortcuts','Personalizar accesos directos','Add or edit a shortcut, choose its destination, label and icon, apply it, then Save changes.','Añade o edita un acceso directo, elige destino, etiqueta e icono, aplícalo y guarda los cambios.'],
  ['settings-pipeline','Configure pipeline automation','Configurar automatización de oportunidades','Choose the pipeline and stage for automatic additions, configure the relevant rules, then save.','Elige embudo y etapa para altas automáticas, configura las reglas y guarda.'],
  ['settings-email-settings','Configure outbound email','Configurar el correo saliente','Enter your SMTP or SES configuration, review sender details and save the configuration. Testing sends a real email.','Introduce la configuración SMTP o SES, revisa el remitente y guarda. Las pruebas envían un correo real.'],
  ['settings-custom-css','Save custom styling','Guardar estilos personalizados','Edit the company CSS, review its effect and select Save Custom CSS.','Edita el CSS de la empresa, revisa el resultado y selecciona Guardar CSS personalizado.'],
  ['settings-custom-js','Save custom JavaScript','Guardar JavaScript personalizado','Review and edit the company JavaScript, then select Save Custom JavaScript. This code affects your company workspace.','Revisa y edita el JavaScript de la empresa y selecciona Guardar JavaScript personalizado. Este código afecta al espacio de trabajo.'],
  ['erp-settings-ordernotifications','Configure order notifications','Configurar notificaciones de pedidos','Configure the channel, recipient and status messages, then save the order-notification settings.','Configura canal, destinatario y mensajes de estado y guarda las notificaciones.'],
  ['erp-settings-invoicetemplates','Configure invoice printing','Configurar la impresión de facturas','Choose A4 or thermal layout and configure invoice fields, branding and footer. Save the template settings.','Elige formato A4 o térmico y configura campos, marca y pie de página. Guarda la plantilla.'],
  ['erp-settings-electronicinvoicing','Configure electronic invoicing','Configurar la facturación electrónica','Enter the provider configuration, environment and numbering information. Save the configuration; connection testing is available separately.','Introduce proveedor, entorno y numeración. Guarda la configuración; la prueba de conexión está disponible por separado.'],
  ['erp-settings-paymentgateways','Configure a payment gateway','Configurar una pasarela de pago','Choose a payment gateway, enter its account configuration and credentials, and save that gateway.','Elige una pasarela, introduce configuración y credenciales y guarda esa pasarela.'],
];
for(const [id,title,titleEs,body,bodyEs]of settingsTasks){
  const feature=TOUR_FEATURES.find(item=>item.id===id)!;const tab=feature.route.split('?tab=')[1];
  inlineTask(id,title,titleEs,body,bodyEs,'settings-saved',selector(tab,fileFor(feature),'TabsContent'),[id.startsWith('erp-')?'manage_erp_settings':'manage_settings']);
}
createTask('settings-ai-credentials','settings.ai_credentials.add_credential','CompanyAiCredentialsTab','settings.ai_credentials.create_title','CompanyAiCredentialsTab','settings-saved','Add an AI credential','Añadir una credencial de IA','Choose the provider and enter its required credentials. Validate the connection and create the credential.','Elige el proveedor e introduce las credenciales. Valida la conexión y crea la credencial.',['manage_settings']);
createTask('settings-contact-custom-fields','settings.custom_fields.add_field','ContactCustomFieldsSettings','settings.custom_fields.add_field','ContactCustomFieldsSettings','settings-saved','Create a custom contact field','Crear un campo personalizado','Choose the entity, field label, type and validation settings, then add the custom field.','Elige entidad, etiqueta, tipo y validación y añade el campo personalizado.',['manage_settings']);
createTask('erp-settings-currencies','erp.settings.currencies.actions.addCurrency','erp/settings','erp.settings.currencyDialog.editTitle','erp/settings','settings-saved','Add a currency','Añadir una moneda','Enter the currency code, name, symbol and exchange rate, then save.','Introduce código, nombre, símbolo y tipo de cambio y guarda.',['manage_erp_settings']);
createTask('erp-settings-tax','erp.settings.taxRules.actions.addRule','erp/settings','erp.settings.taxRuleDialog.editTitle','erp/settings','settings-saved','Create a tax rule','Crear una regla fiscal','Enter the rule name, tax type, rate and applicability, then save the tax rule.','Introduce nombre, tipo de impuesto, tasa y aplicación y guarda la regla.',['manage_erp_settings']);
createTask('erp-settings-progressnotetemplates','erp.dental.clinical.templates.add','DentalProgressNoteTemplatesPanel','erp.dental.clinical.templates.edit','DentalProgressNoteTemplatesPanel','settings-saved','Create a clinical note template','Crear una plantilla de nota clínica','Name the template, choose its specialty, and write its sections in the selected language. Save the template.','Asigna nombre y especialidad y redacta las secciones en el idioma seleccionado. Guarda la plantilla.',['manage_erp_settings']);
createTask('calendar','calendar.schedule_appointment','calendar','calendar.schedule_new_appointment','calendar','appointment-created','Schedule an appointment','Programar una cita','Select the calendar provider, date and available time. Enter the attendee and appointment details, then schedule the appointment.','Selecciona proveedor, fecha y hora disponible. Introduce los datos de asistentes y cita y prográmala.',['manage_calendar']);
createTask('settings-team','settings.team.members.add_member','TeamMembersList','settings.team.create.title','InviteTeamMemberModal','settings-saved','Add a team member','Añadir un miembro al equipo','Enter the member name, email and account details, assign the role and permissions, then create the team member.','Introduce nombre, correo y datos de cuenta, asigna rol y permisos y crea el miembro.',['manage_team']);
createTask('erp-settings-catalog','erp.common.create','CatalogSetupPanel','erp.common.edit','CatalogSetupPanel','settings-saved','Create a catalog category','Crear una categoría de catálogo','Choose Categories, enter the category name and relevant catalog settings, then save.','Elige Categorías, introduce el nombre y los datos del catálogo y guarda.',['manage_erp_settings']);
createTask('erp-settings-customfields','erp.common.create','ProductCustomFieldsPanel','erp.common.edit','ProductCustomFieldsPanel','settings-saved','Create a product field','Crear un campo de producto','Set the field name, type, options and required/default behavior, then save the field.','Establece nombre, tipo, opciones y comportamiento obligatorio o predeterminado y guarda el campo.',['manage_erp_settings']);
replaceTask('settings-api','Create an API key','Crear una clave API',[
  step('open','[data-tour-api-create]','Create an API key','Crear una clave API','Select Create API Key.','Selecciona Crear clave API.',{type:'click'}),
  step('create',selector('settings.api_access.dialog.create_title','ApiAccessTab','DialogContent'),'Name and create the key','Nombrar y crear la clave','Name this integration and create the key. Store the displayed secret securely; tours never record it.','Asigna un nombre a la integración y crea la clave. Guarda el secreto mostrado de forma segura; los recorridos no lo registran.',{type:'signal',name:'settings-saved'},{consequential:true}),
],['manage_settings']);
replaceTask('settings-channels','Connect website chat','Conectar el chat del sitio',[
  step('open','[data-tour="channel-webchat"]','Choose WebChat','Elegir WebChat','Select WebChat to configure a website channel.','Selecciona WebChat para configurar un canal web.',{type:'click'}),
  step('create',selector('settings.webchatConnectionForm.title','WebChatConnectionForm','DialogContent'),'Configure the channel','Configurar el canal','Enter an account name and widget branding, choose its language and settings, then create the channel. Copy the installation snippet from the resulting dialog.','Introduce un nombre y la marca del widget, elige idioma y configuración y crea el canal. Copia el código de instalación del diálogo resultante.',{type:'signal',name:'channel-created'},{consequential:true}),
],['manage_channels']);
replaceTask('dental-queue','Check in a patient','Registrar la llegada de un paciente',[
  step('open','[data-tour="queue-check-in"]','Check in','Registrar llegada','Open the check-in form.','Abre el formulario de registro.',{type:'click'}),
  step('issue','[data-tour="queue-check-in-form"]','Issue the ticket','Emitir el turno','Select the appointment or walk-in patient, professional, office and service. Confirm to issue the queue ticket.','Selecciona cita o paciente sin cita, profesional, consultorio y servicio. Confirma para emitir el turno.',{type:'signal',name:'queue-updated'},{consequential:true}),
],['manage_dental_schedule']);
replaceTask('erp-settings-consenttemplates','Create a consent template','Crear una plantilla de consentimiento',[
  step('open',selector('erp.dental.consent.add','ConsentTemplatesWorkspace','Button'),'Add a template','Añadir una plantilla','Open Add consent template.','Abre Añadir plantilla de consentimiento.',{type:'click'}),
  step('save','[data-tour="consent-template-editor"]','Write and save the consent','Redactar y guardar el consentimiento','Enter a title and consent text, configure the included patient fields and translations, then save.','Introduce título y texto, configura los campos de paciente y traducciones y guarda.',{type:'signal',name:'settings-saved'},{consequential:true}),
],['manage_erp_settings']);
inlineTask('erp-settings-restaurant','Create a kitchen station','Crear una estación de cocina','Enter a station code and name, select a warehouse if needed, then select Create.','Introduce código y nombre de estación, elige almacén si corresponde y selecciona Crear.','settings-saved',selector('restaurant','erp/settings','TabsContent'),['manage_erp_settings']);
createTask('restaurant-table-floors','erp.restaurant.tableFloors.bulkCreate','erp/restaurant/table-floors','erp.restaurant.tableFloors.bulkCreate','erp/restaurant/table-floors','layout-saved','Create restaurant tables','Crear mesas del restaurante','Choose the floor, table-code prefix, starting number, count and capacity. Confirm to create the tables.','Elige piso, prefijo, número inicial, cantidad y capacidad. Confirma para crear las mesas.',['manage_erp_settings']);
inlineTask('restaurant-kitchen','Process a kitchen ticket','Procesar un pedido de cocina','Review queued tickets and their items. Select Start on the ticket you are preparing, or Complete when its preparation is finished.','Revisa pedidos e ingredientes. Selecciona Iniciar en el pedido que preparas o Completar al terminar.','restaurant-order-saved',pageTarget,['manage_sales_orders']);
inlineTask('restaurant-dispatch','Update a dispatch','Actualizar un despacho','Review the delivery board and choose the next valid status on the relevant dispatch. Confirm its status update.','Revisa el tablero de entregas y elige el siguiente estado válido del despacho. Confirma la actualización.','restaurant-order-saved',pageTarget,['manage_sales_orders']);
inlineTask('restaurant-delivery','Assign a delivery driver','Asignar un repartidor','Locate the delivery, enter or select the driver, then select Assign Driver.','Localiza la entrega, introduce o selecciona el repartidor y selecciona Asignar.','restaurant-order-saved',pageTarget,['manage_sales_orders']);
replaceTask('restaurant-floor','Open the table layout manager','Abrir la gestión de mesas',[
  step('layout',selector('erp.restaurant.floor.manageLayouts','erp/restaurant/floor','Button'),'Manage floors and tables','Gestionar pisos y mesas','Open Manage Table/Floors to arrange your restaurant layout.','Abre Gestionar mesas y pisos para organizar el restaurante.',{type:'route',path:'/erp/restaurant/table-floors'}),
  step('review',pageTarget,'Inspect the layout','Revisar la distribución','Choose a floor and select a table to inspect its capacity, position and settings. Use the Create restaurant tables tour to add new tables.','Elige piso y mesa para consultar capacidad, posición y configuración. Utiliza el recorrido Crear mesas para añadir mesas.'),
]);
replaceTask('call-logs','Find a call record','Buscar un registro de llamada',[
  step('search',selector('call_logs.search_placeholder','CallLogsDashboard','Input'),'Search calls','Buscar llamadas','Enter a contact name and press Tab. Use status, direction and date filters to narrow the results.','Introduce un nombre y pulsa Tab. Utiliza filtros de estado, dirección y fecha.',{type:'change',nonEmpty:true}),
  step('review',pageTarget,'Review the call','Revisar la llamada','Open the relevant record to inspect duration, outcome and any recording available to your role.','Abre el registro para consultar duración, resultado y grabación si tus permisos lo permiten.'),
]);
inlineTask('profile','Update your profile','Actualizar tu perfil','Edit your name and personal profile details, then select Save Changes.','Edita tu nombre y datos personales y selecciona Guardar cambios.','settings-saved');
inlineTask('dental-patient-documents','Attach a patient document','Adjuntar un documento del paciente','Choose a file, enter its document details and select Upload document. Verify that the correct patient is selected before uploading.','Elige un archivo, introduce sus datos y selecciona Subir documento. Comprueba que el paciente sea correcto.','document-uploaded',selector('documents','erp/dental/patient-detail','TabsContent'),['manage_dental_patients']);
replaceTask('inbox','Reply to a conversation','Responder a una conversación',[
  step('conversation','[data-tour="conversation-list"]','Choose a conversation','Elegir una conversación','Select the conversation you want to reply to. Check the recipient and channel.','Selecciona la conversación a la que quieres responder. Comprueba destinatario y canal.',{type:'signal',name:'conversation-selected',capture:'conversation'}),
  step('reply','[data-tour="message-composer"]','Write and send a reply','Escribir y enviar una respuesta','Write a reply, check the recipient and select Send. This sends a real message. Any channel restrictions and confirmation prompts still apply.','Escribe la respuesta, comprueba el destinatario y selecciona Enviar. Se enviará un mensaje real. Se aplican las restricciones y confirmaciones del canal.',{type:'signal',name:'message-sent',resource:'conversation'},{consequential:true}),
],['manage_conversations']);
taskFor('inbox').prerequisites=['conversation','channel'];
replaceTask('email','Compose and send an email','Redactar y enviar un correo',[
  step('compose',selector('email.compose','EmailInterface','Button'),'Compose an email','Redactar un correo','Open Compose to write an email from this channel.','Abre Redactar para escribir un correo desde este canal.',{type:'click'}),
  step('send','[data-tour="email-composer"]','Review and send the email','Revisar y enviar el correo','Enter the recipient, subject and message. Review attachments and select Send when ready. This sends a real email.','Introduce destinatario, asunto y mensaje. Revisa los archivos adjuntos y selecciona Enviar. Se enviará un correo real.',{type:'signal',name:'email-sent'},{consequential:true}),
]);
replaceTask('settings-ai-usage','Inspect AI usage','Consultar el uso de IA',[
 step('period','[data-tour="ai-usage-period"]','Choose a reporting period','Elegir un período','Select a different period to compare AI usage, costs and limits.','Selecciona otro período para comparar uso, costes y límites de IA.',{type:'change',nonEmpty:true}),
 step('results',selector('ai-usage','settings','TabsContent'),'Review usage and costs','Revisar uso y costes','Inspect token consumption, costs by provider and any usage alerts for this period.','Consulta consumo de tokens, costes por proveedor y alertas del período.'),
]);
for(const id of ['dental-chart','dental-schedule','dental-treatment-plans','dental-queue'])taskFor(id).prerequisites=['patient'];
for(const id of ['erp-inventory','erp-sales-orders','erp-purchase-orders','restaurant-pos'])taskFor(id).prerequisites=['product'];
for(const definition of INITIAL_GUIDED_TOURS){
  // Inline workflows can open nested editors; keep the native Joyride spotlight in that modal scope.
  for(const item of definition.steps) if(item.completion.type==='signal' && (item.target===pageTarget || item.target.includes('.tabscontent.'))) item.followDialogs=true;
  tourDefinitionSchema.parse(definition);
}
